### PR TITLE
cts: tcl nit cleanup, avoid copy and paste of it later

### PR DESCRIPTION
**Pull request by oharboe**

### CODE REVIEW

**Comment by maliberty** [comment]
I'm not sure if you are behind master or if this change is incorrect.  There are no failures at the head of master currently.

**Comment by oharboe** [comment]
> I'm not sure if you are behind master or if this change is incorrect. There are no failures at the head of master currently.

It is just a syntax nit.

**Comment by oharboe** [comment]
@maliberty The error in the build is unrelated to this PR and this PR is on top of latest master. What's going on?

You're going to hear about this from other PRs soon enough if I didn't miss anything here...

```
[ERROR] detailedroute__route__drc_errors fail test: 11.0 <= 0.0
```

**Comment by maliberty** [comment]
I have not seen this in other PRs and master continues to pass.

**Comment by oharboe** [comment]
> I have not seen this in other PRs and master continues to pass.

Curious....

**Comment by oharboe** [comment]
@maliberty rebuild to see if the problem goes away.

**Comment by oharboe** [comment]
Looking at the log, with this change, the commandline for sky130hd/microwatt is:

```
clock_tree_synthesis -sink_clustering_enable -balance_levels -distance_between_buffers 600
```

On master(using https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/1860):

```
clock_tree_synthesis -sink_clustering_enable -balance_levels -distance_between_buffers 600
```

Curiouser and curiouser...

**Comment by oharboe** [comment]
Ran it locally and it worked:

```
$ make DESIGN_CONFIG=designs/sky130hd/microwatt/config.mk
[deleted]
OpenROAD v2.0-12717-gfe4d260d9
[deleted]
clock_tree_synthesis -sink_clustering_enable -balance_levels -distance_between_buffers 600
[deleted]
$ make DESIGN_CONFIG=designs/sky130hd/microwatt/config.mk metadata
[deleted]
Total                           3797
[WARN] Tag globalroute__timing__clock__slack not found in ././logs/sky130hd/microwatt/base/5_1_grt.log. Will use N/A.
[WARN] Overwriting Tag finish__runtime__total
[WARN] Overwriting Tag finish__cpu__total
[WARN] Overwriting Tag finish__mem__peak
[INFO] synth__design__instance__area__stdcell pass test: 622922.432 <= 634495.72
[INFO] constraints__clocks__count pass test: 2.0 == 2.0
[INFO] placeopt__design__instance__area pass test: 4825330.0 <= 5455002.0
[INFO] placeopt__design__instance__count__stdcell pass test: 154636.0 <= 173812.0
[INFO] detailedplace__design__violations pass test: 0.0 == 0.0
[INFO] cts__design__instance__count__setup_buffer pass test: 0.0 <= 15114.0
[INFO] cts__design__instance__count__hold_buffer pass test: 4066.0 <= 15114.0
[INFO] detailedroute__route__wirelength pass test: 8093794.0 <= 9558824.0
[INFO] detailedroute__route__drc_errors pass test: 0.0 <= 0.0
[INFO] finish__timing__setup__ws pass test: -0.117936 >= -1.61
[INFO] finish__design__instance__area pass test: 4947180.0 <= 5514388.0
[INFO] finish__timing__drv__setup_violation_count pass test: 15.0 <= 7557.0
[INFO] finish__timing__drv__hold_violation_count pass test: 10.0 <= 200.0
[INFO] finish__timing__wns_percent_delay pass test: -0.567963 >= -13.96
All metadata rules passed (14 rules)
$ git log
commit bd1fa6b9d16a9c854fc470afaea69a02866b4aaa (HEAD, pinata/cts-tcl-nit)
Author: Øyvind Harboe <oyvind.harboe@zylin.com>
Date:   Sat Mar 23 14:11:33 2024 +0100

    cts: tcl nit cleanup, avoid copy and paste of it later
    
    rebuild
    
    Signed-off-by: Øyvind Harboe <oyvind.harboe@zylin.com>

commit 4f99f1dda7d0171448a2e1a0facbc2e22e633099 (origin/master, origin/HEAD)
Merge: 6bf26f74 bd4f79c3
Author: Matt Liberty <mliberty@precisioninno.com>
Date:   Fri Mar 22 21:05:39 2024 -0700

    Merge pull request #1875 from The-OpenROAD-Project-staging/ca53-metrics
    
    Update the metrics for gf12/ca53

commit bd4f79c39c76e84481fd8c66026f9394143d0149
Author: Matt Liberty <mliberty@precisioninno.com>
Date:   Fri Mar 22 21:00:14 2024 -0700
```

**Comment by oharboe** [comment]
@maliberty No change, I just modified the comment of the git commit to make it rebuild. Now it works: https://jenkins.openroad.tools/blue/organizations/jenkins/OpenROAD-flow-scripts-Public%2Fpublic_tests_all-pr/detail/PR-1877-head/2/pipeline/1083

**Comment by oharboe** [comment]
Works too: https://jenkins.openroad.tools/blue/organizations/jenkins/OpenROAD-flow-scripts-Public%2Fpublic_tests_all-pr/detail/PR-1877-merge/2/pipeline/1084

**Comment by oharboe** [comment]
@maliberty Thoughts? Master is flaky???

**Comment by oharboe** [comment]
@maliberty unrelated network error

**Comment by maliberty** [comment]
@vvbandeira any idea about the build issues in this PR?

I restarted pr-merge

**Comment by vvbandeira** [comment]
> @maliberty No change, I just modified the comment of the git commit to make it rebuild. Now it works: https://jenkins.openroad.tools/blue/organizations/jenkins/OpenROAD-flow-scripts-Public%2Fpublic_tests_all-pr/detail/PR-1877-head/2/pipeline/1083

The issue in the build above was a "Bad Gateway 502" error during clone, this usually indicates an issue upstream from GitHub.

**Comment by maliberty** [comment]
@vvbandeira why the fail on microwatt and then a pass with no change?

**Review by maliberty — APPROVED** [review]

**Comment by vvbandeira** [comment]
> @vvbandeira why the fail on microwatt and then a pass with no change?

That I do not know. There were no changes in the CI. The only thing I can think of would be a non-det from OR.

**Pull request merged**
