### PR TITLE
macro grid for asap7

### PR DESCRIPTION
**Pull request by vijayank88**
Added macro grid for ASAP7 platform.

### CODE REVIEW

**Comment by vijayank88** [comment]
@maliberty 
Any suggestion why uart_blocks failing during IR drop?
IR Drop is disable right?

**Comment by vijayank88** [comment]
#965 causing PSM IR Drop report error.

**Comment by maliberty** [comment]
> @maliberty Any suggestion why uart_blocks failing during IR drop? IR Drop is disable right?

ir drop is enabled except for asap7/swerv_wrapper (tbd)

**Comment by maliberty** [comment]
In your pdn changes you have:
add_pdn_connect -grid {CORE_macro_grid_1} -layers {M4 M5}

in the uart design the power pins are on M5 and need to be connected to M6.

**Comment by vijayank88** [comment]
@maliberty 
`uart-blocks` is based on `BLOCKS` implementation. Resolved by adding separate pdn grid for the same.

**Review by maliberty — APPROVED** [review]

**Pull request merged**
