### PR TITLE
Mock array 64 bit, 0.19mm^2

### PR DESCRIPTION
**Pull request by oharboe**
Running times are now reasonable with latest master openroad for a 64 bit datapath:

```
Log                       Elapsed seconds
1_1_yosys                          3
2_1_floorplan                      1
2_2_floorplan_io                   1
2_3_tdms_place                     1
2_5_tapcell                        1
2_6_pdn                           40
3_1_place_gp_skip_io               1
3_2_place_iop                      1
3_3_place_gp                       9
3_4_resizer                        4
3_5_opendp                         4
4_1_cts                            8
4_2_cts_fillcell                   3
5_1_fastroute                      9
5_2_TritonRoute                  518
6_1_merge                          4
6_report                          72
```

image

### CODE REVIEW

**Comment by oharboe** [comment]
@louiic @osamahammad21 FYI

**Comment by maliberty** [comment]
In the master CI this design takes 3m55s but with this PR it takes 21m30s.  Is there some advantage in coverage in making this bigger/slower?  It isn't obvious that this tests anything additional.

**Comment by oharboe** [comment]
> In the master CI this design takes 3m55s but with this PR it takes 21m30s. Is there some advantage in coverage in making this bigger/slower? It isn't obvious that this tests anything additional.

Yes, the CTS issues in routing by abutment and that the PDN is now more realistically sized makes 64 bit more relevant.

Ultimately I want to see a nontrivial horizontal routing by abutment test case in regression tests.

**Comment by maliberty** [comment]
I'm not sure what you mean routing in a by-abutment test case as there is no routing when abutting.  Are you referring to abutting in just one direction?

**Comment by oharboe** [comment]
> I'm not sure what you mean routing in a by-abutment test case as there is no routing when abutting.

"Routing by abutment" is a manner of speaking for when there is no routing, because there is zero spacing, yes. It is something that I have heard people use...

> Are you referring to abutting in just one direction?

Yes: when abutting in one direction (horizontal) and leaving vertical space for CTS to work, then hold cells can be a problem because the flow is trying to insert them on connections that are abutted.

**Comment by oharboe** [comment]
Perhaps there are some more low hanging fruits for the below top three items in the time summary?

Reporting seems promising place to look, it hasn't gotten much attention yet.... Also, I've seen it take pathologically long on designs as a function of area.


```
Log                       Elapsed seconds
5_2_TritonRoute                  692
6_report                         179
2_6_pdn                          103
```

**Comment by rovinski** [comment]
> hold cells can be a problem because the flow is trying to insert them on connections that are abutted.

Have you tried marking those nets as `dont_touch`?

**Review by maliberty — APPROVED** [review]

**Comment by maliberty** [comment]
I haven't heard much that relates to having a larger design but it seems tolerable for now.  Routing by abutment is a fine term but this PR doesn't show that so I was confused as to why you used it in answer to my query.

**Comment by oharboe** [comment]
@maliberty @rovinski #1200 is the issue I filed with the problems that I ran into with this version of mock-array when I tried to tweak it to do routing by abutment.

**Pull request merged**
