### PR TITLE
mock-array: update Element/constraint.sdc

### PR DESCRIPTION
**Pull request by oharboe**
For discussion with @louiic there are two registered outputs in io_lsbOuts_* to avoid a long flight path

I'm trying to learn about virtual clocks and tried to update element's .sdc file.

I get hold cells inserted that fail in global routing as the cells are routed by abutment.

image

### CODE REVIEW

**Comment by oharboe** [comment]
After the second commit, it passes global routing, but there are DRC errors due to hold cells(they all appear in the same place), which breaks routing by abutment:

image

image

**Comment by oharboe** [comment]
I wonder why a hold cell was inserted, the min path would have held without it. The hold cell introduces 20.63 delay and the slack is 26.65. 

image

**Comment by maliberty** [comment]
You should look at the path right before timing repair and see what it looked like then.

**Comment by oharboe** [comment]
> You should look at the path right before timing repair and see what it looked like then.

A slight negative slack prior to repair. Still: surprising that the positive slack is larger than the hold delay + negative slack. I'm sure that has some sort of interesting explanation. :-)

```
make do-cts CTS_SNAPSHOTS=1
make gui_4_1_pre_repair_hold_setup.odb
```

```
>>> report_checks -path_delay min -through {ces_0_2/io_ins_left[28]} -fields {net slew}
Startpoint: ces_0_3 (rising edge-triggered flip-flop clocked by clock)
Endpoint: ces_0_2 (rising edge-triggered flip-flop clocked by clock)
Path Group: clock
Path Type: min

Fanout    Slew   Delay    Time   Description
----------------------------------------------------------------------
                  0.00    0.00   clock clock (rise edge)
                305.38  305.38   clock network delay (propagated)
         36.02    0.00  305.38 ^ ces_0_3/clock (Element)
          5.10  161.05  466.43 ^ ces_0_3/io_outs_left[28] (Element)
     1                           ces_0_2_io_ins_left[28] (net)
          5.10    0.00  466.43 ^ ces_0_2/io_ins_left[28] (Element)
                        466.43   data arrival time

                  0.00    0.00   clock clock (rise edge)
                356.09  356.09   clock network delay (propagated)
                 20.00  376.09   clock uncertainty
                  0.00  376.09   clock reconvergence pessimism
                        376.09 ^ ces_0_2/clock (Element)
                 90.92  467.01   library hold time
                        467.01   data required time
----------------------------------------------------------------------
                        467.01   data required time
                       -466.43   data arrival time
----------------------------------------------------------------------
                         -0.58   slack (VIOLATED)
```

**Comment by oharboe** [comment]
```
>>> report_check_types
Group                                  Slack
--------------------------------------------
clock                                  -0.27
clock_vir                             156.19
clock                                  71.02
clock_vir                              69.15

max slew

Pin                                    Limit    Slew   Slack
------------------------------------------------------------
ces_4_0/clock                         300.00  166.31  133.69 (MET)

max capacitance

Pin                                    Limit     Cap   Slack
------------------------------------------------------------
_138_/QN                               92.16    2.32   89.84 (MET)
```

**Comment by oharboe** [comment]
Experiment:
```
diff --git a/flow/designs/asap7/mock-array/constraints.sdc b/flow/designs/asap7/mock-array/constraints.sdc
index 0824341c..4a094da4 100644
--- a/flow/designs/asap7/mock-array/constraints.sdc
+++ b/flow/designs/asap7/mock-array/constraints.sdc
@@ -23,5 +23,5 @@ set_input_delay  [expr $clk_period * $clk_in_pct] -clock ${clk_name}_vir $non_cl
 set_output_delay [expr $clk_period * $clk_o1_pct] -clock ${clk_name}_vir $non_reg_outputs
 set_output_delay [expr $clk_period * $clk_o2_pct] -clock ${clk_name}_vir [get_ports io_lsbs_*]
 
-set_max_transition 300 [current_design]
-set_max_transition 100 -clock_path [all_clocks]
+set_max_transition 100 [current_design]
+set_max_transition 50 -clock_path [all_clocks]
```

Changing set_max_transition, didn't do anything to the clock slew:

```
>>> report_check_types
Group                                  Slack
--------------------------------------------
clock                                   0.74
clock_vir                             230.59
clock                                 145.54
clock_vir                              -9.31

max slew

Pin                                    Limit    Slew   Slack
------------------------------------------------------------
ces_7_6/clock                         100.00  163.23  -63.23 (VIOLATED)

max capacitance

Pin                                    Limit     Cap   Slack
------------------------------------------------------------
hold93/Y                               92.16    3.20   88.96 (MET)
```

**Comment by oharboe** [comment]
Just an observation: there's a 70ps skew between the clocks to those two elements, which is much greater than the negative min slack.

**Comment by maliberty** [comment]
Probably something to do with slew

**Comment by mynnguyen** [comment]
Hold buffers inserted since skew is more than hold margin inside Elements.
Two work-around:
- Reduce clock uncertainty from 20ps to 10ps at mock-array level
- Add "set_input_delay 20 -min"  in Element constraint to have a little more hold margin

**Comment by mynnguyen** [comment]
Regarding constraints.sdc:
1, There may be a typo "set lsb_register_out [concat [get_ports io_lsbOuts_4]....."
  Should it be "io_lsbOuts_3" instead?

2, The "non_reg_outputs" are in-2-out paths, not reg-2-out
    - Remove that "set_output_delay"
    - Add "set_max_delay 50 -from [get_ports {io_lsbIns_*}] -to [get_ports {io_lsbOuts_*}]"

**Comment by oharboe** [comment]
> Regarding constraints.sdc: 1, There may be a typo "set lsb_register_out [concat [get_ports io_lsbOuts_4]....." Should it be "io_lsbOuts_3" instead?
> 
> 2, The "non_reg_outputs" are in-2-out paths, not reg-2-out - Remove that "set_output_delay" - Add "set_max_delay 50 -from [get_ports {io_lsbIns__}] -to [get_ports {io_lsbOuts__}]"

Fixed in upcoming commit.

@maliberty @tspyrou The GUI supports set_max_delay and it makes a lot of sense to me for the combinational paths. There were some concerns about using that feature. What trouble should I look for?


image

**Comment by oharboe** [comment]
What does this mean for mock-array?

If check_setup fails, then normally it lists the paths.

Mock-array:

```
>>> check_setup
Warning: There are 32 unconstrained endpoints.
0
```

For Element, I get the following, but no list of the ports:

```
>>> check_setup
Warning: There are 6 output ports missing set_output_delay.
0
```

**Comment by oharboe** [comment]
@mynnguyen Good to go for my part. I think I have addressed the gaffes I made.

The main goal of this PR is to get the constraints for Element in place, we can tinker with the constraints.sdc later.

**Pull request closed without merging**
