### PR TITLE
update ant command in flow

### PR DESCRIPTION
**Pull request by msaligane**
This PR should be merged after this [PR](https://github.com/The-OpenROAD-Project/OpenROAD/pull/751) is merged.

### CODE REVIEW

**Comment by msaligane** [comment]
@maliberty this small change to the command needs to be merged because check_antennas options were slightly modified. Just FYI.

**Comment by maliberty** [comment]
I'm not sure what is up but I see test failures like:
[2021-06-24T17:16:08.241Z] [ERROR STA-0402] check_antennas -report_violating_nets is not a known keyword or flag.
[2021-06-24T17:16:08.241Z] Error: global_route.tcl, 58 STA-0402

**Comment by msaligane** [comment]
This is supposed to be the new [command](https://github.com/The-OpenROAD-Project/OpenROAD/blob/b75e6d2409ddcd7a1213e713d18cfc6d3b1816bb/src/ant/test/sw130_random_simple.tcl#L6)

is the openroad version being tested/used now up-to-date (IE includes the ant readme update)?

**Comment by maliberty** [comment]
When I resolved the merge conflict I see this has already been fixed in master so there is no need for this PR.

**Pull request closed without merging**
