### PR TITLE
mock-array: renamed mock-array-big to mock-array

### PR DESCRIPTION
**Pull request by oharboe**
git is quite good at handling renames in merges and rebasing, so merging this should be fine.

### CODE REVIEW

**Comment by maliberty** [comment]
I imagine @louiic will have a hard time with merging this into his PR.

Jenkins files need updating.

**Comment by oharboe** [comment]
> I imagine @louiic will have a hard time with merging this into his PR.
> 
> Jenkins files need updating.

@louiic Would you like me to do the merge and create a fresh PR?

I see what you are going with this PR, I can complete it as a co-author and rebase on master...

**Comment by maliberty** [comment]
Once https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/1157 goes through you'll need to update the Makefile comment.

**Comment by oharboe** [comment]
> Once #1157 goes through you'll need to update the Makefile comment.

Fixed.

**Comment by oharboe** [comment]
@maliberty @louiic  There's never going to be a perfect time to do a rename. A bit of foo is required... I would merge with master just before the rename, them merge with master after the rename. At that point, the first review is just a garden variety merge conflict no worse than the current one and afterwards the merge is simple: just to catch up with the rename.

**Comment by oharboe** [comment]
@maliberty Passes tests on server... Ready to go for my part.

**Review by maliberty — APPROVED** [review]

**Pull request merged**
