### PR TITLE
asap7: add decap cells as FILL_CELLS

### PR DESCRIPTION
**Pull request by maliberty**
Per Lawrence Clark this is the intention for asap7

Signed-off-by: Matt Liberty <mliberty@eng.ucsd.edu>

### CODE REVIEW

**Comment by maliberty** [comment]
@oharboe hopefully this will help/fix #732

**Review by vvbandeira — APPROVED** [review]

**Comment by rovinski** [comment]
I question this - decap cells will be inserted everywhere because they are the largest fill cell. Over-insertion of decap cells is usually bad for leakage power.

**Comment by maliberty** [comment]
@rovinski  Since asap7 isn't manufacturable I'm not sure it matters.  Real PDKs have a full range of fill cells.  OL does the same in sky130 in production but maybe leakage matters less there?

**Comment by maliberty** [comment]
From Prof. Clark
```
On the final note, don't fill with fill cells. Use DECAP! That is what it is for. Fill is for the tiny spots left over that decap does not fit.
```

**Comment by rovinski** [comment]
This is unfortunately exposing some shortcomings of ASAP7. Assuming DECAP cells actually have caps in them and aren't just poorly named, they shouldn't be used everywhere. These caps are leaky and contribute significantly to leakage power. Unfortunately, we can't even model this because there aren't .lib views of DECAP cells. IIRC commercial PDKs normally do have lib views just to model the leakage power.

So I guess we just have to accept two wrongs making a right.

**Comment by oharboe** [comment]
> This is unfortunately exposing some shortcomings of ASAP7. Assuming DECAP cells actually have caps in them and aren't just poorly named, they shouldn't be used everywhere. These caps are leaky and contribute significantly to leakage power. Unfortunately, we can't even model this because there aren't .lib views of DECAP cells. IIRC commercial PDKs normally do have lib views just to model the leakage power.
> 
> So I guess we just have to accept two wrongs making a right.

Maybe create a list in the documentation of known "approximations" made by ASAP7 and move on?

**Pull request merged**
