### PR TITLE
sky130hd/microwatt: improving TNS_END_PERCENT needs special attention

### PR DESCRIPTION
**Pull request by oharboe**

### CODE REVIEW

**Comment by maliberty** [comment]
Please explain
> Improving TNS_END_PERCENT will introduce various problems that have to be investigated

**Comment by oharboe** [comment]
> Please explain
> 
> > Improving TNS_END_PERCENT will introduce various problems that have to be investigated

I suspect the failures here are due to the changed default: https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/2142

**Comment by maliberty** [comment]
> I suspect the failures here are due to the changed default: https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/2142

These changes should be part of that PR then.  You can't tell from this PR what it is related to nor does the CI here prove it will help.

**Comment by oharboe** [comment]
> > I suspect the failures here are due to the changed default: #2142
> 
> These changes should be part of that PR then. You can't tell from this PR what it is related to nor does the CI here prove it will help.

It's not my PR...

**Comment by eder-matheus** [comment]
Microwatt has only the antenna violations metrics failing by a small amount in PR 2142. This PR here doesn't seem necessary.

**Pull request closed without merging**
