### PR TITLE
designs/asap7/mock-big-array: harder for detailed routing

### PR DESCRIPTION
**Pull request by oharboe**
Make this design a bit harder to route to investigate some problems.

To reproduce first generate the macro, then the top level design with where detailed routing is ended after 4 iterations

```
make DESIGN_CONFIG=designs/asap7/mock-array-big/Element/config.mk generate_abstract
make DESIGN_CONFIG=designs/asap7/mock-array-big/config.mk DETAILED_ROUTE_ARGS="-bottom_routing_layer M2 -top_routing_layer M7 -save_guide_updates -verbose 1 -droute_end_iter 4"
```

This shows that the DRC errors after 4 iterations is concerning the jump from M4 to M2 and back to M4, as discussed here: https://github.com/The-OpenROAD-Project/OpenROAD/discussions/2870

image

### CODE REVIEW

**Comment by oharboe** [comment]
@maliberty FYI, this pull request should be useful in reproducing some problems we have been seeing.

Currently it fails earlier than on the problems I was trying to reproduce, but once these earlier problems are solved, I am hopeful we can observe other interesting problems that we run into as we try to scale up our proprietary design.


```
./or make DESIGN_CONFIG=designs/asap7/mock-array-big/config.mk
[deleted]
[NesterovSolve] Iter: 2680 overflow: 0.568277 HPWL: 50688675
[NesterovSolve] Iter: 2690 overflow: 0.575824 HPWL: 50687964
[NesterovSolve] Iter: 2700 overflow: 0.592507 HPWL: 50688683
[NesterovSolve] Iter: 2710 overflow: 0.568713 HPWL: 50690016
[NesterovSolve] Iter: 2720 overflow: 0.566089 HPWL: 50689794
[ERROR GPL-0305] RePlAce diverged at newStepLength.
Error: global_place_skip_io.tcl, 30 GPL-0305
Elapsed time: 0:24.03[h:]min:sec. CPU time: user 23.94 sys 0.09 (99%). Peak memory: 223660KB.
make: *** [results/asap7/mock-array-big/base/3_1_place_gp_skip_io.odb] Error 1
```

**Comment by maliberty** [comment]
Is it intentional that you have multiple top-level outputs connections on a single net?  For example:
```
  output       io_lsbs_0,
  output [7:0] io_outsHorizontal_0_0,
...
  assign io_outsHorizontal_0_0 = ces_0_0_io_outs_0; // @[MockArray.scala 50:89]
  assign io_lsbs_0 = ces_0_0_io_outs_0[0]; // @[MockArray.scala 39:44]
```
I don't think this is the problem but noticed it while looking.

**Comment by maliberty** [comment]
Yosys inserts this buffer as a result
```
  BUFx2_ASAP7_75t_R _00_ (
    .A(io_outsHorizontal_0_0[0]),
    .Y(io_lsbs_0)
  );
```

**Comment by oharboe** [comment]
> Is it intentional that you have multiple top-level outputs connections on a single net? For example:
> 
> ```
>   output       io_lsbs_0,
>   output [7:0] io_outsHorizontal_0_0,
> ...
>   assign io_outsHorizontal_0_0 = ces_0_0_io_outs_0; // @[MockArray.scala 50:89]
>   assign io_lsbs_0 = ces_0_0_io_outs_0[0]; // @[MockArray.scala 39:44]
> ```
> 
> I don't think this is the problem but noticed it while looking.

Yes, that is intentional. I was trying to provoke a  problem by throwing a curveball to OpenROAD. This is a mock array with some structure and whatever gets the job done to reproduce problems.

**Comment by oharboe** [comment]
Though.... sometimes removing things is needed to reproduce problems.... I dont know how to get to the bottom of this except by peeling away one bug and problem at the time....

**Comment by oharboe** [comment]
@maliberty I tried with the latest fix and I can now run the instructions above, but I don't think this test case shows anything interesting at this point as we already have a handle on https://github.com/The-OpenROAD-Project/OpenROAD/discussions/2870#discussioncomment-4904710

**Comment by oharboe** [comment]
Not part of any investigation at this point.

**Pull request closed without merging**
