### PR TITLE
update metrics for grt macro handling update

### PR DESCRIPTION
**Pull request by eder-matheus**
Metrics for PR https://github.com/The-OpenROAD-Project/OpenROAD/pull/5833

sky130hd/microwatt
| Metric                                        | Old      | New      | Type     |
| ------                                        | ---      | ---      | ----     |
| synth__design__instance__area__stdcell        | 736136.77 | 732007.18 | Tighten  |
| placeopt__design__instance__area              |  5687969 |  5674410 | Tighten  |
| placeopt__design__instance__count__stdcell    |   192168 |   191898 | Tighten  |
| cts__design__instance__count__setup_buffer    |    16710 |    16687 | Tighten  |
| cts__design__instance__count__hold_buffer     |    16710 |    16687 | Tighten  |
| globalroute__antenna_diodes_count             |    11592 |     5828 | Tighten  |
| detailedroute__route__wirelength              | 10518064 |  9705104 | Tighten  |
| detailedroute__antenna_diodes_count           |     1141 |      760 | Tighten  |
| finish__timing__setup__ws                     |    -2.91 |    -3.75 | Failing  |
| finish__design__instance__area                |  5812434 |  5782867 | Tighten  |
| finish__timing__drv__setup_violation_count    |     8355 |     8343 | Tighten  |

asap7/swerv_wrapper
| Metric                                        | Old      | New      | Type     |
| ------                                        | ---      | ---      | ----     |
| detailedroute__route__drc_errors              |        2 |        0 | Tighten  |
| finish__timing__drv__hold_violation_count     |     1111 |     1034 | Tighten  |

### CODE REVIEW

**Review by maliberty — APPROVED** [review]

**Comment by maliberty** [comment]
Its nice to put the output of 'update_ok' in the description.

**Comment by eder-matheus** [comment]
> Its nice to put the output of 'update_ok' in the description.

I added it now. I had the updates saved in a txt, but I forgot to add to the PR.

**Comment by rovinski** [comment]
Sorry, kind of a tangent here, but isn't it odd that the hold buffer counts and setup buffer counts are identical in the table? Is there a bug in the script that generates it?

**Comment by maliberty** [comment]
@rovinski good eye!  I believe what's happening is that if we do no hold repair (0 violations) then we get the setup value instead.

**Pull request merged**
