### PR TITLE
Updating Yosys to same version as OpenROAD.

### PR DESCRIPTION
**Pull request by mithro**

### CODE REVIEW

**Comment by mithro** [comment]
Reopening to get CI output to compare to https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/1468/files

**Comment by mithro** [comment]
https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/actions/runs/6330777808/job/17193938302?pr=1510
```
Error: cts.tcl, 110 couldn't execute "eqy": no such file or directory
Command exited with non-zero status 1
Elapsed time: 0:07.36[h:]min:sec. CPU time: user 7.26 sys 0.04 (99%). Peak memory: 109344KB.
make[1]: *** [Makefile:669: do-4_1_cts] Error 1
make: *** [Makefile:669: results/nangate45/gcd/base/4_1_cts.odb] Error 2
make: Leaving directory '/OpenROAD-flow-scripts/flow'
```

**Comment by mithro** [comment]
https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/actions/runs/6330777808/job/17193938496?pr=1510#step:6:1
```
Run cmd="yosys -help; openroad -help; make -C flow;"
/bin/bash: line 1: yosys: command not found
/bin/bash: line 1: openroad: command not found
make: Entering directory '/OpenROAD-flow-scripts/flow'
[INFO][FLOW] Using platform directory /OpenROAD-flow-scripts/flow/platforms/nangate45
```

**Comment by vvbandeira** [comment]
@mithro I will look into these errors

**Comment by tspyrou** [comment]
@vvbandeira and @mithro it looks like the new version is significantly worse in several cases.

**Comment by mithro** [comment]
@tspyrou - There seems to be a bunch of complexity here, in many cases there are pretty large swings here...

**Comment by tspyrou** [comment]
This looks like a failure versus  a metric degradation. https://jenkins.openroad.tools/blue/organizations/jenkins/OpenROAD-flow-scripts-Public%2Fpublic_tests_all-pr/detail/PR-1510-head/3/pipeline/1028

**Pull request closed without merging**
