### PR TITLE
setup: add ORFS dependencies to setup

### PR DESCRIPTION
**Pull request by oharboe**
@vijayank88 Is this what was missing?

### CODE REVIEW

**Comment by vijayank88** [comment]
yes @oharboe.

But again question is running both `DependencyInstaller.sh` will skip if package already installed or not?
```
_installORDependencies() {
    ./tools/OpenROAD/etc/DependencyInstaller.sh ${OR_INSTALLER_ARGS}
}
```
Above line again called inside `etc/DependecyInstaller.sh`.

**Comment by oharboe** [comment]
> yes @oharboe.
> 
> But again question is running both `DependencyInstaller.sh` will skip if package already installed or not?
> 
> ```
> _installORDependencies() {
>     ./tools/OpenROAD/etc/DependencyInstaller.sh ${OR_INSTALLER_ARGS}
> }
> ```
> 
> Above line again called inside `etc/DependecyInstaller.sh`.

Some work is needed on ORFS/etc/DependecyInstaller.sh, it doesn't follow the semantics laid out by the command line arguments in tools/OpenROAD/etc/DependencyInstaller.sh.

If you run sudo ./setup.sh it fails, because it is trying to install things using sudo access when "-common" is specified.

**Comment by vijayank88** [comment]
I think @habibayassin is the right person to review this, who split standalone `DependecyInstaller.sh` script for ORFS.

**Comment by oharboe** [comment]
> I think @habibayassin is the right person to review this, who split standalone `DependecyInstaller.sh` script for ORFS.

Once #950  is fixed, I will try this PR again.

**Review by vvbandeira — APPROVED** [review]

**Comment by oharboe** [comment]
@maliberty this PR is ready to merge, works after #959 was merged.

**Pull request merged**
