### PR TITLE
Make fix symlink mock abstract dates

### PR DESCRIPTION
**Pull request by oharboe**
Log from new test run where CTS takes no time. No time in CTS, resize or route:

A couple of macros build with `make skip_resize skip_cts skip_route generate_abstract` and extracting times:

```
1_1_yosys                        616
3_3_place_gp                      57
3_3_place_gp                      51
1_1_yosys                         39
3_3_place_gp                      32
1_1_yosys                         26
3_5_opendp                        24
1_1_yosys                         22
6_report                          12
3_3_place_gp                      12
6_report                           8
3_5_opendp                         8
3_5_opendp                         8
6_report                           7
3_1_place_gp_skip_io               7
3_5_opendp                         6
6_report                           5
3_1_place_gp_skip_io               5
3_1_place_gp_skip_io               4
2_1_floorplan                      4
1_1_yosys                          4
3_2_place_iop                      3
2_6_pdn                            3
2_6_pdn                            3
2_1_floorplan                      3
6_1_merge                          2
6_1_merge                          2
3_2_place_iop                      2
3_1_place_gp_skip_io               2
2_2_floorplan_io                   2
2_1_floorplan                      2
2_1_floorplan                      2
6_1_merge                          1
6_1_merge                          1
3_2_place_iop                      1
3_2_place_iop                      1
2_6_pdn                            1
2_6_pdn                            1
2_5_tapcell                        1
2_5_tapcell                        1
2_5_tapcell                        1
2_5_tapcell                        1
2_4_mplace                         1
2_4_mplace                         1
2_4_mplace                         1
2_4_mplace                         1
2_3_tdms_place                     1
2_3_tdms_place                     1
2_2_floorplan_io                   1
2_2_floorplan_io                   1
2_2_floorplan_io                   1

```

### CODE REVIEW

**Comment by maliberty** [comment]
Why is is necessary to touch the files?

**Comment by oharboe** [comment]
> Why is is necessary to touch the files?

Otherwise e.g. skip_cts does not work, skip_route will build CTS. I must admit I dont understand the exact details of make and file dates, but it works....

**Comment by oharboe** [comment]
@maliberty The failures are not related, it is the usual suspects....

**Comment by oharboe** [comment]
I have to go down into the symlink, touch and make date rabbithole..

**Comment by oharboe** [comment]
Some experiment to establish what is going on with symlink, make and dates.

Makefiles use "Modify" date, removed uninteresting output below for brevity.

Experiment, "foo" is a real file, "bar" is a symlink, start with no files,
`ln -sf foo bar` sets "modify date" as would `cp`:

```
$ touch foo
$ stat foo
Modify: 2023-05-31 07:44:45.096066788 +0200
$ ln -sf foo bar
$ stat bar
Modify: 2023-05-31 07:44:57.323982287 +0200
```

Experiment, update `foo`, `foo` is newer than `bar`, same as `cp`

```
$ touch foo
$ stat foo
Modify: 2023-05-31 07:45:23.607821311 +0200
$ stat bar
Modify: 2023-05-31 07:44:57.323982287 +0200
```

Experiment: symlink `bar` exists, re-execute `ln -sf`, "modify date" of `bar`
is updated, just like `cp`

```
$ ln -sf foo bar
$ stat bar
Modify: 2023-05-31 07:45:43.891742599 +0200
```

Touching `bar` dereferences `bar` and and updates date
of `foo`. Use `touch -h` to update "modify date" of
symlink only.

```
$ stat foo
Modify: 2023-05-31 07:57:02.588274364 +0200
$ stat bar
Modify: 2023-05-31 07:57:02.588274364 +0200
$ touch -h bar
$ stat foo
Modify: 2023-05-31 07:57:02.588274364 +0200
$ stat bar
Modify: 2023-05-31 07:57:19.576174426 +0200
$ touch bar
$ stat foo
Modify: 2023-05-31 07:57:19.588174354 +0200
$ stat bar
Modify: 2023-05-31 07:57:19.576174426 +0200
```

**Comment by oharboe** [comment]
Some experiments with Makefile and symlinks:

```
bar2: bar
	ln -sf bar bar2

bar: foo
	ln -sf foo bar

.PHONY: clean
clean:
	rm -f foo bar bar2
```

Experiment:

```
$ make clean
rm -f foo bar bar2
$ touch foo
$ make
ln -sf foo bar
ln -sf bar bar2
$ touch foo
$ make
make: 'bar2' is up to date.
```

Here "ln -sf" is not behaving like "cp"

**Comment by oharboe** [comment]
```
bar2: bar
	cp bar bar2

bar: foo
	cp foo bar

.PHONY: clean
clean:
	rm -f foo bar bar2
```

```
$ make clean
rm -f foo bar bar2
$ touch foo
$ make
cp foo bar
cp bar bar2
$ touch foo
$ make
cp foo bar
cp bar bar2
$ make
make: 'bar2' is up to date.
```

**Comment by oharboe** [comment]
More experiments...

```
bar2: bar
	ln -sf bar bar2
	stat foo
	stat bar
	stat bar2

bar: foo
	ln -sf foo bar

.PHONY: clean
clean:
	rm -f foo bar bar2
```

Some more experiments:

```
$ make clean
rm -f foo bar bar2
$ touch foo
$ make
ln -sf foo bar
ln -sf bar bar2
stat foo
  File: foo
Access: 2023-05-31 08:21:30.455175039 +0200
Modify: 2023-05-31 08:21:30.455175039 +0200
Change: 2023-05-31 08:21:30.455175039 +0200
 Birth: 2023-05-31 08:21:30.455175039 +0200
stat bar
  File: bar -> foo
Access: 2023-05-31 08:21:31.187171343 +0200
Modify: 2023-05-31 08:21:31.183171363 +0200
Change: 2023-05-31 08:21:31.183171363 +0200
 Birth: 2023-05-31 08:21:31.183171363 +0200
stat bar2
  File: bar2 -> bar
Access: 2023-05-31 08:21:31.187171343 +0200
Modify: 2023-05-31 08:21:31.187171343 +0200
Change: 2023-05-31 08:21:31.187171343 +0200
 Birth: 2023-05-31 08:21:31.187171343 +0200
$ touch foo
$ make
make: 'bar2' is up to date.
```



```
$ stat foo
  File: foo
Access: 2023-05-31 08:23:11.086654748 +0200
Modify: 2023-05-31 08:23:11.086654748 +0200
Change: 2023-05-31 08:23:11.086654748 +0200
 Birth: 2023-05-31 08:21:30.455175039 +0200
$ stat bar
  File: bar -> foo
Access: 2023-05-31 08:21:31.187171343 +0200
Modify: 2023-05-31 08:21:31.183171363 +0200
Change: 2023-05-31 08:21:31.183171363 +0200
 Birth: 2023-05-31 08:21:31.183171363 +0200
$ stat bar2
  File: bar2 -> bar
Access: 2023-05-31 08:21:31.191171322 +0200
Modify: 2023-05-31 08:21:31.187171343 +0200
Change: 2023-05-31 08:21:31.187171343 +0200
 Birth: 2023-05-31 08:21:31.187171343 +0200
$ make bar
make: 'bar' is up to date.
```

This last one has me stumped. Here clearly "foo" is newer than "bar" by all accounts, yet "bar" is up to date.

It would appear that when "foo" is a symlink pointing to "bar", then make always treats the comparison as "up to date".

**Pull request closed without merging**
