### PR TITLE
Use ray queue to schedule jobs

### PR DESCRIPTION
**Pull request by vvbandeira**
Signed-off-by: Vitor Bandeira <vitor.vbandeira@gmail.com>

### CODE REVIEW

**Comment by sewkim** [comment]
Hi Vitor, this naming discrepancy is fine?
        '--openroad-threads', and     make_command += f' NPROC={args.openroad_threads} SHELL=bash'
First one includes '-' and second includes '_'.

**Comment by vvbandeira** [comment]
> Hi Vitor, this naming discrepancy is fine? '--openroad-threads', and make_command += f' NPROC={args.openroad_threads} SHELL=bash' First one includes '-' and second includes '_'.

We can change to be `--openroad_threads` for consistency, but this will not lead to an error.
The `argparse` python lib converts `-` to `_`.

**Comment by sewkim** [comment]
I see. Thank you for your comment. BTW, I can see some parsing error. Could you check below screenshot? _PINS_DISTANCE has list itself.
Input json.{
    "CTS_CLUSTER_SIZE": {
        "type": "int",
        "minmax": [
            50,
            60
        ],
        "step": 1
    },
    "_PINS_DISTANCE": {
        "type": "int",
        "minmax": [
            1,
            3
        ],
        "step": 1
    }
}


image

**Comment by vvbandeira** [comment]
@sewkim this is unrelated to the sweep change.
The parser is probably wrong and would affect both sweep and tune -- we should address in another PR.
https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/blob/759431a718a88aaedf348638dae5d598271c0f5e/flow/util/distributed.py#L301-L302

**Review by sewkim — APPROVED** [review]

**Comment by sewkim** [comment]
I see. Thank you.

**Pull request merged**
