### PR TITLE
asap7-aes-block: update metrics for mpl2-snapper / point to lastest OR with changes

### PR DESCRIPTION
**Pull request by AcKoucher**
| Metric                                        | Old      | New      | Type     |
| ------                                        | ---      | ---      | ----     |
| finish__timing__setup__ws                     |  -285.81 |  -329.84 | Failing  |
| finish__timing__drv__hold_violation_count     |      238 |      424 | Failing  |

### CODE REVIEW

**Comment by maliberty** [comment]
Is the OR submodule update to a commit on master?  It shouldn't be pointed to a branch.

**Comment by AcKoucher** [comment]
I see. My intentions were to sync master with my changes in [#5160](https://github.com/The-OpenROAD-Project/OpenROAD/pull/5160) so CI doesn't break. Should I wait for it to be merged so I can point correctly or should this PR be strictly for updating the metrics?

**Comment by maliberty** [comment]
> I see. My intentions were to sync master with my changes in [#5160](https://github.com/The-OpenROAD-Project/OpenROAD/pull/5160) so CI doesn't break. Should I wait for it to be merged so I can point correctly or should this PR be strictly for updating the metrics?

You should either wait or split updating metrics from updating OR.

**Comment by maliberty** [comment]
I merged the other so please update this PR

**Comment by AcKoucher** [comment]
I updated the changes here so that we only update the metrics.

**Review by maliberty — APPROVED** [review]

**Pull request merged**
