### PR TITLE
mock-array-big: More detailed Element timing constraints

### PR DESCRIPTION
**Pull request by yupferris**
Addresses feedback in comments on https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/commit/725b5f61c690c71a7e577152c3ac1e873a16f68d.

### CODE REVIEW

**Comment by yupferris** [comment]
If possible, I'd like @tspyrou to review this (I cannot request PR reviews in this repo).

**Comment by yupferris** [comment]
jenkins failures appear to be for a different design.

**Comment by vijayank88** [comment]
Yes. Need metrics update
```
[ERROR] finish__timing__drv__max_slew_limit fail test: -0.893999 >= -0.2
```
PR  #1116 needs to be merged.

**Comment by yupferris** [comment]
> Need metrics update

Thanks for the reminder (again) :) . Done now.

**Comment by vijayank88** [comment]
@yupferris 
Metrics update required for `bp_multi_top`. Check reference PR I given. Maybe Matt will handle this.

**Comment by yupferris** [comment]
Ah, that's what you mean, that the _other_ design needed a metrics update. Yeah I think the other PR should be merged before this one. Anyways, can't hurt to have them updated for `mock-array-big` as well :)

**Review by tspyrou — APPROVED** [review]
This looks exactly like what I had in mind.

**Comment by tspyrou** [comment]
@yupferris if you merge in the latest code the failing test  should pass.

**Comment by yupferris** [comment]
> @yupferris if you merge in the latest code the failing test should pass.

Indeed, all green. Cheers!

**Pull request merged**
