### PR TITLE
Mock array flatten

### PR DESCRIPTION
**Pull request by oharboe**
```
make BLOCKS= DESIGN_CONFIG=designs/asap7/mock-array/config.mk cts
```

```
make BLOCKS= DESIGN_CONFIG=designs/asap7/mock-array/config.mk gui_cts
```

image

```
$ make BLOCKS= DESIGN_CONFIG=designs/asap7/mock-array/config.mk elapsed
[INFO-FLOW] ASU ASAP7 - version 2
Default PVT selection: BC
./logs/asap7/mock-array/base
Log                       Elapsed seconds
1_1_yosys                          8
2_1_floorplan                      3
2_2_floorplan_io                   1
2_3_floorplan_tdms                 1
2_4_floorplan_macro                1
2_5_floorplan_tapcell              1
2_6_floorplan_pdn                  4
3_1_place_gp_skip_io              15
3_2_place_iop                      2
3_3_place_gp                      36
3_4_place_resized                 10
3_5_place_dp                      14
4_1_cts                           18
5_1_grt                           33
5_2_fillcell                       3
No elapsed time found in logs/asap7/mock-array/base/5_3_route.tmp.log
Total                            150
```

### CODE REVIEW

**Review by maliberty — APPROVED** [review]

**Comment by tspyrou** [comment]
I see this error in a fresh build.
[INFO][FLOW] Invoked hierarchical flow.
Block Element needs to be hardened.
(/usr/bin/time -f 'Elapsed time: %E[h:]min:sec. CPU time: user %U sys %S (%P). Peak memory: %MKB.' /home/tspyrou/latency_flat/OpenROAD-flow-scripts/tools/install/OpenROAD/bin/openroad -exit -no_init  ./scripts/floorplan.tcl -metrics ./logs/asap7/mock-array/base/2_1_floorplan.json) 2>&1 | tee ./logs/asap7/mock-array/base/2_1_floorplan.log
OpenROAD f9a24b703181b4ecc231cfee28be9958d9b438c9
This program is licensed under the BSD-3 license. See the LICENSE file for details.
Components of this program may be licensed under more restrictive licenses which must be honored.
Error: read_liberty.tcl, 25 cannot read file ./results/asap7/mock-array_Element/base/Element.lib.
Command exited with non-zero status 1
Elapsed time: 0:00.84[h:]min:sec. CPU time: user 0.80 sys 0.04 (100%). Peak memory: 181440KB.
make[1]: *** [Makefile:503: do-2_1_floorplan] Error 1
make[1]: Leaving directory '/home/tspyrou/latency_flat/OpenROAD-flow-scripts/flow'
make: *** [Makefile:503: results/asap7/mock-array/base/2_1_floorplan.odb] Error 2

**Comment by oharboe** [comment]
@tspyrou Run `make nuke` or at least clean before the new cmd

**Comment by tspyrou** [comment]
Confirmed pilot error, thanks.

**Comment by tspyrou** [comment]
Same error after :
2073  make BLOCKS= DESIGN_CONFIG=designs/asap7/mock-array/config.mk nuke
 2074  make BLOCKS= DESIGN_CONFIG=designs/asap7/mock-array/config.mk

tspyrou@TomXPS:~/latency_flat/OpenROAD-flow-scripts/flow$ git remote -v
origin  https://github.com/Pinata-Consulting/OpenROAD-flow-scripts.git (fetch)
origin  https://github.com/Pinata-Consulting/OpenROAD-flow-scripts.git (push)

**Comment by maliberty** [comment]
@tspyrou I just tried this PR and it works for me.  I'm guessing you are not on this branch mock-array-flatten.  What does 'git status' show?

**Comment by tspyrou** [comment]
Pilot error confirmed. Its running for me now.

**Comment by tspyrou** [comment]
<pre>
This is what I see as the skew and critical path (setup/hold) between registers in the elements.
Clock clock
Latency      CRPR       Skew
ces_6_0.REG_1[27]$_DFF_P_/CLK ^
 419.44
ces_7_0.REG_2[27]$_DFF_P_/CLK ^
 323.03      0.00      96.41

Clock clock_vir
No launch/capture paths found.

openroad> report_checks -from [all_registers] -to [all_registers]
Startpoint: ces_6_0.REG_1[9]$_DFF_P_
            (rising edge-triggered flip-flop clocked by clock)
Endpoint: ces_7_0.REG_2[9]$_DFF_P_
          (rising edge-triggered flip-flop clocked by clock)
Path Group: clock
Path Type: max

  Delay    Time   Description
---------------------------------------------------------
   0.00    0.00   clock clock (rise edge)
 400.82  400.82   clock network delay (propagated)
   0.00  400.82 ^ ces_6_0.REG_1[9]$_DFF_P_/CLK (DFFHQNx2_ASAP7_75t_R)
  61.90  462.72 v ces_6_0.REG_1[9]$_DFF_P_/QN (DFFHQNx2_ASAP7_75t_R)
  47.67  510.38 v wire5045/Y (BUFx12f_ASAP7_75t_R)
  59.29  569.67 ^ _19468_/Y (INVx1_ASAP7_75t_R)
   0.78  570.45 ^ ces_7_0.REG_2[9]$_DFF_P_/D (DFFHQNx2_ASAP7_75t_R)
         570.45   data arrival time

 250.00  250.00   clock clock (rise edge)
 322.84  572.84   clock network delay (propagated)
 -10.00  562.84   clock uncertainty
   0.00  562.84   clock reconvergence pessimism
         562.84 ^ ces_7_0.REG_2[9]$_DFF_P_/CLK (DFFHQNx2_ASAP7_75t_R)
 -11.03  551.81   library setup time
         551.81   data required time
---------------------------------------------------------
         551.81   data required time
        -570.45   data arrival time
---------------------------------------------------------
         -18.64   slack (VIOLATED)


openroad> report_checks -from [all_registers] -to [all_registers] -path_delay min
Startpoint: ces_7_2.REG_2[14]$_DFF_P_
            (rising edge-triggered flip-flop clocked by clock)
Endpoint: io_outs_up_3[14]$_DFF_P_
          (rising edge-triggered flip-flop clocked by clock)
Path Group: clock
Path Type: min

  Delay    Time   Description
---------------------------------------------------------
   0.00    0.00   clock clock (rise edge)
 331.20  331.20   clock network delay (propagated)
   0.00  331.20 ^ ces_7_2.REG_2[14]$_DFF_P_/CLK (DFFHQNx2_ASAP7_75t_R)
  46.60  377.80 ^ ces_7_2.REG_2[14]$_DFF_P_/QN (DFFHQNx2_ASAP7_75t_R)
  11.67  389.47 v _22220_/Y (INVx1_ASAP7_75t_R)
   0.22  389.69 v io_outs_up_3[14]$_DFF_P_/D (DFFHQNx2_ASAP7_75t_R)
         389.69   data arrival time

   0.00    0.00   clock clock (rise edge)
 370.37  370.37   clock network delay (propagated)
  10.00  380.37   clock uncertainty
   0.00  380.37   clock reconvergence pessimism
         380.37 ^ io_outs_up_3[14]$_DFF_P_/CLK (DFFHQNx2_ASAP7_75t_R)
   9.27  389.64   library hold time
         389.64   data required time
---------------------------------------------------------
         389.64   data required time
        -389.69   data arrival time
---------------------------------------------------------
           0.05   slack (MET)

</pre>

**Comment by tspyrou** [comment]
The clock skew of 100ps seems high.
image

**Comment by tspyrou** [comment]
<pre>
The next register path in line has nearly perfect skew and plenty of slack.
openroad> report_checks -from ces_7_0.REG_2[9]\$_DFF_P_ -to [all_registers] -path_delay max
Startpoint: ces_7_0.REG_2[9]$_DFF_P_
            (rising edge-triggered flip-flop clocked by clock)
Endpoint: io_outs_up_1[9]$_DFF_P_
          (rising edge-triggered flip-flop clocked by clock)
Path Group: clock
Path Type: max

  Delay    Time   Description
---------------------------------------------------------
   0.00    0.00   clock clock (rise edge)
 322.84  322.84   clock network delay (propagated)
   0.00  322.84 ^ ces_7_0.REG_2[9]$_DFF_P_/CLK (DFFHQNx2_ASAP7_75t_R)
  42.86  365.70 v ces_7_0.REG_2[9]$_DFF_P_/QN (DFFHQNx2_ASAP7_75t_R)
  13.11  378.81 ^ _21651_/Y (INVx2_ASAP7_75t_R)
   2.07  380.88 ^ io_outs_up_1[9]$_DFF_P_/D (DFFHQNx2_ASAP7_75t_R)
         380.88   data arrival time

 250.00  250.00   clock clock (rise edge)
 326.26  576.26   clock network delay (propagated)
 -10.00  566.26   clock uncertainty
   0.00  566.26   clock reconvergence pessimism
         566.26 ^ io_outs_up_1[9]$_DFF_P_/CLK (DFFHQNx2_ASAP7_75t_R)
  -8.77  557.49   library setup time
         557.49   data required time
---------------------------------------------------------
         557.49   data required time
        -380.88   data arrival time
---------------------------------------------------------
         176.61   slack (MET)


openroad> report_checks -from ces_7_0.REG_2[9]\$_DFF_P_ -to [all_registers] -path_delay min
Startpoint: ces_7_0.REG_2[9]$_DFF_P_
            (rising edge-triggered flip-flop clocked by clock)
Endpoint: io_outs_up_1[9]$_DFF_P_
          (rising edge-triggered flip-flop clocked by clock)
Path Group: clock
Path Type: min

  Delay    Time   Description
---------------------------------------------------------
   0.00    0.00   clock clock (rise edge)
 322.84  322.84   clock network delay (propagated)
   0.00  322.84 ^ ces_7_0.REG_2[9]$_DFF_P_/CLK (DFFHQNx2_ASAP7_75t_R)
  42.26  365.10 ^ ces_7_0.REG_2[9]$_DFF_P_/QN (DFFHQNx2_ASAP7_75t_R)
  11.27  376.37 v _21651_/Y (INVx2_ASAP7_75t_R)
   2.05  378.42 v io_outs_up_1[9]$_DFF_P_/D (DFFHQNx2_ASAP7_75t_R)
         378.42   data arrival time

   0.00    0.00   clock clock (rise edge)
 326.26  326.26   clock network delay (propagated)
  10.00  336.26   clock uncertainty
   0.00  336.26   clock reconvergence pessimism
         336.26 ^ io_outs_up_1[9]$_DFF_P_/CLK (DFFHQNx2_ASAP7_75t_R)
   8.43  344.69   library hold time
         344.69   data required time
---------------------------------------------------------
         344.69   data required time
        -378.42   data arrival time
---------------------------------------------------------
          33.73   slack (MET)
</pre>

**Comment by tspyrou** [comment]
This is the worst skew 257.35ps (regardless of whether or not the registers have a path between them).

<pre>
openroad> report_checks -unconstrained -from [get_ports clock] -to [all_registers -clock_pins] -path_delay max
Startpoint: clock (clock source 'clock')
Endpoint: ces_0_0.REG_1[45]$_DFF_P_/CLK (internal pin)
Path Group: unconstrained
Path Type: max

  Delay    Time   Description
---------------------------------------------------------
   0.00  125.00 v clock (in)
  51.93  176.93 v wire1/Y (BUFx16f_ASAP7_75t_R)
  69.02  245.96 v clkbuf_0_clock/Y (BUFx24_ASAP7_75t_R)
  30.37  276.32 v clkbuf_1_0_0_clock/Y (BUFx24_ASAP7_75t_R)
  39.51  315.84 v clkbuf_2_0_0_clock/Y (BUFx24_ASAP7_75t_R)
  34.31  350.14 v clkbuf_2_0_1_clock/Y (BUFx24_ASAP7_75t_R)
  33.95  384.09 v clkbuf_4_2_0_clock/Y (BUFx24_ASAP7_75t_R)
  38.08  422.17 v clkbuf_5_5_0_clock/Y (BUFx24_ASAP7_75t_R)
  31.69  453.86 v clkbuf_7_21__f_clock/Y (BUFx24_ASAP7_75t_R)
  28.04  481.90 v max_length2/Y (BUFx16f_ASAP7_75t_R)
  89.86  571.75 v clkbuf_leaf_8_clock/Y (BUFx24_ASAP7_75t_R)
   1.45  573.21 v ces_0_0.REG_1[45]$_DFF_P_/CLK (DFFHQNx2_ASAP7_75t_R)
         573.21   data arrival time
---------------------------------------------------------
(Path is unconstrained)


openroad> report_checks -unconstrained -from [get_ports clock] -to [all_registers -clock_pins] -path_delay min
Startpoint: clock (clock source 'clock')
Endpoint: ces_4_0.REG_2[36]$_DFF_P_/CLK (internal pin)
Path Group: unconstrained
Path Type: min

  Delay    Time   Description
---------------------------------------------------------
   0.00    0.00 ^ clock (in)
  48.32   48.32 ^ wire1/Y (BUFx16f_ASAP7_75t_R)
  64.32  112.64 ^ clkbuf_0_clock/Y (BUFx24_ASAP7_75t_R)
  32.72  145.36 ^ clkbuf_1_1_0_clock/Y (BUFx24_ASAP7_75t_R)
  38.03  183.39 ^ clkbuf_2_2_0_clock/Y (BUFx24_ASAP7_75t_R)
  32.54  215.93 ^ clkbuf_2_2_1_clock/Y (BUFx24_ASAP7_75t_R)
  30.64  246.57 ^ clkbuf_4_8_0_clock/Y (BUFx24_ASAP7_75t_R)
  22.98  269.55 ^ clkbuf_5_17_0_clock/Y (BUFx24_ASAP7_75t_R)
  23.41  292.96 ^ clkbuf_7_70__f_clock/Y (BUFx24_ASAP7_75t_R)
  21.94  314.91 ^ clkbuf_leaf_97_clock/Y (BUFx24_ASAP7_75t_R)
   0.77  315.68 ^ ces_4_0.REG_2[36]$_DFF_P_/CLK (DFFHQNx2_ASAP7_75t_R)
         315.68   data arrival time
---------------------------------------------------------
(Path is unconstrained)


openroad>
</pre>

**Comment by tspyrou** [comment]
The path with the most skew passes timing.

<pre>
openroad> report_clock_skew -setup
Clock clock
Latency      CRPR       Skew
ces_6_0.REG_1[27]$_DFF_P_/CLK ^
 419.44
ces_7_0.REG_2[27]$_DFF_P_/CLK ^
 323.03      0.00      96.41

openroad> report_checks -from ces_6_0.REG_1[27]\$_DFF_P_ -to ces_7_0.REG_2[27]\$_DFF_P_ -path_delay min
Startpoint: ces_6_0.REG_1[27]$_DFF_P_
            (rising edge-triggered flip-flop clocked by clock)
Endpoint: ces_7_0.REG_2[27]$_DFF_P_
          (rising edge-triggered flip-flop clocked by clock)
Path Group: clock
Path Type: min

  Delay    Time   Description
---------------------------------------------------------
   0.00    0.00   clock clock (rise edge)
 419.44  419.44   clock network delay (propagated)
   0.00  419.44 ^ ces_6_0.REG_1[27]$_DFF_P_/CLK (DFFHQNx2_ASAP7_75t_R)
  55.45  474.89 ^ ces_6_0.REG_1[27]$_DFF_P_/QN (DFFHQNx2_ASAP7_75t_R)
  27.66  502.54 ^ wire5069/Y (BUFx12f_ASAP7_75t_R)
  31.77  534.31 v _19487_/Y (INVx1_ASAP7_75t_R)
   0.07  534.38 v ces_7_0.REG_2[27]$_DFF_P_/D (DFFHQNx2_ASAP7_75t_R)
         534.38   data arrival time

   0.00    0.00   clock clock (rise edge)
 323.03  323.03   clock network delay (propagated)
  10.00  333.03   clock uncertainty
   0.00  333.03   clock reconvergence pessimism
         333.03 ^ ces_7_0.REG_2[27]$_DFF_P_/CLK (DFFHQNx2_ASAP7_75t_R)
   8.70  341.73   library hold time
         341.73   data required time
---------------------------------------------------------
         341.73   data required time
        -534.38   data arrival time
---------------------------------------------------------
         192.64   slack (MET)


openroad> report_checks -from ces_6_0.REG_1[27]\$_DFF_P_ -to ces_7_0.REG_2[27]\$_DFF_P_ -path_delay max
Startpoint: ces_6_0.REG_1[27]$_DFF_P_
            (rising edge-triggered flip-flop clocked by clock)
Endpoint: ces_7_0.REG_2[27]$_DFF_P_
          (rising edge-triggered flip-flop clocked by clock)
Path Group: clock
Path Type: max

  Delay    Time   Description
---------------------------------------------------------
   0.00    0.00   clock clock (rise edge)
 419.44  419.44   clock network delay (propagated)
   0.00  419.44 ^ ces_6_0.REG_1[27]$_DFF_P_/CLK (DFFHQNx2_ASAP7_75t_R)
  56.50  475.94 v ces_6_0.REG_1[27]$_DFF_P_/QN (DFFHQNx2_ASAP7_75t_R)
  29.76  505.69 v wire5069/Y (BUFx12f_ASAP7_75t_R)
  35.04  540.73 ^ _19487_/Y (INVx1_ASAP7_75t_R)
   0.07  540.80 ^ ces_7_0.REG_2[27]$_DFF_P_/D (DFFHQNx2_ASAP7_75t_R)
         540.80   data arrival time

 250.00  250.00   clock clock (rise edge)
 323.03  573.03   clock network delay (propagated)
 -10.00  563.03   clock uncertainty
   0.00  563.03   clock reconvergence pessimism
         563.03 ^ ces_7_0.REG_2[27]$_DFF_P_/CLK (DFFHQNx2_ASAP7_75t_R)
  -8.30  554.73   library setup time
         554.73   data required time
---------------------------------------------------------
         554.73   data required time
        -540.80   data arrival time
---------------------------------------------------------
          13.93   slack (MET)
</pre>

**Comment by tspyrou** [comment]
This sample design has a 250ps clock period which would be 4GHZ. The design closes for both setup and hold if I make it 2GHZ.

**Review by tspyrou — APPROVED** [review]

**Comment by oharboe** [comment]
> This sample design has a 250ps clock period which would be 4GHZ. The design closes for both setup and hold if I make it 2GHZ.

mock-array using macros close timing, setup and hold at 250ps clock period. (Well there is a -2ps slack on setup).

```
>>> report_checks
Startpoint: ces_6_0 (rising edge-triggered flip-flop clocked by clock)
Endpoint: ces_6_4 (rising edge-triggered flip-flop clocked by clock)
Path Group: clock
Path Type: max

  Delay    Time   Description
---------------------------------------------------------
   0.00    0.00   clock clock (rise edge)
 328.23  328.23   clock network delay (propagated)
   0.00  328.23 ^ ces_6_0/clock (Element)
 153.56  481.79 ^ ces_6_0/io_lsbOuts_7 (Element)
  41.14  522.94 ^ ces_6_1/io_lsbOuts_6 (Element)
  40.00  562.93 ^ ces_6_2/io_lsbOuts_5 (Element)
  36.94  599.87 ^ ces_6_3/io_lsbOuts_4 (Element)
   0.00  599.87 ^ ces_6_4/io_lsbIns_4 (Element)
         599.87   data arrival time

 250.00  250.00   clock clock (rise edge)
 303.81  553.81   clock network delay (propagated)
 -10.00  543.81   clock uncertainty
   9.32  553.13   clock reconvergence pessimism
         553.13 ^ ces_6_4/clock (Element)
  44.57  597.70   library setup time
         597.70   data required time
---------------------------------------------------------
         597.70   data required time
        -599.87   data arrival time
---------------------------------------------------------
          -2.17   slack (VIOLATED)


Startpoint: ces_7_0 (rising edge-triggered flip-flop clocked by clock)
Endpoint: io_outs_up_0[9] (output port clocked by clock_vir)
Path Group: clock_vir
Path Type: max

  Delay    Time   Description
---------------------------------------------------------
   0.00    0.00   clock clock (rise edge)
 341.22  341.22   clock network delay (propagated)
   0.00  341.22 ^ ces_7_0/clock (Element)
 164.71  505.93 ^ ces_7_0/io_outs_up[9] (Element)
  11.27  517.20 ^ output3712/Y (BUFx2_ASAP7_75t_R)
   0.02  517.22 ^ io_outs_up_0[9] (out)
         517.22   data arrival time

 250.00  250.00   clock clock_vir (rise edge)
 380.00  630.00   clock network delay (ideal)
 -10.00  620.00   clock uncertainty
   0.00  620.00   clock reconvergence pessimism
 -50.00  570.00   output external delay
         570.00   data required time
---------------------------------------------------------
         570.00   data required time
        -517.22   data arrival time
---------------------------------------------------------
          52.78   slack (MET)
```

image

**Comment by oharboe** [comment]
@maliberty unrelated CI failure.

**Pull request merged**
