### PR TITLE
Routability-driven RePlAce updates on ORFS repo

### PR DESCRIPTION
**Pull request by mgwoo**
Created setGR.tcl and applied in global_place.tcl.
Passed with all green marks under secure CI.

### CODE REVIEW

**Review by rovinski — CHANGES_REQUESTED** [review]
`setGR.tcl` appears to completely duplicate `fastroute.tcl`. We should just refactor `fastroute.tcl` to move the fastroute call into `global_route.tcl` and then source `fastroute.tcl` in `global_place.tcl`

**Comment by tspyrou** [comment]
@mgwoo tagging you. I think Austin's feedback makes sense. Once complete go ahead and merge it.

**Comment by maliberty** [comment]
@mgwoo this PR has not been merged so your change to the gf12 repo just broke the secure CI.  I am going to revert your change.  Please reinstate it only after this is merged to master!

**Comment by rovinski** [comment]
@mgwoo you need to re-add the "Ready to Sync to Public" label on the private PR in order to get the commits to sync to here.

**Review by rovinski — APPROVED** [review]

**Comment by mgwoo** [comment]
@maliberty  Could you check?

**Review by maliberty — APPROVED** [review]

**Pull request merged**
