### PR TITLE
Additional gds misspelling

### PR DESCRIPTION
**Pull request by oharboe**
I think this is a misspelling, but I'm unsure...

### CODE REVIEW

**Comment by rovinski** [comment]
No, I think it was mostly intentional. `ADDITIONAL_LIBS` is clearly plural and so is `ADDITIONAL_LEFS`, so it is obvious that they are list variables. How do you make it obvious that GDS is plural? `GDSS` is bad, `GDSES` isn't good either.

**Comment by maliberty** [comment]
I agree with @rovinski that the pluralization is important and hard to effect otherwise.

If you really want consistency then you could change ADDITIONAL_LIBS -> ADDITIONAL_LIB_FILES  etc

**Comment by oharboe** [comment]
@rovinski @maliberty The purpose of this PR is to make the code consistent as it stands. To rename ADDITIONAL_GDS to something else, is a concern for a different pull request, no?

The bp_multi_top nangate45 failure, I've seen in other PRs too. I think it is a false positive.

**Comment by maliberty** [comment]
Making it consistent also makes it worse in a different way so it isn't a pure win.  That's why I suggested going the other way if you want consistency "If you really want consistency then you could change ADDITIONAL_LIBS -> ADDITIONAL_LIB_FILES etc"

"bp_multi_top nangate45 failure," is fixed in master now.

**Comment by oharboe** [comment]
@maliberty I am happy to do a search and replace on the entire repository, but it is going touch all scripts and lots of code....

This pull request boards up the broken window and allows us to choose a time to fix everything everywhere....

**Comment by maliberty** [comment]
I'm not sure the cure is better than the disease.  The current is irregular but clear; your alternative is regular but unclear.  I find clarity more important.

I would expect ADDITIONAL_GDS to be a single file not a list of files based on the name.

**Comment by maliberty** [comment]
I seems to have been an intentional choice not a "broken window" or a "misspelling"

**Comment by oharboe** [comment]
> I seems to have been an intentional choice not a "broken window" or a "misspelling"

I guess I am weary of changing the interface to the ORFS. This name is not an implementation detail, it is part of the ORFS interface.

Changing the interface to improve naming is a separate concern from fixing a problem in the implementation. Hence, I would do this as two commits(one concern per commit) even if it was done as a single pull request. If I was a stickler for one concern per commit.

**Comment by maliberty** [comment]
I don't want to weary you and appreciate you working on this.  I don't understand your comment about "fixing a problem in the implementation".  When I look at this PR I just see a rename.  What is the fixed problem?

**Comment by maliberty** [comment]
I think I see what you are referring to.  The various platforms are out of sync:
```
platforms/asap7/config.mk\011:                                 $(ADDITIONAL_GDS)
platforms/asap7/config.mk\0142:																	  $(ADDITIONAL_GDS)
platforms/asap7/config.mk\0193:																	 $(ADDITIONAL_GDS)
platforms/nangate45/config.mk\013:                     $(ADDITIONAL_GDS)
platforms/sky130hd/config.mk\013:                     $(ADDITIONAL_GDS_FILES)
platforms/sky130hs/config.mk\013:                     $(ADDITIONAL_GDS_FILES)
platforms/sky130hd_fakestack/config.mk\013:                     $(ADDITIONAL_GDS_FILES)
platforms/gf180/config.mk\021:                                                $(ADDITIONAL_GDS)
```

**Review by maliberty — APPROVED** [review]
I finally get it.  We are already using ADDITIONAL_GDS in most places so this change is to use it everywhere.  I think a bit more explanation in the PR would have made this go a lot more smoothly.

We can take up the rename separately as you suggest.

**Comment by oharboe** [comment]
> I finally get it. We are already using ADDITIONAL_GDS in most places so this change is to use it everywhere. I think a bit more explanation in the PR would have made this go a lot more smoothly.
> 
> We can take up the rename separately as you suggest.

Indeed. Will work on it. As I learn more I will be able to articulate better, there is a lot of guesswork still....

**Pull request merged**
