### PR TITLE
designs/asap7/mock-array-big: use -group and -order correctly

### PR DESCRIPTION
**Pull request by oharboe**

### CODE REVIEW

**Comment by maliberty** [comment]
Does this change require another OR submodule update?

**Comment by vvbandeira** [comment]
I missed this PR and started #908 once I saw the master branch failing. I have just updated my PR to include this fix -- it also has the metrics update for the failing designs.

**Comment by maliberty** [comment]
I think this is covered by Vitor's PR - if so please close.

**Comment by oharboe** [comment]
> I think this is covered by Vitor's PR - if so please close.

Vitor undid this PR because openroad master is broken. @eder-matheus has an issue assigned to fix the bug when this PR is applied.

**Comment by oharboe** [comment]
@maliberty @eder-matheus ready to merge.

**Review by maliberty — APPROVED** [review]

**Pull request merged**
