### PR TITLE
mock-array: remove -distance_between_buffers 60

### PR DESCRIPTION
**Pull request by oharboe**
picked up by accident, asap7 no longer has this as a default

### CODE REVIEW

**Comment by maliberty** [comment]
I'm not sure if you need to merge master but
```
[ERROR] cts__design__instance__count__hold_buffer fail test: 3500.0 <= 1073.0
[ERROR] detailedroute__route__wirelength fail test: 73801.0 <= 73578.0
```
I saw no failure when I removed this option.

**Comment by oharboe** [comment]
@maliberty I tried a quick cleanup of this accidental change that crept in before the Asap7 default cts args cleanup.

Feel free to complete cleanup, closing for my part for now.

**Comment by oharboe** [comment]
@maliberty Merge with latest OpenROAD once https://github.com/The-OpenROAD-Project/OpenROAD/issues/4666 is fixed and it should work.

**Comment by oharboe** [comment]
moot

**Pull request closed without merging**
