### PR TITLE
synth: better names, which helps .sdc articulation and debugging

### PR DESCRIPTION
**Pull request by oharboe**
Let's see how it fares now... Last time this stranded because there were some regressions in quality of results. No change was expected from simply renaming wires...

### CODE REVIEW

**Review by tspyrou — CHANGES_REQUESTED** [review]
It would be good to add a test that shows how the name has changed for the better. For example a puts of all register names.

**Comment by oharboe** [comment]
> It would be good to add a test that shows how the name has changed for the better. For example a puts of all register names.

we will use this for .sdc constraints for fifo's. would that fit the bill?

**Review by tspyrou — APPROVED** [review]

**Comment by tspyrou** [comment]
@vvbandeira can you push this one through. The failures are minor metrics changes.

**Comment by maliberty** [comment]
gcd sky130hs failed to complete.  Please also run a secure CI as I recall we had issues the last time we tried this.

**Comment by oharboe** [comment]
> gcd sky130hs failed to complete. Please also run a secure CI as I recall we had issues the last time we tried this.

@tspyrou Could you debug the failure, it is in CTS. I have not seen that failure before...

**Comment by oharboe** [comment]
@maliberty I can't debug the sky130hs gcd failure because of #1775. When I disable EQUIVALENCE_CHECK, cts passes.

**Comment by maliberty** [comment]
From logs/sky130hs/gcd/base/4_equivalence_check.log
```
EQY 11:22:58 [./logs/sky130hs/gcd/base/4_eqy_output] read_gold: starting process "yosys -ql ./logs/sky130hs/gcd/base/4_eqy_output/gold.log ./logs/sky130hs/gcd/base/4_eqy_output/gold.ys"
EQY 11:22:59 [./logs/sky130hs/gcd/base/4_eqy_output] read_gold: /workspaces/mliberty/w1/OpenROAD-flow-scripts/flow/platforms/sky130hs/work_around_yosys/formal_pdk.v:2094: Warning: Identifier `\Y' is implicitly declared.
EQY 11:22:59 [./logs/sky130hs/gcd/base/4_eqy_output] read_gate: starting process "yosys -ql ./logs/sky130hs/gcd/base/4_eqy_output/gate.log ./logs/sky130hs/gcd/base/4_eqy_output/gate.ys"
EQY 11:22:59 [./logs/sky130hs/gcd/base/4_eqy_output] read_gold: ERROR: Module `\sky130_fd_sc_hs__clkdlyinv3sd1_1' referenced in module `\gcd' in cell `\_433_' is not part of the design.
EQY 11:22:59 [./logs/sky130hs/gcd/base/4_eqy_output] read_gold: finished (returncode=1)
EQY 11:22:59 [./logs/sky130hs/gcd/base/4_eqy_output] read_gold: job failed. ERROR.
EQY 11:22:59 [./logs/sky130hs/gcd/base/4_eqy_output] read_gate: terminating process
```
no clue....

**Comment by maliberty** [comment]
formal_pdk.v<sky130hs> is missing a bunch of cells and now we are using one.

**Comment by oharboe** [comment]
> formal_pdk.v is missing a bunch of cells and now we are using one.

So disable eqy the test because it cant work yet?

**Comment by maliberty** [comment]
I'll add the clkdlyinv cells.

**Comment by maliberty** [comment]
merge master once https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/1777 goes through

**Comment by vijayank88** [comment]
similar update https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/1129 not merged.

**Comment by oharboe** [comment]
> similar update #1129 not merged.

It's the same change resurrected. The issues are now bottomed out on and/or fixed. The only thing that is missing is for @vvbandeira to test on the secure server + update the reference data. As I understand it.

@tspyrou ?

**Comment by maliberty** [comment]
There are still multiple non-metric errors even in the public CI.  It is the same story as before and will take a while to resolve.

**Comment by oharboe** [comment]
> There are still multiple non-metric errors even in the public CI. It is the same story as before and will take a while to resolve.

I see a timeout in detailed routing and failure in detailed placement. Probably good things to have fixed anyway, but, yes, has to be done.

Will you follow up?

**Comment by maliberty** [comment]
I see at least one is due to missing Eder's recent tapcell fix.  Please merge master into ORFS and update the OR submodule to the head of master.

**Comment by oharboe** [comment]
> I see at least one is due to missing Eder's recent tapcell fix. Please merge master into ORFS and update the OR submodule to the head of master.

Done.

**Comment by maliberty** [comment]
started a secure CI

**Comment by maliberty** [comment]
@vvbandeira I think this is down to metric (& drc) updates.  Please take over.

**Comment by oharboe** [comment]
> @vvbandeira I think this is down to metric (& drc) updates. Please take over.

jpeg sky130hd times out in detailed routing.

**Comment by maliberty** [comment]
> jpeg sky130hd times out in detailed routing.

@osamahammad21 please take a look at this

**Comment by maliberty** [comment]
@osamahammad21 note that all violations are on met1

**Comment by tspyrou** [comment]
@vvbandeira and @osamahammad21 is the work to complete fixing up the metrics in progress or stuck?

**Comment by maliberty** [comment]
@tspyrou its not just metrics - we have a failure to resolve.

**Comment by gudeh** [comment]
> jpeg sky130hd times out in detailed routing.

@oharboe Could you try to add the following lines to line 35 at `/flow/scripts/global_place.tcl` and re-execute jpeg sky130hd? 

```
if {$::env(GPL_ROUTABILITY_DRIVEN)} {
  lappend global_placement_args {-routability_target_rc_metric}
  lappend global_placement_args {1.0}
}
```

With that I was able to run the complete flow on my end.

**Comment by oharboe** [comment]
@gudeh I dont think it is necessary to verify this, your test is adequate.

@maliberty Is this an adequate fix? If the timeout is due to a bug that has always been there and the reason it is triggered is simply a sensitivity to initial conditions, then the failure is a separate concern that could be broken out in a separate bugreport and this PR can go in with this workaround?

**Comment by gudeh** [comment]
It is worth mentioning that the other failures on gf180/riscv32i, asap7/jpeg_lvt, and nangate45/gcd still occur.

**Comment by oharboe** [comment]
@maliberty @tspyrou Is there any progress on this? I merged with latest master, just to see what happens currently on master. Are the remaining problems in confidential CI? Can the confidential CI baseline QoR be updated and then fixed later so this PR can be merged? github issues can be written up post-merge w.r.t. confidential CI regressions(although the designs are confidential, the problems that have to be fixed might not be?).

**Comment by maliberty** [comment]
There are still some issues remaining.  It is being worked on.

**Comment by tspyrou** [comment]
@maliberty @vvbandeira the diffs on these look trivial. Is it ready to merge?

**Comment by eder-matheus** [comment]
> @maliberty @vvbandeira the diffs on these look trivial. Is it ready to merge?

@tspyrou I'm looking into this update, and I started a secure-ci earlier today to check how it is with our latest updates in OR and ORFS. If everything is well, we will merge this today or tomorrow.

**Comment by eder-matheus** [comment]
@oharboe I've started this PR that is doing the changes you added here, but also with the necessary metric updates in our designs. Do you mind if we continue this update with this new PR (https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/1846)?

The commits you made still there, so the ownership of the updates are preserved.

**Comment by oharboe** [comment]
fixed by #1846

**Pull request closed without merging**
