### PR TITLE
cts: remove unused CTS_CLUSTER_DIAMETER and CTS_CLUSTER_SIZE

### PR DESCRIPTION
**Pull request by oharboe**

### CODE REVIEW

**Comment by maliberty** [comment]
They are used by the autotuner so I don't view them as unused.

**Comment by oharboe** [comment]
> They are used by the autotuner so I don't view them as unused.

Autotuner is changing these options, but the options are no longer connected to anything.

**Comment by maliberty** [comment]
@precisionmoon I see you disconnected these options in https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/commit/9cb596fd9eb50f5c0c13a1b26ffb25a77289802a - what was the motivation?  The options still seem to exist in the cts code base.

**Comment by precisionmoon** [comment]
These options are still valid.  They are no longer required.  A message is
issued when they are used though about possible sub-optimal solution.

**Comment by maliberty** [comment]
The autotuner might still be able to find a better than default value, no?

**Comment by precisionmoon** [comment]
Yes.

**Comment by maliberty** [comment]
Then I think we should reconnect those values in ORFS even if we undocument them for users [or document them as for ML only].  (@luarss FYI)

**Pull request closed without merging**
