### PR TITLE
flow: platforms: ihp-sg13g2: Add IO files

### PR DESCRIPTION
**Pull request by dnltz**
Add all IO related lib, lef, and gds files when 'HAS_IO_RING' is set to 1. Those files will be appended to the 'ADDITIONAL_x' variables.

- [x] blocked by #2084

### CODE REVIEW

**Comment by dnltz** [comment]
@maliberty any concerns about adding `HAS_IO_RING` as optional environment variable? Should I document that somewhere?

**Comment by maliberty** [comment]
> @maliberty any concerns about adding `HAS_IO_RING` as optional environment variable? Should I document that somewhere?

In order to generate a pad ring the user will need to set FOOTPRINT_TCL (or the obsolete FOOTPRINT).  HAS_IO_RING seems redundant.

**Comment by dnltz** [comment]
> FOOTPRINT_TCL

That's even better, thanks!

**Comment by dnltz** [comment]
@KrzysztofHerman fyi

**Comment by maliberty** [comment]
This is marked as a draft - should I hold off on review?

**Comment by dnltz** [comment]
> This is marked as a draft - should I hold off on review?

yeah, let's start when the other PR got merged since this fails anyway

**Comment by dnltz** [comment]
@maliberty since all required files are on master now, this PR is ready for review :)

**Review by maliberty — APPROVED** [review]
Is there a plan to generate a non-dummy IO lib file?

**Comment by dnltz** [comment]
@maliberty lib files for IO cells are only available in the dev branch: https://github.com/IHP-GmbH/IHP-Open-PDK/tree/dev/ihp-sg13g2/libs.ref/sg13g2_io/lib

So, should be available with the next merge to main.

**Comment by maliberty** [comment]
@dnltz will you make a PR once they are ready?

**Comment by dnltz** [comment]
sure, can do that.

**Pull request merged**
