### PR TITLE
makefile: SUB_MAKE tweak

### PR DESCRIPTION
**Pull request by oharboe**
Be explicit about which makefiles to invoke

### CODE REVIEW

**Review by maliberty — APPROVED** [review]
What problem prompted this PR?

**Comment by oharboe** [comment]
> What problem prompted this PR?

bazel use cases where the project is not in the same rep as orfs....

**Comment by maliberty** [comment]
This breaks the CI at UCSD and will have to be reverted.  It produces
```
make: the '-f' option requires a non-empty string argument
```
on every build.

**Comment by oharboe** [comment]
> This breaks the CI at UCSD and will have to be reverted. It produces
> 
> ```
> make: the '-f' option requires a non-empty string argument
> ```
> 
> on every build.

Where can I see this error? What version of make are they running?

This should fix it:

https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/2134

Could you:

- run `make print-MAKEFILE_LIST`
- Test the updated https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/2138

**Pull request merged**
