### PR TITLE
asap7: remove uart-blocks

### PR DESCRIPTION
**Pull request by oharboe**
it does not add much testing value as there are other designs testing BLOCKS.

I added this design back when I was first experimenting with BLOCKS and asap7 and there were no BLOCKS examples in asap7.

### CODE REVIEW

**Comment by oharboe** [comment]
@maliberty unrelated failures in CI

**Comment by maliberty** [comment]
@vijayank88 you added uart - any thoughts on this?

**Comment by vijayank88** [comment]
@maliberty 
`uart` different from `uart-blocks`. 
`uart-blocks` added by @oharboe only.
Now there are many test cases with `BLOCKS` options. So, if this test case not required mean, approve this.

**Comment by oharboe** [comment]
> @maliberty `uart` different from `uart-blocks`. `uart-blocks` added by @oharboe only. Now there are many test cases with `BLOCKS` options. So, if this test case not required mean, approve this.

Can we remove all uses of uart-blocks now? I only removed the one in asap7, I was unsure if the uart-blocks in gf180 had any value.

**Comment by maliberty** [comment]
@vijayank88 you did add it for gf180.  Any thoughts there?

**Review by maliberty — APPROVED** [review]

**Pull request merged**
