### PR TITLE
Change default Yosys compiler to Clang with disabled debugging

### PR DESCRIPTION
**Pull request by eszpotanski**
This PR changes the default options used for building Yosys to `clang++ -O3 -DNDEBUG -fPIC`

Currently used build options for Yosys (`g++ -fPIC -Os`) seems to be sub-optimal - results of synthesis benchmarks run with Yosys 0.42 (git sha1 9b6afcf3f) on Ibex (averaged from 10 runs):
|    | g++ 14.1.1 -fPIC -Os | g++ 14.1.1 -O3 -DNDEBUG -fPIC | clang++ 17.0.6 -fPIC -Os | clang++ 17.0.6 -O3 -DNDEBUG -fPIC |
|--|------------------------------|---------------------|------------------------------|------------------------------|
| Elapsed time |          55.987s              |     55.599s          |51.951s                       |51.768s                        |

Benchmark for BoomTile synthesis (based on 1 run):
|    | g++ 14.1.1 -fPIC -Os | g++ 14.1.1 -O3 -DNDEBUG -fPIC | clang++ 17.0.6 -fPIC -Os | clang++ 17.0.6 -O3 -DNDEBUG -fPIC |
|--|------------------------------|---------------------|------------------------------|------------------------------|
| Elapsed time (first synth) |60m12s                        |55m03s               |57m33s                        |54m40s                        |
| Elapsed time (second synth) |64m37s                        |58m01s               |59m43s                        |57m02s                        |
| Whole synthesis |124m51s                       |113m06s              |117m20s                       |111m43s                       |

The new build options provides around 8.2% speedup for Ibex synthesis, and 11.7% for BoomTile synthesis.

### CODE REVIEW

**Comment by maliberty** [comment]
I don't see anything in this PR that change -Os to -O3

**Comment by eszpotanski** [comment]
> I don't see anything in this PR that change -Os to -O3

Adding `ENABLE_NDEBUG=1` automatically changes used option in [Yosys Makefile](https://github.com/The-OpenROAD-Project/yosys/blob/master/Makefile#L437). Also, build options are visible in [CI](https://jenkins.openroad.tools/blue/organizations/jenkins/OpenROAD-flow-scripts-Public%2Fpublic_tests_all-pr/detail/PR-2110-merge/1/pipeline/150#step-531-log-329): `Yosys 0.42 (git sha1 9b6afcf3f, clang++ 14.0.0-1ubuntu1.1 -O3 -DNDEBUG -fPIC)`

**Review by maliberty — APPROVED** [review]

**Comment by maliberty** [comment]
@gadfort @QuantamHD FYI in case you build yosys in your env

**Comment by widlarizer** [comment]
Beware that defining NDEBUG also removes all asserts in yosys. This means OpenROAD users will no longer be able to discover a category of yosys bugs easily when they happen!

**Comment by widlarizer** [comment]
I have discussed this with other yosys contributors. We have decided to make yosys use `-O3` by default soon. @eszpotanski would you mind and retest with a modified Makefile to use `-O3` without `-DNDEBUG` ? It is possible that removing some frequent asserts is a part of the speedup you're seeing and I'd like to investigate further if that is the case

**Comment by maliberty** [comment]
Once you release yosys with that change I'll revert this.

**Pull request merged**
