### PR TITLE
designs/asap7/aes-block: fix constraints/CTS

### PR DESCRIPTION
**Pull request by oharboe**
The aes-block should not have hold cells introduced at the submacros

### CODE REVIEW

**Review by maliberty — APPROVED** [review]

**Comment by oharboe** [comment]
@maliberty I don't recognize these CI errors, something intermittently wrong on the servers or on master?

**Comment by maliberty** [comment]
There was a bunch of CI chaos yesterday.   @vvbandeira please look at this as it looks like an infrastructure issue.

**Comment by vvbandeira** [comment]
This is the only current error:
```
------------------------------
       Failing designs
------------------------------
asap7 aes-block (base)
  Flow reached last stage.
  Found 1 metrics failures.
      [ERROR] finish__timing__setup__ws fail test: -355.649 >= -325.46
```

`pr-head` will fail as your branch is not updated with the `master` branch, but if `pr-merge` is green the PR can be merged.

**Comment by oharboe** [comment]
@maliberty So good to go?

**Comment by maliberty** [comment]
> @maliberty So good to go?

No you need to update the metrics as pr-merge is still failing.

**Comment by maliberty** [comment]
Note that the 80ps is max delay at the block level is apparently not good as setup is degraded while trying to resolve the hold

**Comment by oharboe** [comment]
Will rework and reopen... out of sight out of mind meanwhile...

**Pull request closed without merging**
