### PR TITLE
mock-array: improve clock skew

### PR DESCRIPTION
**Pull request by oharboe**
use x/y feature by @louiic and the tip from @maliberty 

https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/1220#issuecomment-1630216386

image

### CODE REVIEW

**Review by maliberty — APPROVED** [review]

**Comment by maliberty** [comment]
You might want to tighten the metrics as this saves a bunch of buffers.

**Comment by oharboe** [comment]
> You might want to tighten the metrics as this saves a bunch of buffers.

What are "mertrics"? I have a tighter floorplan and shorter clock period in the pending PRs.

**Comment by maliberty** [comment]
make update_ok

**Comment by oharboe** [comment]
> make update_ok

done in subsequent commits

**Pull request merged**
