### PR TITLE
make: elapsed prints times for BLOCKS

### PR DESCRIPTION
**Pull request by oharboe**
github displays this misleadingly. There are actually very few changes, this PR refactors the code into a function and makes a few tweaks, run with `git show -w` locally to see that there are very few changes:

image

### CODE REVIEW

**Comment by oharboe** [comment]
Example output. Here we can easily see that the LoadStoreUnit and RegisterFile modules take a very long time and merit some further investigation.

```
make DESIGN_CONFIG=designs/asap7/megaboom/config.mk elapsed
[INFO][FLOW] Using platform directory ./platforms/asap7
[INFO-FLOW] ASU ASAP7 - version 2
Default PVT selection: BC
[INFO][FLOW] Invoked hierarchical flow.
Block _T_157_ext needs to be hardened.
Block _T_80_ext needs to be hardened.
Block tag_array_ext needs to be hardened.
Block _T_850_ext needs to be hardened.
Block entries_info_ext needs to be hardened.
Block smem_ext needs to be hardened.
Block smem_0_ext needs to be hardened.
Block mem_1_ext needs to be hardened.
Block RegisterFile needs to be hardened.
Block RenameStage needs to be hardened.
Block LoadStoreUnit needs to be hardened.
Block IssueUnitCollasping needs to be hardened.
Block Rob needs to be hardened.
Block ALUExeUnit needs to be hardened.
Block ALUExeUnit_2 needs to be hardened.
Block BranchPredictionStage needs to be hardened.
./logs/asap7/megaboom__T_157_ext/base/
Log                       Elapsed seconds
1_1_yosys                         41
2_1_floorplan                      5
2_2_floorplan_io                   1
2_3_floorplan_tdms                 1
2_4_floorplan_macro                1
2_5_floorplan_tapcell              1
2_6_floorplan_pdn                  1
3_1_place_gp_skip_io               6
3_2_place_iop                      1
3_3_place_gp                      22
3_4_place_resized                 16
3_5_place_dp                      11
4_1_cts                           21
4_2_cts_fillcell                   1
5_1_grt                           10
5_2_route                        123
6_1_merge                          3
6_report                          39
./logs/asap7/megaboom__T_80_ext/base/
Log                       Elapsed seconds
1_1_yosys                        178
2_1_floorplan                     38
2_2_floorplan_io                   1
2_3_floorplan_tdms                 1
2_4_floorplan_macro                1
2_5_floorplan_tapcell              3
2_6_floorplan_pdn                  4
3_1_place_gp_skip_io              42
3_2_place_iop                      2
3_3_place_gp                     178
3_4_place_resized                126
3_5_place_dp                      89
4_1_cts                          108
4_2_cts_fillcell                   3
5_1_grt                           58
5_2_route                        729
6_1_merge                         15
6_report                         289
./logs/asap7/megaboom_tag_array_ext/base/
Log                       Elapsed seconds
1_1_yosys                         40
2_1_floorplan                      4
2_2_floorplan_io                   1
2_3_floorplan_tdms                 1
2_4_floorplan_macro                1
2_5_floorplan_tapcell              1
2_6_floorplan_pdn                  1
3_1_place_gp_skip_io               5
3_2_place_iop                      1
3_3_place_gp                      18
3_4_place_resized                 14
3_5_place_dp                      10
4_1_cts                           18
4_2_cts_fillcell                   1
5_1_grt                            9
5_2_route                        113
6_1_merge                          3
6_report                          34
./logs/asap7/megaboom__T_850_ext/base/
Log                       Elapsed seconds
1_1_yosys                        181
2_1_floorplan                     43
2_2_floorplan_io                   1
2_3_floorplan_tdms                 2
2_4_floorplan_macro                1
2_5_floorplan_tapcell              3
2_6_floorplan_pdn                  4
3_1_place_gp_skip_io              43
3_2_place_iop                      2
3_3_place_gp                     178
3_4_place_resized                131
3_5_place_dp                      92
4_1_cts                          111
4_2_cts_fillcell                   3
5_1_grt                           60
5_2_route                        767
6_1_merge                         16
6_report                         298
./logs/asap7/megaboom_entries_info_ext/base/
Log                       Elapsed seconds
1_1_yosys                         20
2_1_floorplan                      2
2_2_floorplan_io                   1
2_3_floorplan_tdms                 1
2_4_floorplan_macro                1
2_5_floorplan_tapcell              1
2_6_floorplan_pdn                  1
3_1_place_gp_skip_io               2
3_2_place_iop                      1
3_3_place_gp                       5
3_4_place_resized                  4
3_5_place_dp                       6
4_1_cts                            9
4_2_cts_fillcell                   1
5_1_grt                            3
5_2_route                         41
6_1_merge                          1
6_report                          10
./logs/asap7/megaboom_smem_ext/base/
Log                       Elapsed seconds
1_1_yosys                         49
2_1_floorplan                      4
2_2_floorplan_io                   1
2_3_floorplan_tdms                 1
2_4_floorplan_macro                1
2_5_floorplan_tapcell              1
2_6_floorplan_pdn                  1
3_1_place_gp_skip_io               5
3_2_place_iop                      1
3_3_place_gp                      20
3_4_place_resized                 14
3_5_place_dp                      14
4_1_cts                           20
4_2_cts_fillcell                   1
5_1_grt                            9
5_2_route                        120
6_1_merge                          3
6_report                          36
./logs/asap7/megaboom_smem_0_ext/base/
Log                       Elapsed seconds
1_1_yosys                         87
2_1_floorplan                      8
2_2_floorplan_io                   1
2_3_floorplan_tdms                 1
2_4_floorplan_macro                1
2_5_floorplan_tapcell              1
2_6_floorplan_pdn                  2
3_1_place_gp_skip_io              12
3_2_place_iop                      1
3_3_place_gp                      40
3_4_place_resized                 28
3_5_place_dp                      30
4_1_cts                           35
4_2_cts_fillcell                   1
5_1_grt                           18
5_2_route                        227
6_1_merge                          5
6_report                          74
./logs/asap7/megaboom_mem_1_ext/base/
Log                       Elapsed seconds
1_1_yosys                        212
2_1_floorplan                     41
2_2_floorplan_io                   1
2_3_floorplan_tdms                 2
2_4_floorplan_macro                2
2_5_floorplan_tapcell              3
2_6_floorplan_pdn                  4
3_1_place_gp_skip_io              43
3_2_place_iop                      2
3_3_place_gp                     210
3_4_place_resized                197
3_5_place_dp                     159
4_1_cts                          119
4_2_cts_fillcell                   3
5_1_grt                           80
5_2_route                       1288
6_1_merge                         16
6_report                         296
./logs/asap7/megaboom_RegisterFile/base/
Log                       Elapsed seconds
1_1_yosys                        284
2_1_floorplan                     50
2_2_floorplan_io                   2
2_3_floorplan_tdms                 2
2_4_floorplan_macro                2
2_5_floorplan_tapcell              6
2_6_floorplan_pdn                  8
3_1_place_gp_skip_io              91
3_2_place_iop                      3
3_3_place_gp                     685
3_4_place_resized                161
3_5_place_dp                     127
4_1_cts                          188
4_2_cts_fillcell                   6
5_1_grt                          122
5_2_route                       2070
6_1_merge                         31
6_report                         910
./logs/asap7/megaboom_RenameStage/base/
Log                       Elapsed seconds
1_1_yosys                        469
2_1_floorplan                     22
2_2_floorplan_io                   1
2_3_floorplan_tdms                 1
2_4_floorplan_macro                1
2_5_floorplan_tapcell              2
2_6_floorplan_pdn                  4
3_1_place_gp_skip_io              28
3_2_place_iop                      3
3_3_place_gp                     277
3_4_place_resized                 74
3_5_place_dp                      54
4_1_cts                          123
4_2_cts_fillcell                   3
5_1_grt                           60
5_2_route                        759
6_1_merge                         13
6_report                         324
./logs/asap7/megaboom_LoadStoreUnit/base/
Log                       Elapsed seconds
1_1_yosys                       1670
2_1_floorplan                    105
2_2_floorplan_io                   2
2_3_floorplan_tdms                 2
2_4_floorplan_macro                3
2_5_floorplan_tapcell             13
2_6_floorplan_pdn                 16
3_1_place_gp_skip_io             156
3_2_place_iop                      5
3_3_place_gp                    1446
3_4_place_resized                335
3_5_place_dp                     298
4_1_cts                          934
4_2_cts_fillcell                  12
5_1_grt                          436
5_2_route                       4537
6_1_merge                         65
6_report                         945
./logs/asap7/megaboom_IssueUnitCollasping/base/
Log                       Elapsed seconds
1_1_yosys                        459
2_1_floorplan                     55
2_2_floorplan_io                   2
2_3_floorplan_tdms                 2
2_4_floorplan_macro                2
2_5_floorplan_tapcell              6
2_6_floorplan_pdn                  9
3_1_place_gp_skip_io              96
3_2_place_iop                      3
No elapsed time found in logs/asap7/megaboom_IssueUnitCollasping/base/3_3_place_gp.tmp.log
./logs/asap7/megaboom_Rob/base/
./logs/asap7/megaboom_ALUExeUnit/base/
./logs/asap7/megaboom_ALUExeUnit_2/base/
./logs/asap7/megaboom_BranchPredictionStage/base/
./logs/asap7/megaboom/base
```

**Comment by vijayank88** [comment]
@oharboe 
Check CI `Util Scripts` failures.

**Comment by oharboe** [comment]
> @oharboe Check CI `Util Scripts` failures.

Fixed. Thanks!

**Review by maliberty — APPROVED** [review]

**Comment by maliberty** [comment]
Note that you can achieve the same effect in GH with the 'Hide whitespace'
image

**Pull request merged**
