### PR TITLE
refactor deltadebug

### PR DESCRIPTION
**Pull request by habibayassin**
Merged together with this [PR](https://github.com/The-OpenROAD-Project/OpenROAD/pull/5223) in OR

### CODE REVIEW

**Review by oharboe — CHANGES_REQUESTED** [review]
why are the paths added? if these are required now, then deltaDebug is less userfriendly than before

**Comment by habibayassin** [comment]
> why are the paths added? if these are required now, then deltaDebug is less userfriendly than before

@oharboe what do you suggest? should it have the paths set in the script itself as a default?

**Comment by oharboe** [comment]
@habibayassin @maliberty There are now paths that I have never heard about that I have to pass in to deltaDebug.py. 

I just don't know what to make of it, so to my mind, the user interface to deltaDebug.py got worse...

**Comment by oharboe** [comment]
@habibayassin @vvbandeira @maliberty Are the deltaDebug.py tests hooked up to CI https://github.com/The-OpenROAD-Project/OpenROAD/issues/5377 ?

**Pull request closed without merging**
