### PR TITLE
Add export command

### PR DESCRIPTION
**Pull request by ObiWanRohan**
Added an export command to allow exporting the reports, logs, and results of a complete run

### CODE REVIEW

**Comment by maliberty** [comment]
What is the motivation for this change?  
Why doesn't it copy objects/ ?

**Comment by ObiWanRohan** [comment]
This command is meant to output an export of everything related to one run.
This is a preliminary version, and I wanted to start a discussion on which files would be beneficial to copy over.

Also, I'm fairly new to the OpenROAD flow, and I'm not sure what the `objects` directory contains

**Comment by maliberty** [comment]
objects/ contains some preprocessed inputs and should be considered part of the run.

**Comment by maliberty** [comment]
What are you exporting to?  If you just want to make multiple runs FLOW_VARIANT is more useful as you can still access the results (eg bring up the GUI).

**Comment by ObiWanRohan** [comment]
Thanks for the `FLOW_VARIANT` suggestion. It looks quite useful.

The export feature is supposed to allow creating a single folder with everything. The use case is to share the files and to keep a record.

**Comment by maliberty** [comment]
Sorry I lost track of this PR.   I'm not clear on how this is beneficial over make issue.

**Comment by ObiWanRohan** [comment]
What does `make issue` do?

**Comment by maliberty** [comment]
It packages a tar.gz with everything needed to reproduce a given run

**Comment by maliberty** [comment]
See https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/blob/f2b56bf1a4e9aa5733552faec9584e5f5173dac8/flow/util/utils.mk#L81

**Comment by vvbandeira** [comment]
@ObiWanRohan setting `COPY_ISSUE` might also prove helpful for your use case. See:
https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/blob/f2b56bf1a4e9aa5733552faec9584e5f5173dac8/flow/util/makeIssue.sh#L116-L119

**Comment by maliberty** [comment]
The appears to be stale.  You an reopen if there is something to progress on here.

**Pull request closed without merging**
