### PR TITLE
Use berkeley ABC in yosys build

### PR DESCRIPTION
**Pull request by mathursanjiv**
Fix for issue: https://openroad.atlassian.net/browse/OR-1094

Signed-off-by: Sanjiv Mathur <mathur.sanjiv@gmail.com>

### CODE REVIEW

**Comment by maliberty** [comment]
This only updates the local build and not the docker build.

You should run secure-ci on this change.

**Comment by rovinski** [comment]
Seems weird that we're only updating ABC and not yosys?

**Comment by maliberty** [comment]
> Seems weird that we're only updating ABC and not yosys?
@rovinski yosys hasn't updated to the latest abc which we require.

**Comment by mathursanjiv** [comment]
> This only updates the local build and not the docker build.
> 
> You should run secure-ci on this change.

@maliberty Updated docker build. I cannot do secure CI run from public fork. Would do in a separate branch and share.

**Comment by maliberty** [comment]
> @maliberty Updated docker build. I cannot do secure CI run from public fork. Would do in a separate branch and share.

Approval pending on your result.

**Comment by mathursanjiv** [comment]
> > @maliberty Updated docker build. I cannot do secure CI run from public fork. Would do in a separate branch and share.
> 
> Approval pending on your result.

Yes, have been having IT problems. Hopefully would get it resolved soon and fire runs.

**Review by maliberty — APPROVED** [review]
secure-ci passed

**Pull request merged**
