### PR TITLE
asap7 v28 update + little script updates

### PR DESCRIPTION
**Pull request by joennlae**
GIthub cannot render changes due to the swapped library files :-)

I worked heavily with ASAP7 for a project and thought I would upstream my changes.
I will try to reason why every commit makes sense but I am happy to discuss and also eager to see the results of the CI. We probably have to update things after CI again.

- floorplan: add `set_dont_use` before `repair_design`

If one uses `RESYNTH_TIMING_RECOVER` it used cells that we do not want to use during `repair_design` and introduced them to the design.

- cts: move `set_dont_use` before `repair_clock_inverters`

Same issue as before `repair_clock_inverters` cloud introduce cells we dont want to use.

- asap7: update to `asap7` `v28` + adding super low threshold option

Updating `.lib`, `.lef`, `.gds` for asap7 and `config.mk` to newest version.
GIthub cannot render this commit.

Should fix all these issues:

> ### There are some fixes in the newer version:
> 1. ICG lib with "clock gating function and state table" has been fixed. [ICG cells throw an error in library compiler The-OpenROAD-Project/asap7#3](https://github.com/The-OpenROAD-Project/asap7/issues/3)
>    Edit: ICG*DC* cells with incorrect width has been fixed. [ICG*DC* cells have incorrect width The-OpenROAD-Project/asap7#12](https://github.com/The-OpenROAD-Project/asap7/issues/12)
> 2. Large ASNYC FF delay has been fixed. [Wrong timing values (1e31) for ASYNC_DFFHx1_ASAP7_75t_R in the sc7p5t_SEQ_RVT_SS_nldm_201020 library The-OpenROAD-Project/asap7#9](https://github.com/The-OpenROAD-Project/asap7/issues/9)
> 3. Multi-VT GDS files missing has been fixed.

- global_route: remove deprecated option `-report_violating_nets`

- asap7: remove unused `yosys` blackbox files

Cleanup of the `.blackbox.v` files and references for `asap7` as we use `.lib` files

- asap7: allow with `v28` working clock gating cells `ICG*`

Allow ICG* cells as they have been fixed for version 28.

- asap7: make `CTS_BUF_DISTANCE` editable via parent config

Just to allow for more flexibility same as in other techs.

Now we come to the more opinionated commits. Which I am also very happy to discuss.

- global_route: add `MIN_CLOCK_ROUTING_LAYER` + to `asap7` config

This is actually an integration of @maliberty changes to this pull request https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/564.

- asap7: adding `fastroute.tcl` to make larger design route

This is an opinionated `fastroute.tcl` file for asap7. I do run a bigger design as we have currently as designs for ASAP7. And without this fastroute script it hangs indefinitly on  [INFO GRT-0103] Extra Run for hard benchmark. This `fastroute.tcl` fixes it. But I first want to see what CI thinks of it :-).

### CODE REVIEW

**Comment by joennlae** [comment]
The security scan fails because I added the new library files for asap7 v28 from here https://github.com/The-OpenROAD-Project/asap7.

**Comment by joennlae** [comment]
Things still left todo:

- [x] `fastroute.tcl` does not work for small designs
- [x] final gds generation fix
- [x] buffer cells, tapcells, fill cells for low Vth and super low Vth

**Comment by joennlae** [comment]
Would close https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/issues/563

**Comment by joennlae** [comment]
Includes https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/564

**Comment by rovinski** [comment]
I wonder if `set_dont_use $::env(DONT_USE_CELLS)` should just be added to `load.tcl`. I can't think of an instance where we would want to purposefully use dont_use cells.

Also, I am unsure about adding different VTs. OpenROAD does not have any notion of VTs or power-based optimization right now. It would likely use as many LVT cells as possible purely because timing is better.

**Comment by joennlae** [comment]
@rovinski I agree with you :-).  I was also thinking about it but I saw that there where a lot of custom usage of `set_dont_use $::env(DONT_USE_CELLS)` and I did not want to make such a drastic change to all the flows. But I of course can put that in to `load.tcl` as I also believe it would be the correct place.

Regarding the multi-vth. I explicitly select only the cells of the specified threshold. So for ASAP7 there are three options:

* default -> `RVT` (as before)
* `ASAP7_USELVT` -> `LVT`
* `ASAP7_USESLVT` -> `SLVT`

**Comment by joennlae** [comment]
We do have some regressions but I am not sure why. Could be that they changed something in the library. They do not provide any information on that in the git repo.

asap7 aes

[INFO] Tightening rule synth__design__instance__area__stdcell from 2576 to 1918.
[INFO] Tightening rule placeopt__design__instance__area from 2879 to 2057.
[INFO] Tightening rule placeopt__design__instance__count__stdcell from 25423 to 17932.
[INFO] Tightening rule cts__clock__skew__setup from 17.46 to 14.06.
[INFO] Tightening rule cts__clock__skew__hold from 17.46 to 14.06.
[INFO] Tightening rule cts__timing__setup__ws from -124.94 to -124.68.
[INFO] Updating failing rule cts__timing__setup__ws__pre_repair from -166.4 to -366.18.
[INFO] Updating failing rule cts__timing__setup__ws__post_repair from -166.4 to -366.18.
[INFO] Tightening rule cts__design__instance__count__setup_buffer from 386 to 311.
[INFO] Updating failing rule globalroute__timing__clock__slack from -35.7 to -63.19.
[INFO] Updating failing rule globalroute__timing__setup__ws from -35.7 to -63.19.
[INFO] Tightening rule detailedroute__route__wirelength from 116087 to 80674.
[INFO] Updating failing rule finish__timing__setup__ws from 0.0 to -31.82.
[INFO] Tightening rule finish__design__instance__area from 3035 to 2213.
[INFO] Tightening rule finish__timing__drv__max_slew_limit from -0.48 to -0.2.

asap7 ethmac

[INFO] Tightening rule synth__design__instance__area__stdcell from 8662 to 8647.
[INFO] Updating failing rule cts__clock__skew__setup from 174.41 to 229.55.
[INFO] Updating failing rule cts__clock__skew__hold from 174.41 to 229.55.
[INFO] Updating failing rule cts__design__instance__count__hold_buffer from 12 to 28.
[INFO] Updating failing rule globalroute__timing__clock__slack from -66.22 to -124.33.
[INFO] Updating failing rule globalroute__timing__setup__ws from -66.22 to -124.33.
[INFO] Tightening rule detailedroute__route__wirelength from 255391 to 254781.
[INFO] Updating failing rule finish__timing__setup__ws from -104.85 to -207.81.
[INFO] Updating failing rule finish__timing__drv__max_slew_limit from -0.2 to -1.3.
[INFO] Updating failing rule finish__timing__wns_percent_delay from -10.0 to -25.04.

asap7 gcd

[INFO] Tightening rule synth__design__instance__area__stdcell from 44 to 40.
[INFO] Tightening rule placeopt__design__instance__area from 51 to 48.
[INFO] Tightening rule placeopt__design__instance__count__stdcell from 514 to 467.
[INFO] Updating failing rule cts__clock__skew__setup from 1.87 to 3.91.
[INFO] Updating failing rule cts__clock__skew__hold from 1.87 to 3.91.
[INFO] Tightening rule cts__timing__setup__ws from -150.09 to -145.67.
[INFO] Tightening rule cts__timing__setup__ws__pre_repair from -141.79 to -138.36.
[INFO] Tightening rule cts__timing__setup__ws__post_repair from -141.79 to -138.36.
[INFO] Tightening rule detailedroute__route__wirelength from 1378 to 1304.
[INFO] Tightening rule finish__design__instance__area from 54 to 52.

asap7 ibex

[INFO] Tightening rule placeopt__design__instance__count__stdcell from 22555 to 22228.
[INFO] Tightening rule cts__clock__skew__setup from 273.14 to 220.9.
[INFO] Tightening rule cts__clock__skew__hold from 273.0 to 220.67.
[INFO] Updating failing rule cts__design__instance__count__setup_buffer from 16 to 42.
[INFO] Tightening rule cts__design__instance__count__hold_buffer from 36 to 10.
[INFO] Tightening rule detailedroute__route__wirelength from 110797 to 106389.
[INFO] Updating failing rule finish__timing__setup__ws from 0.0 to -101.5.
[INFO] Tightening rule finish__design__instance__area from 2746 to 2740.
[INFO] Tightening rule finish__timing__drv__setup_violation_count from 11 to 10.

asap7 jpeg

[INFO] Tightening rule synth__design__instance__area__stdcell from 7265 to 7234.
[INFO] Tightening rule placeopt__design__instance__area from 7580 to 7541.
[INFO] Tightening rule placeopt__design__instance__count__stdcell from 63238 to 62735.
[INFO] Tightening rule cts__clock__skew__setup from 76.95 to 69.51.
[INFO] Tightening rule cts__clock__skew__hold from 76.95 to 69.51.
[INFO] Tightening rule cts__timing__setup__ws from -273.77 to -273.51.
[INFO] Updating failing rule cts__design__instance__count__setup_buffer from 79 to 158.
[INFO] Updating failing rule globalroute__timing__clock__slack from -71.37 to -255.43.
[INFO] Updating failing rule globalroute__timing__setup__ws from -71.37 to -255.43.
[INFO] Updating failing rule finish__timing__setup__ws from 0.0 to -290.5.
[INFO] Tightening rule finish__design__instance__area from 7608 to 7578.
[INFO] Updating failing rule finish__timing__wns_percent_delay from -10.0 to -28.65.

asap7 sha3

[INFO] Tightening rule cts__timing__setup__ws__pre_repair from -498.77 to -364.01.
[INFO] Tightening rule cts__timing__setup__ws__post_repair from -498.77 to -364.01.
[INFO] Tightening rule detailedroute__route__wirelength from 72254 to 70743.
[INFO] Updating failing rule finish__timing__setup__ws from -38.72 to -150.03.
[INFO] Updating failing rule finish__timing__drv__max_slew_limit from -0.51 to -1.08.
[INFO] Updating failing rule finish__timing__wns_percent_delay from -11.26 to -30.07.

asap7 uart

[INFO] Tightening rule synth__design__instance__area__stdcell from 136 to 80.
[INFO] Tightening rule placeopt__design__instance__area from 94 to 88.
[INFO] Tightening rule placeopt__design__instance__count__stdcell from 827 to 762.
[INFO] Tightening rule cts__clock__skew__setup from 31.89 to 6.44.
[INFO] Tightening rule cts__clock__skew__hold from 31.89 to 6.44.
[INFO] Tightening rule cts__design__instance__count__hold_buffer from 11 to 10.
[INFO] Tightening rule globalroute__timing__clock__slack from -56.86 to -53.88.
[INFO] Tightening rule globalroute__timing__setup__ws from -56.87 to -53.89.
[INFO] Tightening rule detailedroute__route__wirelength from 1901 to 1722.
[INFO] Tightening rule finish__design__instance__area from 126 to 95.

**Comment by maliberty** [comment]
This PR is too large and has become unreviewable on GH:
image

Please separate out the v28 large file update from all your other changes.  This should become two PRs.

**Comment by maliberty** [comment]
(or even more than two as your have bundled too many changes into one PR and the degradation of results can't be traced)

**Pull request closed without merging**
