### PR TITLE
[DO NOT REVIEW] CTS improvements CI test

### PR DESCRIPTION
**Pull request by oharboe**

### CODE REVIEW

**Comment by oharboe** [comment]
@precisionmoon FYI, enabling new CTS and taking it for a spin to see what happens.

**Comment by oharboe** [comment]
@vvbandeira I want to test a draft pull request + some additional changes on latest master ORFS. Is that not allowed?

**Comment by oharboe** [comment]
@precisionmoon mock-array will need some adjustments, but other than that the new CTS feature could be enabled by default.

**Comment by precisionmoon** [comment]
> @precisionmoon mock-array will need some adjustments, but other than that the new CTS feature could be enabled by default.

Thank you very much for your help with validation.

**Pull request closed without merging**
