### PR TITLE
Updated util/genMetrics.py

### PR DESCRIPTION
**Pull request by yathAg**
When export `SYNTH_HIERARCHICAL = `1 is defined in the `config.mk` for the hierarchical synthesis, the format of the generated synth_stat is different.

[synth_stat_flat.txt](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/files/11017803/synth_stat_flat.txt)
[synth_stat_hier.txt](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/files/11017804/synth_stat_hier.txt)

This leads to the `genMetrics.py` copying the wrong core area, which is arbitrarily small.

Further, when `genRuleFile.py` is executed using `make update_ok`, the `synth__design__instance__area__stdcell` variable is rounded to zero resulting in an incorrect metadata file.

The updated `genMetrics.py` file accounts for flat synthesis and hierarchical synthesis, reporting the correct area data.

The metadata and rule files for `asap7/riscv32i` are also updated with drc clean and 0wns design metrics to account for the wrong values of `synth__design__instance__area__stdcell`

### CODE REVIEW

**Review by vvbandeira — CHANGES_REQUESTED** [review]
@yathAg, the metrics changes and the python script looks good. I see you already updated the `asap7/riscv32i`, but you will need to update the following designs with `make update_ok` to reflect the changes:

```
asap7/swerv_wrapper
nangate45/ariane136
nangate45/black_parrot
nangate45/bp_be_top
nangate45/bp_fe_top
nangate45/bp_multi_top
nangate45/swerv_wrapper
sky130hd_fakestack/ariane136
```

I will take care of updating the private PDK designs that have `SYNTH_HIERARCHICAL = 1`.

BTW, you do not need to run them locally. You can download the `tar.gz` files from the CI [here](https://jenkins.openroad.tools/blue/organizations/jenkins/OpenROAD-flow-scripts-Public%2Fpublic_tests_all-pr/detail/PR-900-merge/2/artifacts) and use them to update the metrics.

**Comment by yathAg** [comment]
For the designs in  `sky130hd_fakestack` the `metadata-base-ok.json` and `rules-base.json` do not exist, and hence I haven't updated 
`sky130hd_fakestack/ariane136`


I have updated 
```
asap7/swerv_wrapper
nangate45/ariane136
nangate45/black_parrot
nangate45/bp_be_top
nangate45/bp_fe_top
nangate45/bp_multi_top
nangate45/swerv_wrapper
```

**Comment by vijayank88** [comment]
@yathAg 
Check `microwat` design metrics. still it fails.

**Comment by maliberty** [comment]
microwatt is failing on master due to another issue.  I'm going to update it today.

**Comment by vvbandeira** [comment]
> The metadata and rule files for `asap7/riscv32i` are also updated with drc clean and 0wns design metrics to account for the wrong values of `synth__design__instance__area__stdcell`

Is this the reason for the density and clk period change? @maliberty thoughts? Other changes LGTM.

**Comment by yathAg** [comment]
Yes those were the reasons to change the density and clk period.

**Review by yathAg — COMMENTED** [review]
Updated Values for requested designs

**Review by maliberty — APPROVED** [review]

**Comment by maliberty** [comment]
Thanks for the fixes

**Pull request merged**
