### PR TITLE
[DO NOT MERGE] test: add an idempotency test

### PR DESCRIPTION
**Pull request by oharboe**
pile on as many options as possible that should result in identical results and run an a/b test and diff results folder.

Needs to be hooked up to CI and the existing diffs need to be fixed (or whitelisted)

### CODE REVIEW

**Comment by oharboe** [comment]
@maliberty Any idea what is going on here?

```
$ diff <(hexdump -C results/nangate45/gcd/a/6_1_merged.gds) <(hexdump -C results/nangate45/gcd/b/6_1_merged.gds) | head -n 20
2,3c2,3
< 00000010  00 13 00 0d 00 1a 07 e8  00 08 00 07 00 13 00 0d  |................|
< 00000020  00 1a 00 08 02 06 4c 49  42 00 00 14 03 05 3d 68  |......LIB.....=h|
---
> 00000010  00 13 00 0d 00 2f 07 e8  00 08 00 07 00 13 00 0d  |...../..........|
> 00000020  00 2f 00 08 02 06 4c 49  42 00 00 14 03 05 3d 68  |./....LIB.....=h|
5,6c5,6
< 00000040  05 02 07 e8 00 08 00 07  00 13 00 0d 00 1a 07 e8  |................|
< 00000050  00 08 00 07 00 13 00 0d  00 1a 00 0e 06 06 56 49  |..............VI|
---
> 00000040  05 02 07 e8 00 08 00 07  00 13 00 0d 00 2f 07 e8  |............./..|
> 00000050  00 08 00 07 00 13 00 0d  00 2f 00 0e 06 06 56 49  |........./....VI|
20,21c20,21
< 00000130  07 e8 00 08 00 07 00 13  00 0d 00 1a 07 e8 00 08  |................|
< 00000140  00 07 00 13 00 0d 00 1a  00 0e 06 06 56 49 41 5f  |............VIA_|
---
> 00000130  07 e8 00 08 00 07 00 13  00 0d 00 2f 07 e8 00 08  |.........../....|
> 00000140  00 07 00 13 00 0d 00 2f  00 0e 06 06 56 49 41 5f  |......./....VIA_|
35,36c35,36
< 00000220  00 08 00 07 00 13 00 0d  00 1a 07 e8 00 08 00 07  |................|
```

**Comment by maliberty** [comment]
Nope but you should know that gds also has time stamps in it.  You can find the format https://en.wikipedia.org/wiki/GDSII  in the External links

**Comment by oharboe** [comment]
@maliberty I think the test is ready to be merged, even if it fails. It is a encoding in code how the system is supposed to work, even if it is currently failing.

Thoughts?

**Comment by maliberty** [comment]
I'm not sure if the gds is "supposed" to be idempotent.  It would be good to trace down the diff and see if it is expected (eg timestamps).

**Pull request closed without merging**
