### PR TITLE
rtlmp: add RTLMP_ARGS consistent with global/place/cts

### PR DESCRIPTION
**Pull request by oharboe**
RTLMP has a lot of environment variables.

This change makes it possible to add and remove any current and future RTLMP argument, consistent with how this is done in global route, placement and cts.

The next step, once this is merged, would be to prune the disused RTLMP_ environment variables to reduce repetition and expose the OpenROAD interface directly through RTLMP_ARGS, rather than create an ORFS environment variable version of every current and future RTLMP argument.

https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/blob/74c112eb3ab5a3fc8c703b428aa7386bd0cb3da1/flow/scripts/global_route.tcl#L32

### CODE REVIEW

**Review by maliberty — APPROVED** [review]

**Comment by maliberty** [comment]
While I'm fine with this change, this

> The next step, once this is merged, would be to prune the disused RTLMP_ environment variables to reduce repetition and expose the OpenROAD interface directly through RTLMP_ARGS, rather than create an ORFS environment variable version of every current and future RTLMP argument.

concerns me.  It would make this inconsistent with all the other tools that present individual options.   Also the autotuner needs discrete knobs to turn so this would impair the ability to use it.  No user is required to use the options so I'm not clear of the harm.

**Comment by oharboe** [comment]
> While I'm fine with this change, this
> 
> > The next step, once this is merged, would be to prune the disused RTLMP_ environment variables to reduce repetition and expose the OpenROAD interface directly through RTLMP_ARGS, rather than create an ORFS environment variable version of every current and future RTLMP argument.
> 
> concerns me. It would make this inconsistent with all the other tools that present individual options. Also the autotuner needs discrete knobs to turn so this would impair the ability to use it. No user is required to use the options so I'm not clear of the harm.

The problem is repetition and no unit-tests. Every option has to be repeated in ORFS and documented whereas it is already documented and should be unit-tested in OpenROAD.

It is no arduous task for Autotuner to articulate a string of OpenROAD arguments and articulate it as a command line argument.

**Comment by maliberty** [comment]
Unit tests are an orthogonal concern (that I share).

What rule is there for how many arguments can have per switch vars and how many is too many?  It seems a bit arbitrary.

**Comment by oharboe** [comment]
> Unit tests are an orthogonal concern (that I share).
> 
> What rule is there for how many arguments can have per switch vars and how many is too many? It seems a bit arbitrary.

Unsure what you are asking.

Generally, I think that the role of ORFS is to make common cases w.r.t. these parameters easy and the more obscure cases possible.

**Comment by maliberty** [comment]
In detail_route.tcl we have a fair number of individual arguments but you haven't proposed to do the same there.  Is the only reason to do it in mpl2 is the number of arguments?

**Comment by oharboe** [comment]
> In detail_route.tcl we have a fair number of individual arguments but you haven't proposed to do the same there. Is the only reason to do it in mpl2 is the number of arguments?

mpl2 is newer and the parameters are added but not used, but really the same idea applies. Make ORFS thinner.

**Pull request merged**
