### PR TITLE
sky130hd missing met1/met2 MINENCLOSEDAREA rules

### PR DESCRIPTION
**Pull request by antonblanchard**

### CODE REVIEW

**Comment by antonblanchard** [comment]
I'm getting DRC errors when building a sky130hd project. Details can be found at: https://github.com/google/skywater-pdk/issues/285

**Comment by maliberty** [comment]
Is there no equivalent required for sky130hs?

**Comment by antonblanchard** [comment]
> Is there no equivalent required for sky130hs?

It seems like it should. @agorararmard @RTimothyEdwards any reason we only added the `MINENCLOSEDAREA` rules to the hd and hdll libraries?

**Comment by RTimothyEdwards** [comment]
It _is_ required for all of the libraries.  However, without direct access to update the library repositories, we patched them as needed.  We will be updating all the libraries shortly;  getting the repositories in shape to allow pull requests is coming along and is supposed to be ready in a few days.

**Comment by maliberty** [comment]
@antonblanchard would you update this PR to include hs.

**Comment by antonblanchard** [comment]
Thanks @RTimothyEdwards. @maliberty I've made the same changes to the hs library.

**Comment by maliberty** [comment]
@tspyrou merge the changes again for hs

**Comment by agorararmard** [comment]
@maliberty (cc: @antonblanchard ): Please note that the `sky130_fd_sc_hs` didn't have that problem in the source repo. Which implies that the version of the pdk used here is either **_very_** outdated or hand edited to remove the rule? 

@antonblanchard (cc: @RTimothyEdwards): I only created a patch for hd and hdll because the rule already exists in the techlef for all other libraries.

**Comment by maliberty** [comment]
@msaligane please check if we are up to date with the current skywater pdk.

**Comment by maliberty** [comment]
@msaligane is going to PR a general update to the efabless versions of the skywater pdks.  I expect that will cover this issue.

**Review by msaligane — APPROVED** [review]
LGTM!
The upstream from google/skywater is not updated it seems. See my comment here: https://github.com/google/skywater-pdk/issues/285#issuecomment-810705537

**Pull request merged**
