### PR TITLE
sky130hd-microwatt: increase halos/channels for mpl2 flow & turn off boundary penalty

### PR DESCRIPTION
**Pull request by AcKoucher**
This should unblock either the boundary penalty fix for mpl2 and the gpl routability changes.

### CODE REVIEW

**Comment by AcKoucher** [comment]
Running locally with master showed no metrics failures.

**Comment by eder-matheus** [comment]
@maliberty Arthur made this change because the halos were too small, considering the size of the die. I believe microwatt was on the edge of failing during the global routing with high congestion. Changing the halos creates more space for the routing near the macros. Note that the previous halo value was a default value for all designs in the PDK.

@AcKoucher, could you paste a figure showing the new macro placement after this change?

**Comment by maliberty** [comment]
I restarted pr-merge as it looks like a network failure

**Comment by AcKoucher** [comment]
image

**Comment by AcKoucher** [comment]
I opened [#4867](https://github.com/The-OpenROAD-Project/OpenROAD/issues/4867) to investigate how to improve results and run time for this design. As discussed in R&D synch, it's a challenging case for mpl2 due to large macros, pins in all boundaries, few metal layers...

**Review by eder-matheus — APPROVED** [review]

**Pull request merged**
