### PR TITLE
Printing a list of DONT_USE CELLS.

### PR DESCRIPTION
**Pull request by socclosure**
Fix for the issue
https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/issues/1429

### CODE REVIEW

**Comment by rovinski** [comment]
This seems to just be printing the environment variable? Is that useful?

**Comment by socclosure** [comment]
It is not unix environment which can be viewed using echo while it can be accessed in the tool. In issue # 1429 user has requested to print DONT_USE cell list in the log file which is being implemented int this PR.

**Comment by rovinski** [comment]
I have a few issues with this:

1. This can already be done with the `make print-%` rule pattern:
https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/blob/bb190447797192a1bc2c43db81d5cb568513dd59/flow/Makefile#L1125-L1127
So running `make print-DONT_USE_CELLS` will provide this result.
2. This doesn't actually print cells that aren't used, it only prints each item in the variable. The item in the variable may not match any cells in the lib (for example, `INV_x1` won't match `INV_X1`, the former may not actually exist in the library).
3. It will also not resolve any wildcards, so it would print `INV_*` as the dont_use cell rather than all of `INV_X1`, `INV_X2`, `INV_X4`, ...
4. As stated in https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/issues/1429#issuecomment-2296425056 this information technically already shows in the log

I think this would be more useful if it actually used a `get_cells` call to resolve the cell names, and also formatted it in a list

**Comment by socclosure** [comment]
@rovinski @maliberty @vijayank88 

I need your help for the requirement or need of the ISSUE_1429.
Please find my inline response of last comment.

> I have a few issues with this:
> 
> 1. This can already be done with the `make print-%` rule pattern:
>    https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/blob/bb190447797192a1bc2c43db81d5cb568513dd59/flow/Makefile#L1125-L1127
>    
>    So running `make print-DONT_USE_CELLS` will provide this result.

**### Jignesh: When I execute "make print-DONT_USE_CELLS", it does not display any list. It's possible that I may need to set or change a variable. If the user agrees with this approach, then we can close this issue without checking in any code changes and we can discard this pull request.**

> 2. This doesn't actually print cells that aren't used, it only prints each item in the variable. The item in the variable may not match any cells in the lib (for example, `INV_x1` won't match `INV_X1`, the former may not actually exist in the library).

** Jignesh: Correct. The request is to print setting of "DONT_USE_CELLS". If any value of "DONT_USE_CELLS" is incorrect then it should be informed by Synthesis tool when it will apply that list. **

> 3. It will also not resolve any wildcards, so it would print `INV_*` as the dont_use cell rather than all of `INV_X1`, `INV_X2`, `INV_X4`, ...

** Jignesh: Same feedback as point 2 **

> 4. As stated in [Create 0_prep.log to view logs related to design flow preparation #1429 (comment)](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/issues/1429#issuecomment-2296425056) this information technically already shows in the log
> 
> I think this would be more useful if it actually used a `get_cells` call to resolve the cell names, and also formatted it in a list

** Jignesh:  If user can clarify more on requirement, then it will be better my interpretation from the comment is that user can see merge.lib in log file and a list of "DONT_USE_CELL" not actual cells still need to be print in Yosys log file. **

Please guide on what need to be done for ISSUE_1496. If code change is not required, then we can discard the PR and close the ISSUE.

**Comment by rovinski** [comment]
According to https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/issues/1429#issuecomment-2296425056 the current state is good enough, so I would recommend closing the issue and this PR.

**Comment by socclosure** [comment]
Thanks @rovinski for recommending.
I will discard the PR.
@vijayank88 / @maliberty 
Please close the ISSUE 1429 or give your input.

**Comment by socclosure** [comment]
I am closing this PR.

**Pull request closed without merging**
