### PR TITLE
variables: REMOVE_ABC_BUFFERS is deprecated

### PR DESCRIPTION
**Pull request by oharboe**

### CODE REVIEW

**Comment by oharboe** [comment]
@maliberty I am making some guesses here based on discussions, thought documenting would be helpful.

**Comment by oharboe** [comment]
@maliberty Comments?

**Comment by maliberty** [comment]
Do you need to regenerate the docs?

**Comment by oharboe** [comment]
> Do you need to regenerate the docs?

That will be picked up next time someone regenerates them. Good 'nuf?

**Comment by maliberty** [comment]
Why wait for someone else to do it?

**Comment by oharboe** [comment]
> Why wait for someone else to do it?

There would have been several merge conflicts if I added FlowVariables.md updates to this PR.

Updating variables.yaml and updating FlowVariables.md are separate concerns, best done in separate PRs to avoid false merge conflicts.

**Comment by maliberty** [comment]
I have no idea when that next person will happen to do it.  I would rather see this as one update even if other PRs need to merge in the changes.  Its no different from any other PR that needs a merge.

**Comment by oharboe** [comment]
> I have no idea when that next person will happen to do it.  I would rather see this as one update even if other PRs need to merge in the changes.  Its no different from any other PR that needs a merge.

There is a difference: this PR does not update some automatically generate docs.

There was some CI work in progress to make this moot: automatically run generatedocs.py as needed to automatically create PRs to do docs update.

**Comment by oharboe** [comment]
@maliberty regenerated, should be good to merge.

**Review by maliberty — APPROVED** [review]

**Pull request merged**
