### PR TITLE
swerv_wrapper ASAP7 test case added

### PR DESCRIPTION
**Pull request by vijayank88**
`swerv_wrapper` implemented with ASAP7 platform.

### CODE REVIEW

**Review by vvbandeira — CHANGES_REQUESTED** [review]
please add the design to CI

**Comment by vijayank88** [comment]
@vvbandeira 
This design is already available in sky130/nangate45. In ASAP7 platform run time is 2Hr 30Mins. Is that ok to add in CI?
If yes mean need to add both public and nightly jenkins or public CI alone is enough?

**Comment by vvbandeira** [comment]
Currently, the PR pipeline is taking nearly 2h30, so it should be fine to add to both nightly and all tests.

All designs need to be in at least one pipeline; for large designs, we usually add to the nightly since it will not slow down the PR process.

**Review by maliberty — APPROVED** [review]
This is fine but you'll need to resolve the merge conflict

**Comment by vijayank88** [comment]
@vvbandeira 
Conflicts got resolved. Can you please check once and merge it?

**Review by vvbandeira — CHANGES_REQUESTED** [review]
> This design is already available in sky130/nangate45. In ASAP7 platform run time is 2Hr 30Mins.

image

This is longer than expected. Please only enable the design in the Nightly build.

**Review by vvbandeira — APPROVED** [review]

**Pull request merged**
