### PR TITLE
ASAP7: `v28` lib update + changes (merge via cli)

### PR DESCRIPTION
**Pull request by joennlae**
- floorplan: add `set_dont_use` before `repair_design`
- cts: move `set_dont_use` before `repair_clock_inverters`
- asap7: update to `v28` `.lef` files
- asap7: update to `v28` `.gds` files
- asap7: update to `v28` adaption of `config.mk` file
- global_route: remove depreceated option `-report_violating_nets`
- asap7: remove unused `yosys` blackbox files
- asap7: allow with `v28` working clock gating cells `ICG*`
- asap7: make `CTS_BUF_DISTANCE` editable via parent config
- global_route: add `MIN_CLOCK_ROUTING_LAYER` + to `asap7` config
- asap7: make tapcell work with low and super low threshold
- asap7: use correct gds, buffer, fille for corresponding vth
- asap7: update `yosys` adder, clkgate, latch and dff for multi-vt
- asap7: fix `.lef` file according to upstream repo
- asap7: revert back to one buffer
- asap7: remove `4x` gds + lef
- asap7: remove `4x` option from `asap7`
- scripts: move `set_dont_use` into `load.tcl` and remove other refs
- asap7: update to `v28` `.lib` files
- asap7: update `metadata` after `v28` lib upgrade Signed-off-by: Jannis Schönleber <joennlae@gmail.com>
- asap7: apply changes from `review`

### CODE REVIEW

**Comment by oharboe** [comment]
@joennlae FYI, I added a single commit on top of this pull request to update the openlane folder: https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/644/commits/d07ede1f8b740b699f82cf2791ad89a06c50599b

There are some comments that really should go on this pull request: https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/644#issuecomment-1317329887

**Comment by joennlae** [comment]
OK :-) For me, the problem is that the tests pass locally with all the newest versions (Openroad, etc.). So I cannot reproduce the CI errors. I would happily help fix it, but it is nearly impossible to debug.

**Comment by maliberty** [comment]
Are you running 'make finish metadata' to check the metrics as well as run the design?

**Comment by joennlae** [comment]
> Are you running 'make finish metadata' to check the metrics as well as run the design?

I did run `make update_ok`. I am running `make finish metadata` now :-) Thank you for the input.

**Comment by maliberty** [comment]
I'm trying to figure out how to bring this to a successful conclusion. There are too many PRs and changes intermixed still. I have no idea the source of the failures. Can I ask for the following:

- One PR that just adds the new files but does nothing else (large but easy to approve as no functional change)
- One PR that just switches from the old (27) files to the new (28) files with no other configuration changes. This will isolate any issues with the new cells (small and targeted)
- Follow on PRs that make a single change whose QOR impact can be evaluated (small and targeted)

**Comment by joennlae** [comment]
Sorry for going radio silent. I figured out the error with the CI. My nightly auto build of OpenROAD has been failing for a few weeks (and I didn't notice, and because of that, I updated the metadata with the wrong information).

So last week, I started to update our internal build (we can not use the build scripts because there is no sudo ...); I was fixing the missing `<limits>` headers in parallel on Friday :-) But anyway, I will start working on that on Thursday (hopefully) and can then split the PRs, but I cannot promise a final delivery yet :-).

**Comment by maliberty** [comment]
See comments in https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/579

**Pull request closed without merging**
