### PR TITLE
Adding total elapsed time to flow/util/genElapsedTime.py

### PR DESCRIPTION
**Pull request by gudeh**

### CODE REVIEW

**Comment by maliberty** [comment]
Please remember to sign your commits (git commit -s).  I see you signed the first one so I will squash this into one commit when it is ready to merge.

**Review by maliberty — APPROVED** [review]

**Comment by maliberty** [comment]
Thanks for the contribution

**Comment by oharboe** [comment]
@gudeh Nice!

**Comment by gudeh** [comment]
Feels great to be able to help guys! I hope I can continue to contribute to further improvements. Please feel free to point out any additional issues I can help with.

**Comment by oharboe** [comment]
> Feels great to be able to help guys! I hope I can continue to contribute to further improvements. Please feel free to point out any additional issues I can help with.

Lots of things to do... If you are feeling extremely adventerous, fancy trying out a wafer thin Bazel layer on top of ORFS? :-)

**Comment by gudeh** [comment]
That is quite a large jump! haha
I see the discussion you created at #1139.

**Pull request merged**
