### PR TITLE
Update ASAP7 RC layer estimates

### PR DESCRIPTION
**Pull request by antonblanchard**
Signed-off-by: Anton Blanchard <anton@linux.ibm.com>

### CODE REVIEW

**Comment by maliberty** [comment]
Please provide a description of how these values were generated.

**Comment by antonblanchard** [comment]
I need to recreate the estimates after https://github.com/The-OpenROAD-Project/OpenROAD/issues/2277 is fixed

**Comment by maliberty** [comment]
@antonblanchard still relevant?

**Comment by maliberty** [comment]
Stale

**Pull request closed without merging**
