### PR TITLE
Fix ASAP7 VIA resistances

### PR DESCRIPTION
**Pull request by antonblanchard**
While it is an academic PDK, having the same via resistance for all
layers is not realistic. The updated values come from one of the
papers on the ASAP7 PDK.

Signed-off-by: Anton Blanchard <anton@linux.ibm.com>

### CODE REVIEW

**Comment by maliberty** [comment]
What paper did you take the values from?

You can update the metrics with the update_ok target for the failing design.

**Comment by antonblanchard** [comment]
> What paper did you take the values from?

I found them in here: https://pages.hmc.edu/harris/research/asap7.pdf

**Comment by maliberty** [comment]
The paper reference makes sense.  You have conflicts to resolve

**Comment by antonblanchard** [comment]
@maliberty conflicts resolved, and the CI passes.

**Review by maliberty — APPROVED** [review]

**Pull request merged**
