### PR TITLE
asap7: updated openlane folder as part of asap7 upgrade

### PR DESCRIPTION
**Pull request by oharboe**
This pull request has a single commit on top of #638 to update the openlane folder, seems to work, but needs https://github.com/The-OpenROAD-Project/OpenLane/issues/1486 fixed before it can be fully tested.

Signed-off-by: Øyvind Harboe <oyvind.harboe@zylin.com>

### CODE REVIEW

**Comment by maliberty** [comment]
How is this supposed to work when the files don't exist in ORFS?

**Comment by oharboe** [comment]
> How is this supposed to work when the files don't exist in ORFS?

I tried to fix this by copying files over from https://github.com/The-OpenROAD-Project/asap7

**Comment by rovinski** [comment]
I think this is mostly a subset of #638 and #579?

**Comment by oharboe** [comment]
> I think this is mostly a subset of #638 and #579?

Ah. Rather a lot more going on in those two pull requests...

How can I test #638 and #579 with OpenLane?

**Comment by maliberty** [comment]
There are a number of CI failures that need investigating.  I see this isn't a pure upgrade as you have
```
export MIN_CLOCK_ROUTING_LAYER = M4
```
which might be good but isn't about upgrading to 28.  Likewise with removing *ICG* from DONT_USE_CELLS.  I'm ok with keeping these but you need to establish that they aren't causing degradations in QOR.

**Comment by oharboe** [comment]
> There are a number of CI failures that need investigating. I see this isn't a pure upgrade as you have
> 
> ```
> export MIN_CLOCK_ROUTING_LAYER = M4
> ```
> 
> which might be good but isn't about upgrading to 28. Likewise with removing _ICG_ from DONT_USE_CELLS. I'm ok with keeping these but you need to establish that they aren't causing degradations in QOR.

This is a draft pull request on top of #638 where I only one commit: https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/644/commits/d07ede1f8b740b699f82cf2791ad89a06c50599b.

Your comments should go on #638

**Comment by maliberty** [comment]
I'm trying to figure out how to bring this to a successful conclusion.  There are too many PRs and changes intermixed still.  I have no idea the source of the failures.  Can I ask for the following:

- One PR that just adds the new files but does nothing else (large but easy to approve as no functional change)
- One PR that just switches from the old (27) files to the new (28) files with no other configuration changes.  This will isolate any issues with the new cells (small and targeted)
- Follow on PRs that make a single change whose QOR impact can be evaluated (small and targeted)

**Comment by rovinski** [comment]
@maliberty this isn't the OP of the changes, that was @joennlae

**Comment by maliberty** [comment]
@rovinski OP?

**Comment by rovinski** [comment]
The person who originally made the changes in the PR. I think this one is just grabbing those same changes.

**Comment by maliberty** [comment]
@rovinski I see - I'll put the comment in #638 then

**Comment by oharboe** [comment]
Easily done when ASAP7 is upgraded.

**Pull request closed without merging**
