### PR TITLE
Allow asap7 x1 cells

### PR DESCRIPTION
**Pull request by antonblanchard**
Signed-off-by: Anton Blanchard <anton@linux.ibm.com>

### CODE REVIEW

**Comment by maliberty** [comment]
Needs DCO

**Comment by antonblanchard** [comment]
I tried to work out why x1 cells were being excluded. The initial commit of the ASAP7 support suggests it was because of pin access issues:

```
+# Cells with strength <= 1 have difficult pin access
+export DONT_USE_CELLS += OAI21xp* AOI21xp* OAI21x1* AOI21x1* A2O1A1O1Ixp* A2O1A1O1Ix1* MAJIxp* NAND2x1* AO21x1* AOI22xp* AOI22x1* AOI211xp* AOI31xp* A2O1A1Ixp* HB4xp* HB3xp* HB2xp* HB1xp*
```

The pin access code has improved, so this has hopefully been resolved.

@jjcherry56 @maliberty I stumbled on this because I have a gate level design that uses x1 strength cells, and the resizer was refusing to do gate upsizing during setup repair. Since they are marked `dont_use` in the liberty file, the resizer doesn't have any knowledge of the cell and cant find equivalent ones.

I did wonder if the resizer should know enough about the cell so that it can still upsize `dont_use` cells, but ultimately we just shouldn't exclude them in the first place.

I wasn't completely sure what the x1p and xp cells are, so I left them alone. They appear to be the percentage of diffusion (p33, p67 etc)

**Comment by maliberty** [comment]
How did you get a dont_use cell in your netlist in the first place?

**Comment by antonblanchard** [comment]
> How did you get a dont_use cell in your netlist in the first place?

Not in the netlist, in the liberty file:

```
  cell (INVx1_ASAP7_75t_R) {
    dont_use : true;
```

**Comment by jjcherry56** [comment]
That comment "# Cells with strength <= 1 have difficult pin access" is copied out of the gf12 config file.
I seriously doubt it is based on any evidence.

**Comment by maliberty** [comment]
There were issues on another pdk and since then I think it has just become tradition

**Comment by maliberty** [comment]
re: "I stumbled on this because I have a gate level design that uses x1 strength cells"  how did they get in your gate level design?  Was it produced by another tool?

**Comment by antonblanchard** [comment]
> re: "I stumbled on this because I have a gate level design that uses x1 strength cells" how did they get in your gate level design? Was it produced by another tool?

It was produced by another tool, one which emits a gate level representation of adders and multipliers. I gave it x1 strength cells, and it took a while to realise they weren't getting resized.

**Review by vvbandeira — DISMISSED** [review]

**Comment by vvbandeira** [comment]
@antonblanchard could you force push the same commit again to your branch? I am not sure why, but the GHA scan is stuck at pending. If this does not work, could you start a new PR?

**Review by maliberty — APPROVED** [review]

**Comment by maliberty** [comment]
You might want to merge https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/520 into this branch to make sure there is no combined effect.

**Comment by antonblanchard** [comment]
> You might want to merge #520 into this branch to make sure there is no combined effect.

Looks to have passed the CI with #520

**Pull request merged**
