### PR TITLE
utils: make issue filter out variable

### LINKED ISSUE #798: Issue with test case generation
### Subject

[Flow] for any util, flow Makefile, or flow script issues.

### Describe the bug

`make floorplan_issue` generates executable shell script with test case.
But if I run the test case with ` ./run-me-gcd-nangate45-base.sh` it fails to find `Error: floorplan.tcl, 2 can't read "::env(SCRIPTS_DIR)": no such variable`

But the issue is in shell script missing `"` close quote in one of configuration variable in 
`vars-gcd-nangate45-base.sh` as `export bash -c " unset BLOCKS && unset ADDITIONAL_LEFS && unset ADDITIONAL_GDS && unset ADDITIONAL_LIBS && unset DONT_USE_SC_LIB && unset LIB_FILES && unset MACRO_PLACEMENT && make \"DESIGN_CONFIG='\" generate_abstract'`

### Expected Behavior

Add missing `"` in following variable:
`export bash -c " unset BLOCKS && unset ADDITIONAL_LEFS && unset ADDITIONAL_GDS && unset ADDITIONAL_LIBS && unset DONT_USE_SC_LIB && unset LIB_FILES && unset MACRO_PLACEMENT && make \"DESIGN_CONFIG='\" generate_abstract'"`

### Environment

```shell
With Latest ORFS master checked
```

### To Reproduce

Run any built in designs. Then run
`make floorplan_issue`
If try to execute the test case locally it will fail.
`./run-me-gcd-nangate45-base.sh`

### Relevant log output

```shell
./run-me-gcd-nangate45-base.sh 
vars-gcd-nangate45-base.sh: line 51: unexpected EOF while looking for matching `"'
vars-gcd-nangate45-base.sh: line 109: syntax error: unexpected end of file
OpenROAD v2.0-6566-g970f89da6 
This program is licensed under the BSD-3 license. See the LICENSE file for details.
Components of this program may be licensed under more restrictive licenses which must be honored.
Error: floorplan.tcl, 2 can't read "::env(SCRIPTS_DIR)": no such variable
openroad>
```

### Screenshots

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by habibayassin**
Signed-off-by: habibayassin <habibayassin@aucegypt.edu>

### CODE REVIEW

**Comment by vvbandeira** [comment]
@oharboe is the `GENERATE_ABSTRACT_RULE` variable required to have a complete `*_issue.tar.gz` file or can we exclude as this PR proposes?

**Comment by oharboe** [comment]
> @oharboe is the `GENERATE_ABSTRACT_RULE` variable required to have a complete `*_issue.tar.gz` file or can we exclude as this PR proposes?

I dont know the details, but for sure I am using submacros in designs/asap7/mock-array-big

**Comment by vvbandeira** [comment]
> I dont know the details, but for sure I am using submacros in designs/asap7/mock-array-big

The `make *_issue` command creates a `*_issue.tar.gz` file to share reproducible testcases. The question is if the variable `GENERATE_ABSTRACT_RULE` needs to be on the tar file scripts in order to be complete.

@habibayassin can you run this design and try the `make final_report_issue`? If both the straight run and the run from the make issue are the same, I think we can go ahead with the PR.

**Comment by habibayassin** [comment]
> > I dont know the details, but for sure I am using submacros in designs/asap7/mock-array-big
> 
> The `make *_issue` command creates a `*_issue.tar.gz` file to share reproducible testcases. The question is if the variable `GENERATE_ABSTRACT_RULE` needs to be on the tar file scripts in order to be complete.
> 
> @habibayassin can you run this design and try the `make final_report_issue`? If both the straight run and the run from the make issue are the same, I think we can go ahead with the PR.

The output of running from the make issue:
```OpenROAD v2.0-6709-g6d4b59903 
This program is licensed under the BSD-3 license. See the LICENSE file for details.
Components of this program may be licensed under more restrictive licenses which must be honored.
[WARNING STA-0164] ./platforms/asap7/lib/asap7sc7p5t_SIMPLE_RVT_FF_nldm_211120.lib.gz line 13178, timing group from output port.
[WARNING STA-0164] ./platforms/asap7/lib/asap7sc7p5t_SIMPLE_RVT_FF_nldm_211120.lib.gz line 13211, timing group from output port.
[WARNING STA-0164] ./platforms/asap7/lib/asap7sc7p5t_SIMPLE_RVT_FF_nldm_211120.lib.gz line 13244, timing group from output port.
[WARNING STA-0164] ./platforms/asap7/lib/asap7sc7p5t_SIMPLE_RVT_FF_nldm_211120.lib.gz line 13277, timing group from output port.
[WARNING STA-0164] ./platforms/asap7/lib/asap7sc7p5t_SIMPLE_RVT_FF_nldm_211120.lib.gz line 13310, timing group from output port.
[WARNING STA-0164] ./platforms/asap7/lib/asap7sc7p5t_SIMPLE_RVT_FF_nldm_211120.lib.gz line 13343, timing group from output port.
[WARNING STA-0164] ./platforms/asap7/lib/asap7sc7p5t_SIMPLE_RVT_FF_nldm_211120.lib.gz line 13376, timing group from output port.
[WARNING STA-0164] ./platforms/asap7/lib/asap7sc7p5t_SIMPLE_RVT_FF_nldm_211120.lib.gz line 14772, timing group from output port.
[WARNING STA-0164] ./platforms/asap7/lib/asap7sc7p5t_SIMPLE_RVT_FF_nldm_211120.lib.gz line 14805, timing group from output port.
[WARNING STA-0164] ./platforms/asap7/lib/asap7sc7p5t_SIMPLE_RVT_FF_nldm_211120.lib.gz line 14838, timing group from output port.
[INFO] Deleted 0 routing obstructions
[INFO RCX-0431] Defined process_corner X with ext_model_index 0
[INFO RCX-0029] Defined extraction corner X
[INFO RCX-0008] extracting parasitics of MockArray ...
[INFO RCX-0435] Reading extraction model file ./platforms/asap7/rcx_patterns.rules ...
[INFO RCX-0436] RC segment generation MockArray (max_merge_res 50.0) ...
[INFO RCX-0040] Final 25425 rc segments
[INFO RCX-0439] Coupling Cap extraction MockArray ...
[INFO RCX-0440] Coupling threshhold is 0.1000 fF, coupling capacitance less than 0.1000 fF will be grounded.
[INFO RCX-0043] 52347 wires to be extracted
[INFO RCX-0442] 14% completion -- 7770 wires have been extracted
[INFO RCX-0442] 28% completion -- 14808 wires have been extracted
[INFO RCX-0442] 40% completion -- 21115 wires have been extracted
[INFO RCX-0442] 53% completion -- 28040 wires have been extracted
[INFO RCX-0442] 78% completion -- 41047 wires have been extracted
[INFO RCX-0442] 83% completion -- 43623 wires have been extracted
[INFO RCX-0442] 89% completion -- 46946 wires have been extracted
[INFO RCX-0442] 100% completion -- 52347 wires have been extracted
[INFO RCX-0045] Extract 6837 nets, 32254 rsegs, 32254 caps, 17115 ccs
[INFO RCX-0015] Finished extracting MockArray.
[INFO RCX-0016] Writing SPEF ...
[INFO RCX-0443] 6837 nets finished
[INFO RCX-0017] Finished writing SPEF ...
Error: final_report.tcl, 58 wrong # args: should be "dict for {keyVarName valueVarName} dictionary script"
```

I am not sure if the variable `GENERATE_ABSTRACT_RULE` is the issue. If so, @oharboe does the variable has to be on multiple lines and with unescaped double quotes?
```define GENERATE_ABSTRACT_RULE
# Single rule, two targets, hence the "&:", syntax
$(1) $(2) &: $(3)
    # Make sure environment variables modified in this Makefile do not leak into the sub-build
	bash -c " \
	unset BLOCKS && \
	unset ADDITIONAL_LEFS && \
	unset ADDITIONAL_GDS && \
	unset ADDITIONAL_LIBS && \
	unset DONT_USE_SC_LIB && \
	unset LIB_FILES && \
	unset MACRO_PLACEMENT && \
	$(MAKE) \"DESIGN_CONFIG=$(3)\" generate_abstract"
endef
```

It ruins the variables file in the make issue because of this format e.g.:
image

**Comment by vvbandeira** [comment]
@habibayassin, please check the variables used [here](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/blob/master/flow/scripts/final_report.tcl#L38-L54). Especially `PWR_NETS_VOLTAGES` and `GND_NETS_VOLTAGES`. See if they are being correctly generated and re-imported.

**Comment by habibayassin** [comment]
> PWR_NETS_VOLTAGES

@vvbandeira These are the values in the variables script:
export PWR_NETS_VOLTAGES='VDD 0.77'
export GND_NETS_VOLTAGES='VSS 0.0'

**Review by vvbandeira — APPROVED** [review]

**Pull request merged**
