### PR TITLE
cleanup a cryptic use of tcl

### PR DESCRIPTION
**Pull request by tspyrou**
Signed-off-by: Tom Spyrou <46945466+tspyrou@users.noreply.github.com>

### CODE REVIEW

**Review by louiic — COMMENTED** [review]
Tom ... this looks suspicious ...

It is supposed to be repairing setup but the code change to repair hold.

**Comment by tspyrou** [comment]
@louiic thanks for catching that, fixed.

**Review by maliberty — COMMENTED** [review]
I find it cryptic both ways but then I always think TCL is cryptic.  There are many uses of {*} through the flow scripts.

**Comment by tspyrou** [comment]
@maliberty I guess it was just cryptic to me then.

**Comment by louiic** [comment]
Matt, … yes it is … this is the quick way to get around “eval”

**Comment by louiic** [comment]
I am ok with “eval” only that … the original line is to do setup repair but the modification is with hold repair… or am I missing something?

**Comment by tspyrou** [comment]
@louiic if the latest update is OK can you approve?

**Review by louiic — APPROVED** [review]

**Comment by louiic** [comment]
Tom,

Done.

Louii

**Pull request merged**
