### PR TITLE
asap7: large amount of fillers test

### PR DESCRIPTION
**Pull request by oharboe**
Signed-off-by: Øyvind Harboe <oyvind.harboe@zylin.com>

### CODE REVIEW

**Comment by maliberty** [comment]
Is there a reason to add this as a flow test rather than just an asap7 issue?

**Comment by oharboe** [comment]
> Is there a reason to add this as a flow test rather than just an asap7 issue?

This is a draft pull request that I intend to refer to from issues, if I can reproduce the problems I am seeing.

I havent gotten around to trying to create reproduction issues yet.

**Comment by maliberty** [comment]
So there is no intention to ever merge this?  You can use make_issue to generate a reproducer without needing a PR.

**Comment by oharboe** [comment]
> So there is no intention to ever merge this? You can use make_issue to generate a reproducer without needing a PR.

Iterating on the code still and need to find the time to articulate the case.

**Pull request closed without merging**
