### PR TITLE
reports: report_metrics now reports into the reports folder

### PR DESCRIPTION
**Pull request by oharboe**
much less spam in the normal log output from report_metrics and easier to navigate instead of scrolling in endless logs.

There are a few things that can't be redirected to a file, a future improvement.

### CODE REVIEW

**Comment by maliberty** [comment]
Do make metadata & update_ok work ok after this change?
@vvbandeira any CI concerns?

**Comment by oharboe** [comment]
> Do make metadata & update_ok work ok after this change? @vvbandeira any CI concerns?

Seems fine...

```
$ make DESIGN_CONFIG=designs/asap7/gcd/config.mk update_ok
[INFO-FLOW] ASU ASAP7 - version 2
Default PVT selection: BC
cp -f ./reports/asap7/gcd/base/metadata-base.json \
      designs/asap7/gcd//metadata-base-ok.json
/home/oyvind/OpenROAD-flow-scripts/flow/util/genRuleFile.py designs/asap7/gcd/ --variant base --failing --tighten
[INFO] Tightening rule synth__design__instance__area__stdcell from 43.85 to 39.59.
[INFO] Tightening rule placeopt__design__instance__area from 51 to 48.
[INFO] Tightening rule placeopt__design__instance__count__stdcell from 518 to 466.
[INFO] Tightening rule cts__design__instance__count__setup_buffer from 45 to 40.
[INFO] Tightening rule cts__design__instance__count__hold_buffer from 45 to 40.
[INFO] Tightening rule detailedroute__route__wirelength from 1413 to 1267.
[INFO] Tightening rule finish__timing__setup__ws from -24.69 to -16.05.
[INFO] Tightening rule finish__design__instance__area from 54 to 51.
[INFO] Tightening rule finish__timing__drv__setup_violation_count from 22 to 20.
[INFO] Tightening rule finish__timing__wns_percent_delay from -11.96 to -10.0.
[INFO] writing /home/oyvind/OpenROAD-flow-scripts/flow/designs/asap7/gcd/rules-base.json
oyvind@corona:~/OpenROAD-flow-scripts/flow$ make DESIGN_CONFIG=designs/asap7/gcd/config.mk metadata
[INFO-FLOW] ASU ASAP7 - version 2
Default PVT selection: BC
./logs/asap7/gcd/base
Log                       Elapsed seconds
1_1_yosys                          2
2_1_floorplan                      1
3_1_place_gp_skip_io               1
3_2_place_iop                      1
3_3_place_gp                       1
3_4_place_resized                  1
3_5_place_dp                       1
4_1_cts                            3
5_1_grt                            1
5_3_route                         13
6_report                           2
[WARN] Overwriting Tag finish__runtime__total
[WARN] Overwriting Tag finish__cpu__total
[WARN] Overwriting Tag finish__mem__peak
[INFO] synth__design__instance__area__stdcell pass test: 34.42338 <= 39.59
[INFO] constraints__clocks__count pass test: 1.0 == 1.0
[INFO] placeopt__design__instance__area pass test: 41.7571 <= 48.0
[INFO] placeopt__design__instance__count__stdcell pass test: 405.0 <= 466.0
[INFO] detailedplace__design__violations pass test: 0.0 == 0.0
[INFO] cts__design__instance__count__setup_buffer pass test: 21.0 <= 40.0
[INFO] cts__design__instance__count__hold_buffer pass test: 0.0 <= 40.0
[INFO] detailedroute__route__wirelength pass test: 1102.0 <= 1267.0
[INFO] detailedroute__route__drc_errors pass test: 0.0 <= 0.0
[INFO] finish__timing__setup__ws pass test: 3.44236 >= -16.05
[INFO] finish__design__instance__area pass test: 43.915 <= 51.0
[INFO] finish__timing__drv__setup_violation_count pass test: 0.0 <= 20.0
[INFO] finish__timing__drv__hold_violation_count pass test: 0.0 <= 100.0
[INFO] finish__timing__wns_percent_delay pass test: 1.115643 >= -10.0
All metadata rules passed (14 rules)
```

**Comment by oharboe** [comment]
> Do make metadata & update_ok work ok after this change? @vvbandeira any CI concerns?

@maliberty Yes, tested locally. See test results in this github issue.

@vvbandeira Comments?

**Review by vvbandeira — APPROVED** [review]
LGTM

**Pull request merged**
