### PR TITLE
Mirrored pins

### PR DESCRIPTION
**Pull request by oharboe**

### CODE REVIEW

**Comment by maliberty** [comment]
Is this to merge or should it be a draft?

**Comment by oharboe** [comment]
> Is this to merge or should it be a draft?

I would like to see it merged. Please fire away w.r.t. changes I should make...

**Comment by oharboe** [comment]
> > Is this to merge or should it be a draft?
> 
> I would like to see it merged. Please fire away w.r.t. changes I should make...

I don't know why it is failing, I updated the baseline it is comparing against.

**Comment by maliberty** [comment]
The CI fails
[ERROR] cts__timing__setup__ws fail test: -156.216 >= -62.5
[ERROR] cts__timing__setup__ws__pre_repair fail test: -153.774 >= -62.5
[ERROR] cts__timing__setup__ws__post_repair fail test: -155.661 >= -62.5
[ERROR] globalroute__timing__setup__ws fail test: -162.539 >= -12.5
[ERROR] finish__timing__setup__ws fail test: -138.651 >= -12.5

**Comment by oharboe** [comment]
> The CI fails [ERROR] cts__timing__setup__ws fail test: -156.216 >= -62.5 [ERROR] cts__timing__setup__ws__pre_repair fail test: -153.774 >= -62.5 [ERROR] cts__timing__setup__ws__post_repair fail test: -155.661 >= -62.5 [ERROR] globalroute__timing__setup__ws fail test: -162.539 >= -12.5 [ERROR] finish__timing__setup__ws fail test: -138.651 >= -12.5

Yes: but why is it different locally and on the server?

**Comment by maliberty** [comment]
> Yes: but why is it different locally and on the server?

I don't know as I don't have access to your local run.

**Comment by oharboe** [comment]
> > Yes: but why is it different locally and on the server?
> 
> I don't know as I don't have access to your local run.

I see, so no difference is expected. I will re-run tomorrow, making sure I'm using latest master.

Meanwhile, if you have any other requests for changes, I'll service them too tomorrow.

**Comment by maliberty** [comment]
Not much else to say.

**Comment by oharboe** [comment]
@maliberty Ran "make update_ok", got different results, but the build server is not yet happy.

**Comment by maliberty** [comment]
The tests are run with "./build_openroad.sh --local".  Are you using the OR submodule version of the head of master in your build?

What I usually do is just grab the build artifacts and unpack whatever results I need.  For this PR see https://jenkins.openroad.tools/job/OpenROAD-flow-scripts-Public/job/public_tests_all-pr/job/PR-764-head/5/artifact/flow/

**Comment by oharboe** [comment]
> The tests are run with "./build_openroad.sh --local". Are you using the OR submodule version of the head of master in your build?
> 
> What I usually do is just grab the build artifacts and unpack whatever results I need. For this PR see https://jenkins.openroad.tools/job/OpenROAD-flow-scripts-Public/job/public_tests_all-pr/job/PR-764-head/5/artifact/flow/

Ah. Nice!

Copied over the metadata-base-ok.json and ran make update_rules.

🤞

**Comment by oharboe** [comment]
@maliberty The new test passes now, but the build failed for what must be other reasons

**Comment by oharboe** [comment]
@maliberty The build fairy has fixed the build :-)

**Review by maliberty — APPROVED** [review]

**Comment by maliberty** [comment]
I was the fairy :)

**Comment by oharboe** [comment]
> I was the fairy :)

:-)

**Pull request merged**
