### PR TITLE
allow empty cells

### PR DESCRIPTION
**Pull request by habibayassin**

### CODE REVIEW

**Comment by vvbandeira** [comment]
@maliberty 
For context: there are error messages about empty GDS today in our CI, but only on the new scripted pipeline does it throw an error -- which is the expected behavior as the `def2stream.py` script exits with error code 42 (number of cells with empty GDS).

**Comment by maliberty** [comment]
What is an example design with this error?

**Comment by habibayassin** [comment]
> What is an example design with this error?

aes-hybrid gf180
Example run: https://jenkins.openroad.tools/blue/organizations/jenkins/OpenROAD-flow-scripts-Public%2Fpublic_tests_all-pr/detail/PR-1709-head/161/pipeline/141/

**Comment by maliberty** [comment]
That design is a bit of an odd case and you could put this option in its config.mk.  Ideally we would handle the gds there too but it `Argument list too long` and I haven't thought it worth addressing.

**Review by maliberty — APPROVED** [review]

**Pull request merged**
