### PR TITLE
rtlmp: turn on by default

### PR DESCRIPTION
**Pull request by oharboe**
See what happens...

### CODE REVIEW

**Comment by maliberty** [comment]
This will have to go through a secure CI to see the impact there.

**Comment by oharboe** [comment]
> This will have to go through a secure CI to see the impact there.

I expected as much. I was pleasantly surprised that there were no issues in public ORFS CI tests.

**Comment by oharboe** [comment]
@maliberty are you taking this for a spin on the internal CI server? Would have been nice to have in the can.

**Comment by maliberty** [comment]
I did and there were failures.  I haven't had a chance to dig into them yet.

**Comment by oharboe** [comment]
@maliberty A loose end... Rabithole or close? Any idea?

**Comment by oharboe** [comment]
@maliberty @jeffng-or So now we're being bitten by regressions in RTLMP_FLOW=0 in bazel-orfs...

Can we push this over the finish line and put RTLMP_FLOW=0 to pasture?

**Comment by maliberty** [comment]
I'll repeat the experiment as its been a while and see.

**Comment by maliberty** [comment]
The CI looks fine (the only failure is in master and is similar).

**Pull request merged**
