### PR TITLE
WIP: Fix io alignment for mock-array-big

### PR DESCRIPTION
**Pull request by yupferris**
Also clean up some of the config/setup stuff to be a bit more straightforward.

Currently breaks IR drop setup (#919).

### CODE REVIEW

**Comment by oharboe** [comment]
@eder-matheus  @maliberty 

```
make DESIGN_CONFIG=designs/asap7/mock-array-big/config.mk
[deleted]
[INFO PPL-0048] Restrict pins [clock] to region 0.0u-60.0u at the top edge.
Found 0 macro blocks.
Using 1u default distance from corners.
Using 2 tracks default min distance between IO pins.
/usr/include/c++/11/bits/stl_vector.h:1045: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = std::vector<int>; _Alloc = std::allocator<std::vector<int> >; std::vector<_Tp, _Alloc>::reference = std::vector<int>&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__n < this->size()' failed.
Signal 6 received
Stack trace:
 0# 0x000056354F9E2DC5 in /home/oyvind/OpenROAD-flow-scripts/tools/install/OpenROAD/bin/openroad
 1# 0x00007FED77042520 in /lib/x86_64-linux-gnu/libc.so.6
 2# pthread_kill in /lib/x86_64-linux-gnu/libc.so.6
 3# raise in /lib/x86_64-linux-gnu/libc.so.6
 4# abort in /lib/x86_64-linux-gnu/libc.so.6
 5# std::char_traits<char>::assign(char&, char const&) in /home/oyvind/OpenROAD-flow-scripts/tools/install/OpenROAD/bin/openroad
 6# std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > >::operator[](unsigned long) in /home/oyvind/OpenROAD-flow-scripts/tools/install/OpenROAD/bin/openroad
 7# ppl::HungarianMatching::createMatrix() in /home/oyvind/OpenROAD-flow-scripts/tools/install/OpenROAD/bin/openroad
 8# ppl::HungarianMatching::findAssignment() in /home/oyvind/OpenROAD-flow-scripts/tools/install/OpenROAD/bin/openroad
 9# ppl::IOPlacer::findPinAssignment(std::vector<ppl::Section, std::allocator<ppl::Section> >&) in /home/oyvind/OpenROAD-flow-scripts/tools/install/OpenROAD/bin/openroad
10# ppl::IOPlacer::run(bool) in /home/oyvind/OpenROAD-flow-scripts/tools/install/OpenROAD/bin/openroad
11# ppl::run_io_placement(bool) in /home/oyvind/OpenROAD-flow-scripts/tools/install/OpenROAD/bin/openroad
12# 0x000056354FCD25CF in /home/oyvind/OpenROAD-flow-scripts/tools/install/OpenROAD/bin/openroad
13# TclNRRunCallbacks in /lib/x86_64-linux-gnu/libtcl8.6.so
14# 0x00007FED7B521028 in /lib/x86_64-linux-gnu/libtcl8.6.so
15# Tcl_EvalEx in /lib/x86_64-linux-gnu/libtcl8.6.so
16# Tcl_Eval in /lib/x86_64-linux-gnu/libtcl8.6.so
17# sta::sourceTclFile(char const*, bool, bool, Tcl_Interp*) in /home/oyvind/OpenROAD-flow-scripts/tools/install/OpenROAD/bin/openroad
18# 0x000056354F9E3A63 in /home/oyvind/OpenROAD-flow-scripts/tools/install/OpenROAD/bin/openroad
19# ord::tclAppInit(Tcl_Interp*) in /home/oyvind/OpenROAD-flow-scripts/tools/install/OpenROAD/bin/openroad
20# Tcl_MainEx in /lib/x86_64-linux-gnu/libtcl8.6.so
21# main in /home/oyvind/OpenROAD-flow-scripts/tools/install/OpenROAD/bin/openroad
22# 0x00007FED77029D90 in /lib/x86_64-linux-gnu/libc.so.6
23# __libc_start_main in /lib/x86_64-linux-gnu/libc.so.6
24# _start in /home/oyvind/OpenROAD-flow-scripts/tools/install/OpenROAD/bin/openroad
Command terminated by signal 6
Elapsed time: 0:02.61[h:]min:sec. CPU time: user 2.49 sys 0.03 (96%). Peak memory: 210352KB.
make[1]: *** [Makefile:500: results/asap7/mock-array-big_Element/base/3_2_place_iop.odb] Error 134
make[1]: Leaving directory '/home/oyvind/OpenROAD-flow-scripts/flow'
make: *** [Makefile:317: results/asap7/mock-array-big_Element/base/Element.lib] Error 2
```

**Comment by yupferris** [comment]
@oharboe: See #934 + #935.

**Comment by maliberty** [comment]
The various referenced issue has all been closed.  Is this still relevant?

**Comment by yupferris** [comment]
Nope, this was just for supporting #919.

**Pull request closed without merging**
