### PR TITLE
makefile: add skip_place and reduce repetition in comments

### PR DESCRIPTION
**Pull request by oharboe**

### CODE REVIEW

**Comment by oharboe** [comment]
@maliberty unrelated mac failure

**Review by maliberty — COMMENTED** [review]
When would you use skip_place?

**Comment by oharboe** [comment]
> When would you use skip_place?

To create eviscerated macros in bug reports and with preview_macro_placement.

**Comment by maliberty** [comment]
> > When would you use skip_place?
> 
> To create eviscerated macros in bug reports and with preview_macro_placement.

Won't all the subsequent steps fail if the design is unplaced?

**Comment by oharboe** [comment]
> > > When would you use skip_place?
> > 
> > 
> > To create eviscerated macros in bug reports and with preview_macro_placement.
> 
> Won't all the subsequent steps fail if the design is unplaced?

Not if you skip cts and route too 😅

**Review by maliberty — APPROVED** [review]

**Pull request merged**
