### PR TITLE
regen fakerams issue 224

### PR DESCRIPTION
**Pull request by jjcherry56**
Signed-off-by: James Cherry <cherry@parallaxsw.com>

### CODE REVIEW

**Comment by dralabeing** [comment]
@tspyrou, @vijayank88 is debugging the source of these CI (DRC etc.) errors to see if this is just a matter of metadata updates, so that these commits can be merged.

**Comment by vijayank88** [comment]
CI fails due to metadata check and congestion issue.
Metadata check fail:
bp_fe_top, bp_be_top,swerv_wrapper design need metadata update to pass CI.
Also fakeram45_64x96 module creating DRC errors, with short violation type. w_mask_in pin only creating short violations as metal layer placed vertically instead of horizontal direction for few pins.

Congestion Issue:
bp_multi_top and black_parrot has congestion issue at global route stage.
Tried with increasing density/Die area still not able to resolve congestion issue.

**Comment by maliberty** [comment]
The macro halo is not being applied.  This looks to be fixed in the current head of master.  @jjcherry56 please merge master to this PR again.  Thanks.

**Comment by maliberty** [comment]
Note that this change does change the shape of the RAMs in LEF.  I don't know if that was expected.

**Comment by maliberty** [comment]
@vijayank88 a cursory look at the floorplan shows the problem with no halos around the macros:
image

**Comment by vijayank88** [comment]
@maliberty 
Platform config.mk has default setting
```
export MACRO_PLACE_HALO ?= 22.4 15.12
export MACRO_PLACE_CHANNEL ?= 18.8 19.95
```
Have you updated this values? or problem with the commit.
Because I tried tuning above values during my review, but no luck.

**Comment by jjcherry56** [comment]
Something in the flow scripts is inserting blockages that are unrelated to the macro locations.

Screen Shot 2022-01-16 at 7 46 51 AM
.

**Comment by vijayank88** [comment]
@maliberty @vvbandeira

With latest commit [ac79516](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/278/commits/ac79516c863fc26720b6e312aacda172367256ae) DRC errors got fixed. Need to update metadata as per current data.

can you please review and update the metadata to pass CI?

**Pull request merged**
