### PR TITLE
designs/asap7: mock array test

### PR DESCRIPTION
**Pull request by oharboe**
@maliberty  I want to see if I can create a mock array test that can reproduce the problems.

I'm running into different problems compiling this one. Why this enormous negative slack?

```
$ make DESIGN_CONFIG=designs/asap7/mock-array/Element/config.mk   generate_abstract
[deleted]
[WARNING ANT-0011] -report_violating_nets is deprecated.
[INFO GRT-0043] No OR_DEFAULT vias defined.
[INFO ANT-0002] Found 0 net violations.
[INFO ANT-0001] Found 0 pin violations.
[INFO FLW-0007] clock clock period 250.000000
[INFO FLW-0008] Clock clock period -950000018091105591419833328319696937680896.000
[INFO FLW-0009] Clock clock slack 1000000019043269116898905829602460421849088.000
[ERROR STA-0414] period '-9.500000180911056e+41' is not a positive float.
Error: write_ref_sdc.tcl, 34 STA-0414
Elapsed time: 0:01.17[h:]min:sec. CPU time: user 1.10 sys 0.06 (100%). Peak memory: 243172KB.
make: *** [results/asap7/mock-array_Element/base/5_1_grt.odb] Error 1
```

I need to flesh out this test a bit more with IO pin placement and scale it up before it becomes interesting.

### CODE REVIEW

**Comment by oharboe** [comment]
@maliberty I have something now that's relatively fast, but is starting to show interesting problems with arrays of macros.

Run:

```
make DESIGN_CONFIG=designs/asap7/mock-array-big/config.mk
```

Some features used:

- placement of macros
- constraints of IOs. 
- slightly non-trivial routing on top of lots of trivial point to point routing.


image

Initial problem:

```
[NesterovSolve] Iter: 2120 overflow: 0.998441 HPWL: 29466309
[NesterovSolve] Iter: 2130 overflow: 0.998437 HPWL: 29465589
[NesterovSolve] Iter: 2140 overflow: 0.998434 HPWL: 29465157
[NesterovSolve] Iter: 2150 overflow: 0.998441 HPWL: 29465181
[ERROR GPL-0305] RePlAce diverged at newStepLength.
Error: global_place_skip_io.tcl, 30 GPL-0305
Elapsed time: 0:09.15[h:]min:sec. CPU time: user 9.09 sys 0.06 (99%). Peak memory: 198968KB.
make: *** [results/asap7/mock-array-big/base/3_1_place_gp_skip_io.odb] Error 1

```

**Comment by maliberty** [comment]
The entire design is covered in a placement blockage
image

Your block are less than the channel apart:
image

export MACRO_PLACE_HALO ?= 10 10
export MACRO_PLACE_CHANNEL ?= 12 12

so it is impossible to place anything

**Comment by maliberty** [comment]
export MACRO_PLACE_HALO = 5 5 
get you past placement

**Comment by maliberty** [comment]
Your macro pins are off-grid
image

met5 has
```
 PROPERTY LEF58_RIGHTWAYONGRIDONLY "
      RIGHTWAYONGRIDONLY ;
 " ;
```
so you can't put wires off grid.  The power strip runs over the pins so there is no way to access them from above either:
image

Basically leaving the pins inaccessible.

**Comment by oharboe** [comment]
@maliberty  Thank you! I'll study and learn.

**Comment by maliberty** [comment]
You'll also want to think about whether you want to reserve any layers above your macro for routing over the top.  Also how you want to build your power grid across the hierarchy.

**Pull request closed without merging**
