### PR TITLE
environment: rename setup_env.sh to env.sh

### PR DESCRIPTION
**Pull request by oharboe**
env.sh has nothing to do with setup.sh as such, so just env.sh is shorter and less confusing

### CODE REVIEW

**Comment by maliberty** [comment]
Have you reviewed all the documentation for any needed updates?

**Comment by oharboe** [comment]
> Have you reviewed all the documentation for any needed updates?

I did a search and replace in all of ORFS. Anything else to change?

**Comment by maliberty** [comment]
OpenROAD/docs/user/BuildLocally.md for one.  I don't know how many other documents/videos/etc are out there that may mention it.  We are potentially creating a different source of confusion.

**Comment by oharboe** [comment]
> OpenROAD/docs/user/BuildLocally.md for one.

Fixed: https://github.com/The-OpenROAD-Project/OpenROAD/pull/3153/

> I don't know how many other documents/videos/etc are out there that may mention it. We are potentially creating a different source of confusion.

The instructions have to change anyway, because as they are they are harmful to your Ubuntu machine...

**Comment by maliberty** [comment]
@vvbandeira any concerns on this?

**Review by vvbandeira — APPROVED** [review]

**Comment by oharboe** [comment]
@maliberty Good to go? @vvbandeira approved.

**Pull request merged**
