### PR TITLE
ihp-sg13g2: fix incorrect tie cell port names

### PR DESCRIPTION
**Pull request by Syndace**
Corrected the tie cell port names according to [ihp-sg13g2's stdcell lef](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/blob/master/flow/platforms/ihp-sg13g2/lef/sg13g2_stdcell.lef).

### CODE REVIEW

**Review by maliberty — APPROVED** [review]
Thanks!

@KrzysztofHerman FYI

**Comment by maliberty** [comment]
I'm curious how you noticed this problem.

**Comment by Syndace** [comment]
There are a few warnings in the logs when running a design with incorrect port names. The first during synthesis:
```
Warning: Wire MissingPads.$auto$hilomap.cc:47:hilomap_worker$101 is used but has no driver.
Warning: Wire MissingPads.$auto$hilomap.cc:39:hilomap_worker$99 is used but has no driver.
```

And then at various points during STA:
```
[WARNING STA-0201] ./results/ihp-sg13g2/missing_pads/base/1_synth.v line 48, instance _10_ port HI not found.
[WARNING STA-0201] ./results/ihp-sg13g2/missing_pads/base/1_synth.v line 51, instance _11_ port LO not found.
```

Those pointed me torwards an issue with the tie cells :)

**Comment by maliberty** [comment]
Thanks for actually reading the warnings :)

**Pull request merged**
