### PR TITLE
Use relative submodules to make cross project merging seemless

### PR DESCRIPTION
**Pull request by tspyrou**
Updating all submodules to respective openroad/HEADs.

### CODE REVIEW

**Comment by rovinski** [comment]
I don't understand this. You're moving the remote repo to be on the same machine and parallel to OpenROAD-flow?

**Comment by tspyrou** [comment]
Yes, that's right. The other repo's are in the same project parallel to openroad-flow-private. I did not change them being cloned into tools, just the location of where the .git is for cloning.

**Comment by rovinski** [comment]
I'm not really sure on the reasoning here, we should probably just schedule a meeting. Would require several changes to Jenkins to not break.

**Comment by maliberty** [comment]
I don't get it either.

**Review by rovinski — APPROVED** [review]
This is actually a relative _url_ and not relative _filepath_. The change is mostly semantic and can allow for easier private-public integration. It is ok by me for now.

**Pull request merged**
