### PR TITLE
makefile: make memory now lists names of instances of memories

### PR DESCRIPTION
**Pull request by oharboe**
@jeffng-or This needs to be knocked into shape...

### CODE REVIEW

**Comment by oharboe** [comment]
never mind... confused at the time...

**Comment by oharboe** [comment]
| Rows | Width |   Bits  | Module               | Instances                                                                                                          |
|------|-------|---------|----------------------|--------------------------------------------------------------------------------------------------------------------|
|  256 |   128 | 524288  | array_256x128        | BoomDuplicatedDataArray.array_0_0_ext, BoomDuplicatedDataArray.array_0_1_ext, BoomDuplicatedDataArray.array_1_0_ext, BoomDuplicatedDataArray.array_1_1_ext, BoomDuplicatedDataArray.array_2_0_ext, BoomDuplicatedDataArray.array_2_1_ext, BoomDuplicatedDataArray.array_3_0_ext, BoomDuplicatedDataArray.array_3_1_ext, BoomDuplicatedDataArray.array_4_0_ext, BoomDuplicatedDataArray.array_4_1_ext, BoomDuplicatedDataArray.array_5_0_ext, BoomDuplicatedDataArray.array_5_1_ext, BoomDuplicatedDataArray.array_6_0_ext, BoomDuplicatedDataArray.array_6_1_ext, BoomDuplicatedDataArray.array_7_0_ext, BoomDuplicatedDataArray.array_7_1_ext |
|  128 |    56 |  14336  | btb_128x56           | BTBBranchPredictorBank.btb_0_ext, BTBBranchPredictorBank.btb_1_ext                                                  |
|  256 |    64 | 262144  | dataArrayB_256x64    | ICache.dataArrayB0Way_0_ext, ICache.dataArrayB0Way_1_ext, ICache.dataArrayB0Way_2_ext, ICache.dataArrayB0Way_3_ext, ICache.dataArrayB0Way_4_ext, ICache.dataArrayB0Way_5_ext, ICache.dataArrayB0Way_6_ext, ICache.dataArrayB0Way_7_ext, ICache.dataArrayB1Way_0_ext, ICache.dataArrayB1Way_1_ext, ICache.dataArrayB1Way_2_ext, ICache.dataArrayB1Way_3_ext, ICache.dataArrayB1Way_4_ext, ICache.dataArrayB1Way_5_ext, ICache.dataArrayB1Way_6_ext, ICache.dataArrayB1Way_7_ext |
| 2048 |     8 |  16384  | data_2048x8          | BIMBranchPredictorBank.data_ext                                                                                     |
|  128 |    40 |   5120  | ebtb_128x40          | BTBBranchPredictorBank.ebtb_ext                                                                                     |
|   40 |    72 |   5760  | ghist_40x72          | FetchTargetQueue.ghist_0_ext, FetchTargetQueue.ghist_1_ext                                                          |
|  512 |    46 |  23552  | l2_tlb_ram_0_512x46  | PTW.l2_tlb_ram_0_ext                                                                                                |
|   32 |   128 |   4096  | lb_32x128            | BoomMSHRFile.lb_ext                                                                                                 |
|  128 |     4 |   4096  | mem_128x4            | TageTable.hi_us_ext, TageTable.lo_us_ext, TageTable_1.hi_us_ext, TageTable_1.lo_us_ext, TageTable_4.hi_us_ext, TageTable_4.lo_us_ext, TageTable_5.hi_us_ext, TageTable_5.lo_us_ext |
|  256 |     4 |   4096  | mem_256x4            | TageTable_2.hi_us_ext, TageTable_2.lo_us_ext, TageTable_3.hi_us_ext, TageTable_3.lo_us_ext                          |
|  128 |   120 |  30720  | meta_128x120         | BTBBranchPredictorBank.meta_0_ext, BTBBranchPredictorBank.meta_1_ext                                                |
|   40 |   240 |   9600  | meta_40x240          | FetchTargetQueue.meta_ext                                                                                           |
|   16 |    46 |    736  | ram_16x46            | BranchKillableQueue.ram_ext                                                                                         |
|    2 |   412 |    824  | ram_2x412            | Queue_21.ram_ext                                                                                                    |
|    3 |    79 |    237  | ram_3x79             | BranchKillableQueue_11.ram_ext                                                                                      |
|    4 |    65 |    260  | ram_4x65             | BranchKillableQueue_8.ram_ext                                                                                       |
|    5 |    79 |    395  | ram_5x79             | BranchKillableQueue_9.ram_ext                                                                                       |
|    7 |    79 |    553  | ram_7x79             | BranchKillableQueue_10.ram_ext                                                                                      |
|  128 |    64 |   8192  | regfile_128x64       | RegisterFileSynthesizable_1.regfile_ext                                                                             |
|  128 |    65 |   8320  | regfile_128x65       | RegisterFileSynthesizable.regfile_ext                                                                               |
|   17 |    64 |   1088  | sdq_17x64            | BoomMSHRFile.sdq_ext                                                                                                |
|  128 |    44 |  11264  | table_128x44         | TageTable.table_ext, TageTable_1.table_ext                                                                          |
|  128 |    52 |  13312  | table_128x52         | TageTable_4.table_ext, TageTable_5.table_ext                                                                        |
|  256 |    48 |  24576  | table_256x48         | TageTable_2.table_ext, TageTable_3.table_ext                                                                        |
|   64 |   168 |  10752  | tag_array_64x168     | ICache.tag_array_ext                                                                                                |
|   64 |   184 |  11776  | tag_array_64x184     | L1MetadataArray.tag_array_ext                                                                                       |

**Comment by oharboe** [comment]
sorted descending on total bits:

| Rows | Width | Bits  | Module               | Instances  |
|------|-------|-------|----------------------|------------|
| 256  | 128   | 524288| array_256x128        | BoomTile.dcache.BoomNonBlockingDCache.data.BoomDuplicatedDataArray.array_0_0_ext, BoomTile.dcache.BoomNonBlockingDCache.data.BoomDuplicatedDataArray.array_0_1_ext, BoomTile.dcache.BoomNonBlockingDCache.data.BoomDuplicatedDataArray.array_1_0_ext, BoomTile.dcache.BoomNonBlockingDCache.data.BoomDuplicatedDataArray.array_1_1_ext, BoomTile.dcache.BoomNonBlockingDCache.data.BoomDuplicatedDataArray.array_2_0_ext, BoomTile.dcache.BoomNonBlockingDCache.data.BoomDuplicatedDataArray.array_2_1_ext, BoomTile.dcache.BoomNonBlockingDCache.data.BoomDuplicatedDataArray.array_3_0_ext, BoomTile.dcache.BoomNonBlockingDCache.data.BoomDuplicatedDataArray.array_3_1_ext, BoomTile.dcache.BoomNonBlockingDCache.data.BoomDuplicatedDataArray.array_4_0_ext, BoomTile.dcache.BoomNonBlockingDCache.data.BoomDuplicatedDataArray.array_4_1_ext, BoomTile.dcache.BoomNonBlockingDCache.data.BoomDuplicatedDataArray.array_5_0_ext, BoomTile.dcache.BoomNonBlockingDCache.data.BoomDuplicatedDataArray.array_5_1_ext, BoomTile.dcache.BoomNonBlockingDCache.data.BoomDuplicatedDataArray.array_6_0_ext, BoomTile.dcache.BoomNonBlockingDCache.data.BoomDuplicatedDataArray.array_6_1_ext, BoomTile.dcache.BoomNonBlockingDCache.data.BoomDuplicatedDataArray.array_7_0_ext, BoomTile.dcache.BoomNonBlockingDCache.data.BoomDuplicatedDataArray.array_7_1_ext |
| 256  | 64    | 262144| dataArrayB_256x64    | BoomTile.frontend.BoomFrontend.icache.ICache.dataArrayB0Way_0_ext, BoomTile.frontend.BoomFrontend.icache.ICache.dataArrayB0Way_1_ext, BoomTile.frontend.BoomFrontend.icache.ICache.dataArrayB0Way_2_ext, BoomTile.frontend.BoomFrontend.icache.ICache.dataArrayB0Way_3_ext, BoomTile.frontend.BoomFrontend.icache.ICache.dataArrayB0Way_4_ext, BoomTile.frontend.BoomFrontend.icache.ICache.dataArrayB0Way_5_ext, BoomTile.frontend.BoomFrontend.icache.ICache.dataArrayB0Way_6_ext, BoomTile.frontend.BoomFrontend.icache.ICache.dataArrayB0Way_7_ext, BoomTile.frontend.BoomFrontend.icache.ICache.dataArrayB1Way_0_ext, BoomTile.frontend.BoomFrontend.icache.ICache.dataArrayB1Way_1_ext, BoomTile.frontend.BoomFrontend.icache.ICache.dataArrayB1Way_2_ext, BoomTile.frontend.BoomFrontend.icache.ICache.dataArrayB1Way_3_ext, BoomTile.frontend.BoomFrontend.icache.ICache.dataArrayB1Way_4_ext, BoomTile.frontend.BoomFrontend.icache.ICache.dataArrayB1Way_5_ext, BoomTile.frontend.BoomFrontend.icache.ICache.dataArrayB1Way_6_ext, BoomTile.frontend.BoomFrontend.icache.ICache.dataArrayB1Way_7_ext |
| 128  | 120   | 61440 | meta_128x120         | BoomTile.frontend.BoomFrontend.bpd.BranchPredictor.banked_predictors_0.ComposedBranchPredictorBank.btb.BTBBranchPredictorBank.meta_0_ext, BoomTile.frontend.BoomFrontend.bpd.BranchPredictor.banked_predictors_0.ComposedBranchPredictorBank.btb.BTBBranchPredictorBank.meta_1_ext, BoomTile.frontend.BoomFrontend.bpd.BranchPredictor.banked_predictors_1.ComposedBranchPredictorBank.btb.BTBBranchPredictorBank.meta_0_ext, BoomTile.frontend.BoomFrontend.bpd.BranchPredictor.banked_predictors_1.ComposedBranchPredictorBank.btb.BTBBranchPredictorBank.meta_1_ext |
| 256  | 48    | 49152 | table_256x48         | BoomTile.frontend.BoomFrontend.bpd.BranchPredictor.banked_predictors_0.ComposedBranchPredictorBank.tage.TageBranchPredictorBank.t_2.TageTable_2.table_ext, BoomTile.frontend.BoomFrontend.bpd.BranchPredictor.banked_predictors_0.ComposedBranchPredictorBank.tage.TageBranchPredictorBank.t_3.TageTable_3.table_ext, BoomTile.frontend.BoomFrontend.bpd.BranchPredictor.banked_predictors_1.ComposedBranchPredictorBank.tage.TageBranchPredictorBank.t_2.TageTable_2.table_ext, BoomTile.frontend.BoomFrontend.bpd.BranchPredictor.banked_predictors_1.ComposedBranchPredictorBank.tage.TageBranchPredictorBank.t_3.TageTable_3.table_ext |
| 2048 | 8     | 32768 | data_2048x8          | BoomTile.frontend.BoomFrontend.bpd.BranchPredictor.banked_predictors_0.ComposedBranchPredictorBank.bim.BIMBranchPredictorBank.data_ext, BoomTile.frontend.BoomFrontend.bpd.BranchPredictor.banked_predictors_1.ComposedBranchPredictorBank.bim.BIMBranchPredictorBank.data_ext |
| 128  | 56    | 28672 | btb_128x56           | BoomTile.frontend.BoomFrontend.bpd.BranchPredictor.banked_predictors_0.ComposedBranchPredictorBank.btb.BTBBranchPredictorBank.btb_0_ext, BoomTile.frontend.BoomFrontend.bpd.BranchPredictor.banked_predictors_0.ComposedBranchPredictorBank.btb.BTBBranchPredictorBank.btb_1_ext, BoomTile.frontend.BoomFrontend.bpd.BranchPredictor.banked_predictors_1.ComposedBranchPredictorBank.btb.BTBBranchPredictorBank.btb_0_ext, BoomTile.frontend.BoomFrontend.bpd.BranchPredictor.banked_predictors_1.ComposedBranchPredictorBank.btb.BTBBranchPredictorBank.btb_1_ext |
| 128  | 52    | 26624 | table_128x52         | BoomTile.frontend.BoomFrontend.bpd.BranchPredictor.banked_predictors_0.ComposedBranchPredictorBank.tage.TageBranchPredictorBank.t_4.TageTable_4.table_ext, BoomTile.frontend.BoomFrontend.bpd.BranchPredictor.banked_predictors_0.ComposedBranchPredictorBank.tage.TageBranchPredictorBank.t_5.TageTable_5.table_ext, BoomTile.frontend.BoomFrontend.bpd.BranchPredictor.banked_predictors_1.ComposedBranchPredictorBank.tage.TageBranchPredictorBank.t_4.TageTable_4.table_ext, BoomTile.frontend.BoomFrontend.bpd.BranchPredictor.banked_predictors_1.ComposedBranchPredictorBank.tage.TageBranchPredictorBank.t_5.TageTable_5.table_ext |
| 512  | 46    | 23552 | l2_tlb_ram_0_512x46  | BoomTile.ptw.PTW.l2_tlb_ram_0_ext |
| 64   | 184   | 23552 | tag_array_64x184     | BoomTile.dcache.BoomNonBlockingDCache.meta_0.L1MetadataArray.tag_array_ext, BoomTile.dcache.BoomNonBlockingDCache.meta_1.L1MetadataArray.tag_array_ext |
| 128  | 44    | 22528 | table_128x44         | BoomTile.frontend.BoomFrontend.bpd.BranchPredictor.banked_predictors_0.ComposedBranchPredictorBank.tage.TageBranchPredictorBank.t.TageTable.table_ext, BoomTile.frontend.BoomFrontend.bpd.BranchPredictor.banked_predictors_0.ComposedBranchPredictorBank.tage.TageBranchPredictorBank.t_1.TageTable_1.table_ext, BoomTile.frontend.BoomFrontend.bpd.BranchPredictor.banked_predictors_1.ComposedBranchPredictorBank.tage.TageBranchPredictorBank.t.TageTable.table_ext, BoomTile.frontend.BoomFrontend.bpd.BranchPredictor.banked_predictors_1.ComposedBranchPredictorBank.tage.TageBranchPredictorBank.t_1.TageTable_1.table_ext |
| 64   | 168   | 10752 | tag_array_64x168     | BoomTile.frontend.BoomFrontend.icache.ICache.tag_array_ext |
| 128  | 40    | 10240 | ebtb_128x40          | BoomTile.frontend.BoomFrontend.bpd.BranchPredictor.banked_predictors_0.ComposedBranchPredictorBank.btb.BTBBranchPredictorBank.ebtb_ext, BoomTile.frontend.BoomFrontend.bpd.BranchPredictor.banked_predictors_1.ComposedBranchPredictorBank.btb.BTBBranchPredictorBank.ebtb_ext |
| 40   | 240   | 9600  | meta_40x240          | BoomTile.frontend.BoomFrontend.ftq.FetchTargetQueue.meta_ext |
| 128  | 65    | 8320  | regfile_128x65       | BoomTile.core.BoomCore.FpPipeline.FpPipeline.fregfile.RegisterFileSynthesizable.regfile_ext |
| 128  | 4     | 8192  | mem_128x4            | BoomTile.frontend.BoomFrontend.bpd.BranchPredictor.banked_predictors_0.ComposedBranchPredictorBank.tage.TageBranchPredictorBank.t.TageTable.hi_us_ext, BoomTile.frontend.BoomFrontend.bpd.BranchPredictor.banked_predictors_0.ComposedBranchPredictorBank.tage.TageBranchPredictorBank.t.TageTable.lo_us_ext, BoomTile.frontend.BoomFrontend.bpd.BranchPredictor.banked_predictors_0.ComposedBranchPredictorBank.tage.TageBranchPredictorBank.t_1.TageTable_1.hi_us_ext, BoomTile.frontend.BoomFrontend.bpd.BranchPredictor.banked_predictors_0.ComposedBranchPredictorBank.tage.TageBranchPredictorBank.t_1.TageTable_1.lo_us_ext, BoomTile.frontend.BoomFrontend.bpd.BranchPredictor.banked_predictors_0.ComposedBranchPredictorBank.tage.TageBranchPredictorBank.t_4.TageTable_4.hi_us_ext, BoomTile.frontend.BoomFrontend.bpd.BranchPredictor.banked_predictors_0.ComposedBranchPredictorBank.tage.TageBranchPredictorBank.t_4.TageTable_4.lo_us_ext, BoomTile.frontend.BoomFrontend.bpd.BranchPredictor.banked_predictors_0.ComposedBranchPredictorBank.tage.TageBranchPredictorBank.t_5.TageTable_5.hi_us_ext, BoomTile.frontend.BoomFrontend.bpd.BranchPredictor.banked_predictors_0.ComposedBranchPredictorBank.tage.TageBranchPredictorBank.t_5.TageTable_5.lo_us_ext, BoomTile.frontend.BoomFrontend.bpd.BranchPredictor.banked_predictors_1.ComposedBranchPredictorBank.tage.TageBranchPredictorBank.t.TageTable.hi_us_ext, BoomTile.frontend.BoomFrontend.bpd.BranchPredictor.banked_predictors_1.ComposedBranchPredictorBank.tage.TageBranchPredictorBank.t.TageTable.lo_us_ext, BoomTile.frontend.BoomFrontend.bpd.BranchPredictor.banked_predictors_1.ComposedBranchPredictorBank.tage.TageBranchPredictorBank.t_1.TageTable_1.hi_us_ext, BoomTile.frontend.BoomFrontend.bpd.BranchPredictor.banked_predictors_1.ComposedBranchPredictorBank.tage.TageBranchPredictorBank.t_1.TageTable_1.lo_us_ext, BoomTile.frontend.BoomFrontend.bpd.BranchPredictor.banked_predictors_1.ComposedBranchPredictorBank.tage.TageBranchPredictorBank.t_4.TageTable_4.hi_us_ext, BoomTile.frontend.BoomFrontend.bpd.BranchPredictor.banked_predictors_1.ComposedBranchPredictorBank.tage.TageBranchPredictorBank.t_4.TageTable_4.lo_us_ext, BoomTile.frontend.BoomFrontend.bpd.BranchPredictor.banked_predictors_1.ComposedBranchPredictorBank.tage.TageBranchPredictorBank.t_5.TageTable_5.hi_us_ext, BoomTile.frontend.BoomFrontend.bpd.BranchPredictor.banked_predictors_1.ComposedBranchPredictorBank.tage.TageBranchPredictorBank.t_5.TageTable_5.lo_us_ext |
| 256  | 4     | 8192  | mem_256x4            | BoomTile.frontend.BoomFrontend.bpd.BranchPredictor.banked_predictors_0.ComposedBranchPredictorBank.tage.TageBranchPredictorBank.t_2.TageTable_2.hi_us_ext, BoomTile.frontend.BoomFrontend.bpd.BranchPredictor.banked_predictors_0.ComposedBranchPredictorBank.tage.TageBranchPredictorBank.t_2.TageTable_2.lo_us_ext, BoomTile.frontend.BoomFrontend.bpd.BranchPredictor.banked_predictors_0.ComposedBranchPredictorBank.tage.TageBranchPredictorBank.t_3.TageTable_3.hi_us_ext, BoomTile.frontend.BoomFrontend.bpd.BranchPredictor.banked_predictors_0.ComposedBranchPredictorBank.tage.TageBranchPredictorBank.t_3.TageTable_3.lo_us_ext, BoomTile.frontend.BoomFrontend.bpd.BranchPredictor.banked_predictors_1.ComposedBranchPredictorBank.tage.TageBranchPredictorBank.t_2.TageTable_2.hi_us_ext, BoomTile.frontend.BoomFrontend.bpd.BranchPredictor.banked_predictors_1.ComposedBranchPredictorBank.tage.TageBranchPredictorBank.t_2.TageTable_2.lo_us_ext, BoomTile.frontend.BoomFrontend.bpd.BranchPredictor.banked_predictors_1.ComposedBranchPredictorBank.tage.TageBranchPredictorBank.t_3.TageTable_3.hi_us_ext, BoomTile.frontend.BoomFrontend.bpd.BranchPredictor.banked_predictors_1.ComposedBranchPredictorBank.tage.TageBranchPredictorBank.t_3.TageTable_3.lo_us_ext |
| 128  | 64    | 8192  | regfile_128x64       | BoomTile.core.BoomCore.iregfile.RegisterFileSynthesizable_1.regfile_ext |
| 16   | 46    | 5888  | ram_16x46            | BoomTile.dcache.BoomNonBlockingDCache.mshrs.BoomMSHRFile.mshrs_0.BoomMSHR.rpq.BranchKillableQueue.ram_ext, BoomTile.dcache.BoomNonBlockingDCache.mshrs.BoomMSHRFile.mshrs_1.BoomMSHR.rpq.BranchKillableQueue.ram_ext, BoomTile.dcache.BoomNonBlockingDCache.mshrs.BoomMSHRFile.mshrs_2.BoomMSHR.rpq.BranchKillableQueue.ram_ext, BoomTile.dcache.BoomNonBlockingDCache.mshrs.BoomMSHRFile.mshrs_3.BoomMSHR.rpq.BranchKillableQueue.ram_ext, BoomTile.dcache.BoomNonBlockingDCache.mshrs.BoomMSHRFile.mshrs_4.BoomMSHR.rpq.BranchKillableQueue.ram_ext, BoomTile.dcache.BoomNonBlockingDCache.mshrs.BoomMSHRFile.mshrs_5.BoomMSHR.rpq.BranchKillableQueue.ram_ext, BoomTile.dcache.BoomNonBlockingDCache.mshrs.BoomMSHRFile.mshrs_6.BoomMSHR.rpq.BranchKillableQueue.ram_ext, BoomTile.dcache.BoomNonBlockingDCache.mshrs.BoomMSHRFile.mshrs_7.BoomMSHR.rpq.BranchKillableQueue.ram_ext |
| 40   | 72    | 5760  | ghist_40x72          | BoomTile.frontend.BoomFrontend.ftq.FetchTargetQueue.ghist_0_ext, BoomTile.frontend.BoomFrontend.ftq.FetchTargetQueue.ghist_1_ext |
| 32   | 128   | 4096  | lb_32x128            | BoomTile.dcache.BoomNonBlockingDCache.mshrs.BoomMSHRFile.lb_ext |
| 17   | 64    | 1088  | sdq_17x64            | BoomTile.dcache.BoomNonBlockingDCache.mshrs.BoomMSHRFile.sdq_ext |
| 2    | 412   | 824   | ram_2x412            | BoomTile.frontend.BoomFrontend.f4_btb_corrections.Queue_21.ram_ext |
| 7    | 79    | 553   | ram_7x79             | BoomTile.core.BoomCore.FpPipeline.FpPipeline.fpu_exe_unit.FPUExeUnit.queue.BranchKillableQueue_10.ram_ext |
| 5    | 79    | 395   | ram_5x79             | BoomTile.core.BoomCore.alu_exe_unit.ALUExeUnit_2.queue.BranchKillableQueue_9.ram_ext |
| 4    | 65    | 260   | ram_4x65             | BoomTile.dcache.BoomNonBlockingDCache.mshrs.BoomMSHRFile.respq.BranchKillableQueue_8.ram_ext |
| 3    | 79    | 237   | ram_3x79             | BoomTile.core.BoomCore.FpPipeline.FpPipeline.fpu_exe_unit.FPUExeUnit.fp_sdq.BranchKillableQueue_11.ram_ext |

**Review by jeffng-or — CHANGES_REQUESTED** [review]
Code works as advertised. I had a few suggestions for performance and maintainability:

1. Change find_top_module to find_top_modules, since we're returning the list of top modules
2. Move call of find_top_modules from find_cells_by_type into format_ram_table_from_json, since the list of top modules is invariant and there's no need to recalculate it for each memory that we find
3. Add a comment in find_cells_by_type_in_module to document the cell path formatting. Something like:
```
"""
    Searches through hierarchy starting at module_name to find all instances of
    the given module/type in the hierarchy.

    Returns list of cell paths, which are constructed as:

        <top_module_name>.(<child_inst_name>.<child_module_name>+).<memory_inst_name>

    where the child_inst_name/child_module_name pairs are repeated for each level of the hierarchy.
 """
```

**Comment by oharboe** [comment]
@jeffng-or fixed

**Review by jeffng-or — APPROVED** [review]

**Comment by maliberty** [comment]
"Lint Python / lint (pull_request) " needs fixing

**Comment by oharboe** [comment]
@maliberty Can you retrigger the lint job?

This is unrelated to this PR:

```
  Receiving objects:  24% (603/2458), 10.86 MiB | 767.00 KiB/s
  Receiving objects:  24% (603/2458), 11.68 MiB | 782.00 KiB/s
  Receiving objects:  24% (603/2458), 12.27 MiB | 731.00 KiB/s
  Receiving objects:  24% (603/2458), 12.68 MiB | 741.00 KiB/s
  Receiving objects:  24% (603/2458), 13.35 MiB | 712.00 KiB/s
  Receiving objects:  24% (603/2458), 14.06 MiB | 700.00 KiB/s
  Error: error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
  Error: error: 421 bytes of body are still expected
  fetch-pack: unexpected disconnect while reading sideband packet
  Error: fatal: early EOF
  Error: fatal: fetch-pack: invalid index-pack output
  Error: The process '/usr/bin/git' failed with exit code 128
```

**Comment by oharboe** [comment]
@maliberty It worked :relieved:

**Review by maliberty — APPROVED** [review]

**Pull request merged**
