### PR TITLE
Add OpenPOWER Microwatt core

### PR DESCRIPTION
**Pull request by antonblanchard**

### CODE REVIEW

**Comment by antonblanchard** [comment]
A few things stand out:

- ~~Why is `repair_clock_nets` inserting a `clkbuf_1`, instead of something bigger. We see an enormous delay in the clock tree because of it (over 4ns). This isn't happening when running through Openlane, but as of yet I cant work out why ORFS is different:~~

```
                          0.00    0.00   clock ext_clk (rise edge)
                          0.00    0.00   clock source latency
                  0.54    0.42    0.42 ^ ext_clk (in)
     1    0.12                           ext_clk (net)
                  0.56    0.00    0.42 ^ repeater15/A (sky130_fd_sc_hd__clkbuf_1)
                  6.30    4.20    4.62 ^ repeater15/X (sky130_fd_sc_hd__clkbuf_1)
     1    0.55                           net7213 (net)
                  6.47    0.86    5.48 ^ clkbuf_0_ext_clk/A (sky130_fd_sc_hd__clkbuf_8)
                  1.36    1.69    7.17 ^ clkbuf_0_ext_clk/X (sky130_fd_sc_hd__clkbuf_8)
     4    0.86                           clknet_0_ext_clk (net)
                  1.40    0.18    7.35 ^ clkbuf_2_3_0_ext_clk/A (sky130_fd_sc_hd__clkbuf_8)
                  0.26    0.49    7.84 ^ clkbuf_2_3_0_ext_clk/X (sky130_fd_sc_hd__clkbuf_8)
     2    0.14                           clknet_2_3_0_ext_clk (net)
                  0.30    0.08    7.92 ^ clkbuf_3_7_0_ext_clk/A (sky130_fd_sc_hd__clkbuf_8)
                  0.24    0.35    8.27 ^ clkbuf_3_7_0_ext_clk/X (sky130_fd_sc_hd__clkbuf_8)
     4    0.13                           clknet_3_7_0_ext_clk (net)
                  0.24    0.02    8.28 ^ clkbuf_5_31__f_ext_clk/A (sky130_fd_sc_hd__clkbuf_8)
                  0.32    0.40    8.69 ^ clkbuf_5_31__f_ext_clk/X (sky130_fd_sc_hd__clkbuf_8)
    13    0.19                           clknet_5_31__leaf_ext_clk (net)
```

- I'm not completely sure I have my setup constraints in the liberty files correct. As an example, I have an I/O that is constrained in the macro SDC file to be 2ns after the clock. The liberty file has:

```
            timing() {
                timing_type : setup_rising;
                related_pin : "CLK";
                rise_constraint(scalar) {
                    values("-1.8");
                }
                fall_constraint(scalar) {
                    values("-1.8");
                }
            }
            timing() {
                timing_type : hold_rising;
                related_pin : "CLK";
                rise_constraint(scalar) {
                    values("2.0");
                }
                fall_constraint(scalar) {
                    values("2.0");
                }
            }
        }
```

I think that's right - If the I/O was constrained to be at time 0, then the setup constraint would be small positive, the positive direction being earlier in time before the next clock edge. Since it is constrained to be at 2ns it needs to be negative so it is after the clock edge.

For outputs I give them a middle of the range transition time (0.75ns) and a delay that matches the SDC constraint (here 8ns, 10ns period - 2ns output delay). I'm using hierarchical STA to double check the tape out, so I don't need to be exact with my modelling:

```
+            timing() {
+                related_pin : "CLK";
+                timing_sense : non_unate
+                timing_type : rising_edge
+                cell_rise(scalar) {
+                    values("8.0");
+                }
+                cell_fall(scalar) {
+                    values("8.0");
+                }
+                rise_transition(scalar) {
+                    values("0.75");
+                }
+                fall_transition(scalar) {
+                    values("0.75");
+                }
+            }
```

**Comment by antonblanchard** [comment]
> Why is repair_clock_nets inserting a clkbuf_1, instead of something bigger. We see an enormous delay in the clock tree because of it (over 4ns). This isn't happening when running through Openlane, but as of yet I cant work out why ORFS is different:

Ignore this - I had a local patch in my OpenROAD tree which was limiting the buffer choice.

**Comment by antonblanchard** [comment]
The macros aren't getting powered - I see no vias from met5 to met4 within all macros. I presume I need a custom `pdn.cfg`?

**Comment by maliberty** [comment]
We are moving away from pdn.cfg to use the tcl commands for pdn.  Does your macro have unusal power pin names?

**Comment by antonblanchard** [comment]
The macro power pins are `VPWR` and `VGND` which are what the sky130 PDK uses.

**Comment by maliberty** [comment]
In that case you'll use add_global_connection to hook them up.  Vias should then be generated.

**Comment by maliberty** [comment]
I've resolved the scan issue with https://github.com/The-OpenROAD-Project/security/commit/9a82c8b8a4e6d918774bb95c4402e4dbb66a698e

**Comment by maliberty** [comment]
@antonblanchard how much does the cts tuning get you?  [commented in the wrong PR previously]

**Comment by maliberty** [comment]
@ravi-varadarajan this could be a public RTL-MP test case once its ready. Currently it has a fixed macro placement due to poor TMP results.  [commented in the wrong PR previously]

**Comment by antonblanchard** [comment]
> In that case you'll use add_global_connection to hook them up. Vias should then be generated.

I'm probably doing it wrong, but I added:

```
+export PDN_TCL = $(microwatt_DIR)/pdn.tcl
```

which consisted of:

```
add_global_connection -net VDD -pin_pattern {^VPWR$} -power
add_global_connection -net VDD -pin_pattern {^VPB$} -power

add_global_connection -net VSS -pin_pattern {^VGND$} -ground
add_global_connection -net VSS -pin_pattern {^VNB$} -ground
```

And it dies with:

```
[WARNING PSM-0016] Voltage pad location (VSRC) file not specified, defaulting pad location to checkerboard pattern on core area.
[WARNING PSM-0017] X direction bump pitch is not specified, defaulting to 140um.
[WARNING PSM-0018] Y direction bump pitch is not specified, defaulting to 140um.
[WARNING PSM-0065] VSRC location not specified, using default checkerboard pattern with one VDD every size bumps in x-direction and one in two bumps in the y-direction
[WARNING PSM-0070] Net VDD has no nodes and will be skipped
/usr/include/c++/11/bits/stl_vector.h:1045: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = double; _Alloc = std::allocator<double>; std::vector<_Tp, _Alloc>::reference = double&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__n < this->size()' failed.
Stack trace:
 0# 0x0000000000FC427E in /home/anton_unencrypted/OpenROAD/build-dist/src/openroad
 1# 0x00007F0CA0E1D750 in /lib64/libc.so.6
 2# 0x00007F0CA0E6A88C in /lib64/libc.so.6
 3# raise in /lib64/libc.so.6
 4# abort in /lib64/libc.so.6
 5# fmt::v8::detail::for_each_codepoint<fmt::v8::detail::compute_width(fmt::v8::basic_string_view<char>)::count_code_points>(fmt::v8::basic_string_view<char>, fmt::v8::detail::compute_width(fmt::v8::basic_string_view<char>)::count_code_points)::{lambda(char const*, char const*)#1}::operator()(char const*, char const*) const in /home/anton_unencrypted/OpenROAD/build-dist/src/openroad
 6# psm::IRSolver::SolveIR() in /home/anton_unencrypted/OpenROAD/build-dist/src/openroad
 7# psm::PDNSim::analyze_power_grid() in /home/anton_unencrypted/OpenROAD/build-dist/src/openroad
 8# 0x0000000001D622D0 in /home/anton_unencrypted/OpenROAD/build-dist/src/openroad
 9# TclNRRunCallbacks in /lib64/libtcl8.6.so
10# 0x00007F0CA2AA3BEA in /lib64/libtcl8.6.so
11# Tcl_EvalEx in /lib64/libtcl8.6.so
12# Tcl_Eval in /lib64/libtcl8.6.so
13# sta::sourceTclFile(char const*, bool, bool, Tcl_Interp*) in /home/anton_unencrypted/OpenROAD/build-dist/src/openroad
14# ord::tclAppInit(Tcl_Interp*) in /home/anton_unencrypted/OpenROAD/build-dist/src/openroad
15# Tcl_MainEx in /lib64/libtcl8.6.so
16# main in /home/anton_unencrypted/OpenROAD/build-dist/src/openroad
17# 0x00007F0CA0E08560 in /lib64/libc.so.6
18# __libc_start_main in /lib64/libc.so.6
19# _start in /home/anton_unencrypted/OpenROAD/build-dist/src/openroad
```

**Comment by maliberty** [comment]
I think I lead you astray.  I see that VPWR & VGND are specified in the sky130hd pdn.cfg already so you should need to override it.  If you do you have to give the full spec not just the additional commands.  I'll see if I can spot the via problem

**Comment by antonblanchard** [comment]
We were discussing the CTS issues with this design (albeit using the Openlane flow) at https://github.com/The-OpenROAD-Project/OpenROAD/issues/1714

I just reran ORFS without and with the overrides:

Baseline:
```
==========================================================================
finish report_clock_skew
--------------------------------------------------------------------------
Clock ext_clk
Latency      CRPR       Skew
_121029_/CLK ^
   9.17
_117745_/CLK ^
   6.33     -0.13       2.72
```

Overrides:
```
Clock ext_clk
Latency      CRPR       Skew
_121016_/CLK ^
   6.19
_117732_/CLK ^
   3.32     -0.16       2.71
```

So it helps quite a bit. Having said that, my Openlane results and @jjcherry56's results are better, so I'll see if I can tune it a bit more

**Comment by maliberty** [comment]
If you want to try the autotuner you could have it find the best parameters for CTS on your design.

**Review by maliberty — APPROVED** [review]

**Comment by maliberty** [comment]
We can deal with the pdn via issue post-merge.  I'd like to tackle it once we switch skywater to the new pdngen (hopefully the problem will just disappear).

**Pull request merged**
