### PR TITLE
Build openroad ubuntu 22 gui using docker image

### PR DESCRIPTION
**Pull request by oharboe**
My thinking is that this is one step in the direction of creating an Ubuntu .deb package as part of the CI build.

### CODE REVIEW

**Comment by yupferris** [comment]
Nice, very useful!

**Comment by oharboe** [comment]
> Nice, very useful!

If nothing else, I like that it doesn't install e.g. a partial boost or cmake into my system, which causes problems with other things I'm trying to build on my system.

**Comment by vvbandeira** [comment]
@oharboe, thanks for the contribution. We already had plans to add support for ubuntu 22 via docker images. We are trying to speed up the development; you can see our progress in #697. Could you check that the direction of our PR is aligned with your goal here? We are planning to merge that PR soon.

**Comment by oharboe** [comment]
> @oharboe, thanks for the contribution. We already had plans to add support for ubuntu 22 via docker images. We are trying to speed up the development; you can see our progress in #697. Could you check that the direction of our PR is aligned with your goal here? We are planning to merge that PR soon.

Silly question: any reason not to make it a draft pull request? Easier to comment...

Will look tomorrow.

**Comment by maliberty** [comment]
Why is it easier to comment on a draft PR?

**Comment by oharboe** [comment]
> Why is it easier to comment on a draft PR?

Than to trawl for branches in all the forks?

**Comment by maliberty** [comment]
> > Why is it easier to comment on a draft PR?
> 
> Than to trawl for branches in all the forks?

#697 is a PR already.  Are you suggesting it be turned into a draft PR?  I'm not sure how trawling branches is related.

**Comment by oharboe** [comment]
> Why is it easier to comment on a draft PR?

Mea culpa. My eyes are not what they used to be, it's late here... Going to bed :-)

**Comment by oharboe** [comment]
> > > Why is it easier to comment on a draft PR?
> > 
> > 
> > Than to trawl for branches in all the forks?
> 
> #697 is a PR already. Are you suggesting it be turned into a draft PR? I'm not sure how trawling branches is related.

Mea culpa. Indeed it is. My eyes are not what they used to be, it's late here... Going to bed :-)

**Comment by oharboe** [comment]
Too many things going on, I'm cutting back. Awaiting updates to install scripts in flight.

**Pull request closed without merging**
